import Foundation
import IDAX

func runValueDomainChecks() throws {
    let bounds = try Database.addressBounds()
    try expect(bounds.size == Database.addressSpan(), "Database address bounds disagree with the span")
    try expect(Database.processorIdFromRaw(Database.processorId()) == Database.processor(),
        "Typed processor identity differs from the native identity")
    _ = try Database.processorProfile()
    _ = try Undo.undoActionLabel()
    try expect(Undo.redoActionLabel() == nil, "Fresh database unexpectedly has a redo label")
    let functions = try Functions.all()
    try expect(functions.count == Functions.count(), "Function traversal omitted records")
    if var function = functions.first {
        try function.refresh()
        try expect(function.size == function.end - function.start, "Function snapshot size is incorrect")
        try expect(Functions.tailChunks(address: function.start) == Functions.chunks(address: function.start).filter(\.isTail),
            "Tail chunk filtering lost complete chunk values")
    }

    let start = (bounds.end + 0xfff) & ~Address(0xfff)
    var segment = try Segments.create(start: start, end: start + 0x1000,
        name: "SWIFT_VALUES_TEST", className: "DATA", type: .data)
    defer { try? Segments.remove(address: start) }
    try expect(segment.start == start && segment.size == 0x1000, "Segment create did not return its snapshot")
    try Segments.setPermissions(address: start, permissions: .init(read: true, write: true))
    try segment.refresh()
    try expect(segment.permissions == .init(read: true, write: true), "Segment refresh lost permissions")
    try expect(Segments.all().count == Segments.count(), "Segment traversal omitted records")
    try expect(Segments.last().start == start, "Segment traversal lost database order")
    try IDAX.Data.writeBytes(address: start, data: Array(repeating: 0, count: 128))
    try IDAX.Data.defineDword(address: start, count: 1)
    try expect(Addresses.items(start: start, end: start + 8) == [start], "Item collection included tail bytes")
    try expect(Addresses.dataItems(start: start, end: start + 8) == [start], "Data collection included tail bytes")
    let unknown = try Addresses.unknownBytes(start: start, end: start + 8)
    try expect(unknown == Array((start + 4)..<(start + 8)),
        "Unknown byte collection changed range bounds: offsets \(unknown.map { $0 - start })")
    try expect(Addresses.matching(.tail, start: start, end: start + 4) == Array((start + 1)..<(start + 4)),
        "Predicate collection lost tails")

    try Names.set(address: start, name: "idax_swift_value_named")
    let names = try Names.all(options: .init(start: start, end: start + 8, includeAutoGenerated: false))
    try expect(names.count == 1 && names[0].address == start && names[0].userDefined,
        "Name listing options changed semantic filters")
    let bookmark = try Bookmarks.set(address: start, description: "Swift value bookmark")
    try expect(Bookmarks.atSlot(slot: bookmark.slot) == bookmark, "Allocated bookmark slot did not round-trip")
    try expect(Bookmarks.removeSlot(slot: bookmark.slot), "Bookmark removal lost the boolean result")
    try expect(!Bookmarks.removeSlot(slot: bookmark.slot), "Missing bookmark removal returned true")
    try Problems.remember(kind: .attention, address: start)
    try expect(Problems.contains(kind: .attention, address: start), "Absent optional problem message was not forwarded")
    _ = try Problems.remove(kind: .attention, address: start)
    try expect(Problems.description(kind: .attention, address: start) == nil,
        "Absent problem description became an empty string or failure")

    if let register = try Segments.registers().first {
        let original = try Segments.defaultRegisterValue(address: start, registerName: register.name)
        defer { try? Segments.setDefaultSegmentRegister(address: start, registerName: register.name, value: original) }
        try Segments.setDefaultSegmentRegister(address: start, registerName: register.name, value: 0)
        try expect(Segments.defaultRegisterValue(address: start, registerName: register.name) == 0,
            "Optional segment register zero became absent")
        try Segments.setDefaultSegmentRegister(address: start, registerName: register.name, value: nil)
        try expect(Segments.defaultRegisterValue(address: start, registerName: register.name) == nil,
            "Optional segment register absence became zero")
    }

    try CrossReferences.addData(from: start, to: start + 16, type: .read)
    let reference = try CrossReferences.dataRefsFrom(address: start).first { $0.to == start + 16 }
    try expect(reference?.type == .read && reference?.isCode == false,
        "Data reference collection lost classification")
    try expect(CrossReferences.dataRefsFromRange(address: start) == CrossReferences.dataRefsFrom(address: start),
        "Reference range lost full reference metadata")
    try CrossReferences.removeData(from: start, to: start + 16)
    try Lines.addSourceFile(range: .init(start: start, end: start + 16), filename: "swift-values.c")
    try expect(Lines.sourceFileAt(address: start).filename == "swift-values.c", "Source range adapter lost filename")
    try Lines.removeSourceFile(address: start)

    let fixupAddress = start + 64
    try Fixups.set(at: fixupAddress, descriptor: .init(type: .off64,
        offset: start + 96, displacement: -4))
    let fixup = try Fixups.at(source: fixupAddress)
    try expect(fixup.source == fixupAddress && fixup.type == .off64
        && fixup.offset == start + 96 && fixup.displacement == -4,
        "Fixup descriptor lost its address or signed payload")
    try expect(Fixups.all().contains(fixup), "Fixup traversal omitted its terminal record")
    try Fixups.remove(source: fixupAddress)
    try expect(!Fixups.exists(source: fixupAddress), "Fixup removal did not clear the descriptor")
    let customName = "idax.swift.values.fixup"
    var firstRegistration: Fixups.CustomRegistration? = try Fixups.registerCustom(.init(name: customName))
    let firstID = firstRegistration!.id
    try expect(Fixups.findCustom(named: customName) == firstID, "Custom fixup lookup lost the opaque identity")
    try Fixups.unregisterCustom(firstID)
    let replacement = try Fixups.registerCustom(.init(name: customName))
    defer { try? replacement.close() }
    try expect(replacement.id != firstID, "Custom fixup reuse did not change the identity generation")
    try expectConflict { try Fixups.unregisterCustom(firstID) }
    try firstRegistration!.close()
    try firstRegistration!.close()
    firstRegistration = nil
    try expect(Fixups.findCustom(named: customName) == replacement.id,
        "Old custom fixup owner removed the replacement during close or ARC")
    try replacement.close()

    let processor = try Database.processor()
    if processor == .intelX86 || processor == .arm {
        try Segments.setBitness(address: start, bits: 64)
        let bytes: [UInt8] = processor == .intelX86 ? [0x74, 0x00] : [0x40, 0x00, 0x00, 0x54]
        try IDAX.Data.writeBytes(address: start + 32, data: bytes)
        let instruction = try Instructions.decode(address: start + 32)
        try expect(instruction.branchCondition == .equal, "Conditional branch snapshot lost the condition")
        try expect(Instructions.branchCondition(address: start + 32) == instruction.branchCondition,
            "Branch query differs from decoded snapshot")
        try expect(instruction.operandCount > 0 && instruction.operand(index: 0) == instruction.operands[0],
            "Instruction operand lookup lost its copied value")
    }

    let counters = try Diagnostics.performanceCounters()
    do {
        try Diagnostics.assertInvariant(false, message: "Swift invariant boundary probe")
        throw Failure(description: "Invariant failure did not throw")
    } catch let error as IDAError {
        try expect(error.category == .internalError && error.context == "Swift invariant boundary probe",
            "Invariant failure lost native error context")
    }
    try expect(Diagnostics.performanceCounters().invariantFailures == counters.invariantFailures + 1,
        "Invariant bridge bypassed the canonical performance counters")
    // Empty input is rejected before any server lookup or network operation.
    for operation in [
        { () throws -> Void in _ = try Lumina.pull(addresses: [], skipFrequencyUpdate: true) },
        { () throws -> Void in _ = try Lumina.push(addresses: []) }
    ] {
        do { try operation(); throw Failure(description: "Empty Lumina batch was accepted") }
        catch let error as IDAError { try expect(error.category == .validation, "Unexpected Lumina empty-input error") }
    }
    try expect(!DyldCache.isAvailable(), "Ordinary fixture was classified as a dyld cache")
    print("PASS: Swift value-domain snapshots, optional values, typed branches, reference metadata, ranges, and diagnostics")
}
