// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Addresses {
    public enum Predicate: Int32, CaseIterable, Sendable {
        case mapped = 0
        case loaded = 1
        case code = 2
        case data = 3
        case unknown = 4
        case head = 5
        case tail = 6
    }

    public struct Range: Equatable, Sendable {
        public var start: UInt64
        public var end: UInt64

        public init(start: UInt64 = badAddress, end: UInt64 = badAddress) {
            self.start = start
            self.end = end
        }

        internal init(copying native: IdaxAddressRange, _ operation: String) throws(IDAError) {
            self.start = native.start
            self.end = native.end
        }
    }

    public static func isMapped(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isMapped")
        let result = idax_address_is_mapped(address)
        return result != 0
    }

    public static func isLoaded(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isLoaded")
        let result = idax_address_is_loaded(address)
        return result != 0
    }

    public static func isCode(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isCode")
        let result = idax_address_is_code(address)
        return result != 0
    }

    public static func isData(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isData")
        let result = idax_address_is_data(address)
        return result != 0
    }

    public static func isUnknown(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isUnknown")
        let result = idax_address_is_unknown(address)
        return result != 0
    }

    public static func isHead(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isHead")
        let result = idax_address_is_head(address)
        return result != 0
    }

    public static func isTail(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Addresses.isTail")
        let result = idax_address_is_tail(address)
        return result != 0
    }

    public static func itemStart(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.itemStart")
        var out: UInt64 = 0
        try checkStatus(idax_address_item_start(address, &out), "Addresses.itemStart")
        return out
    }

    public static func itemEnd(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.itemEnd")
        var out: UInt64 = 0
        try checkStatus(idax_address_item_end(address, &out), "Addresses.itemEnd")
        return out
    }

    public static func itemSize(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.itemSize")
        var out: UInt64 = 0
        try checkStatus(idax_address_item_size(address, &out), "Addresses.itemSize")
        return out
    }

    public static func nextHead(address: UInt64, limit: UInt64 = badAddress) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.nextHead")
        var out: UInt64 = 0
        try checkStatus(idax_address_next_head(address, limit, &out), "Addresses.nextHead")
        return out
    }

    public static func prevHead(address: UInt64, limit: UInt64 = 0) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.prevHead")
        var out: UInt64 = 0
        try checkStatus(idax_address_prev_head(address, limit, &out), "Addresses.prevHead")
        return out
    }

    public static func nextNotTail(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.nextNotTail")
        var out: UInt64 = 0
        try checkStatus(idax_address_next_not_tail(address, &out), "Addresses.nextNotTail")
        return out
    }

    public static func prevNotTail(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.prevNotTail")
        var out: UInt64 = 0
        try checkStatus(idax_address_prev_not_tail(address, &out), "Addresses.prevNotTail")
        return out
    }

    public static func nextMapped(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.nextMapped")
        var out: UInt64 = 0
        try checkStatus(idax_address_next_mapped(address, &out), "Addresses.nextMapped")
        return out
    }

    public static func prevMapped(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.prevMapped")
        var out: UInt64 = 0
        try checkStatus(idax_address_prev_mapped(address, &out), "Addresses.prevMapped")
        return out
    }

    public static func findFirst(start: UInt64, end: UInt64, predicate: Addresses.Predicate) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.findFirst")
        var out: UInt64 = 0
        try checkStatus(idax_address_find_first(start, end, Int32(predicate.rawValue), &out), "Addresses.findFirst")
        return out
    }

    public static func findNext(address: UInt64, predicate: Addresses.Predicate, end: UInt64 = badAddress) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Addresses.findNext")
        var out: UInt64 = 0
        try checkStatus(idax_address_find_next(address, Int32(predicate.rawValue), end, &out), "Addresses.findNext")
        return out
    }
}
