// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Analysis {
    public static func isEnabled() throws(IDAError) -> Bool {
        try requireRuntimeThread("Analysis.isEnabled")
        let result = idax_analysis_is_enabled()
        return result != 0
    }

    public static func setEnabled(enabled: Bool) throws(IDAError) {
        try requireRuntimeThread("Analysis.setEnabled")
        try checkStatus(idax_analysis_set_enabled((enabled ? 1 : 0)), "Analysis.setEnabled")
    }

    public static func isIdle() throws(IDAError) -> Bool {
        try requireRuntimeThread("Analysis.isIdle")
        let result = idax_analysis_is_idle()
        return result != 0
    }

    public static func wait() throws(IDAError) {
        try requireRuntimeThread("Analysis.wait")
        try checkStatus(idax_analysis_wait(), "Analysis.wait")
    }

    public static func waitRange(start: UInt64, end: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.waitRange")
        try checkStatus(idax_analysis_wait_range(start, end), "Analysis.waitRange")
    }

    public static func schedule(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.schedule")
        try checkStatus(idax_analysis_schedule(address), "Analysis.schedule")
    }

    public static func scheduleRange(start: UInt64, end: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.scheduleRange")
        try checkStatus(idax_analysis_schedule_range(start, end), "Analysis.scheduleRange")
    }

    public static func scheduleCode(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.scheduleCode")
        try checkStatus(idax_analysis_schedule_code(address), "Analysis.scheduleCode")
    }

    public static func scheduleFunction(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.scheduleFunction")
        try checkStatus(idax_analysis_schedule_function(address), "Analysis.scheduleFunction")
    }

    public static func scheduleReanalysis(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.scheduleReanalysis")
        try checkStatus(idax_analysis_schedule_reanalysis(address), "Analysis.scheduleReanalysis")
    }

    public static func scheduleReanalysisRange(start: UInt64, end: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.scheduleReanalysisRange")
        try checkStatus(idax_analysis_schedule_reanalysis_range(start, end), "Analysis.scheduleReanalysisRange")
    }

    public static func cancel(start: UInt64, end: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.cancel")
        try checkStatus(idax_analysis_cancel(start, end), "Analysis.cancel")
    }

    public static func revertDecisions(start: UInt64, end: UInt64) throws(IDAError) {
        try requireRuntimeThread("Analysis.revertDecisions")
        try checkStatus(idax_analysis_revert_decisions(start, end), "Analysis.revertDecisions")
    }
}
