// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Bookmarks {
    public struct Bookmark: Equatable, Sendable {
        public var address: UInt64
        public var slot: UInt32
        public var description: String

        public init(address: UInt64, slot: UInt32, description: String) {
            self.address = address
            self.slot = slot
            self.description = description
        }

        internal init(copying native: IdaxBookmark, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.slot = native.slot
            self.description = try borrowCString(native.description.map { UnsafePointer($0) }, operation)
        }
    }

    public static func all() throws(IDAError) -> [Bookmarks.Bookmark] {
        try requireRuntimeThread("Bookmarks.all")
        var out: UnsafeMutablePointer<IdaxBookmark>?
        var count: Int = 0
        defer { idax_bookmarks_free(out, count) }
        try checkStatus(idax_bookmark_all(&out, &count), "Bookmarks.all")
        return try copyNativeValues(out, count: count, "Bookmarks.all") { (value) throws(IDAError) -> Bookmarks.Bookmark in try Bookmarks.Bookmark(copying: value, "Bookmarks.all") }
    }

    public static func at(address: UInt64) throws(IDAError) -> Bookmarks.Bookmark? {
        try requireRuntimeThread("Bookmarks.at")
        var out = IdaxBookmark()
        var has_value: Int32 = 0
        defer { idax_bookmark_free(&out) }
        try checkStatus(idax_bookmark_at(address, &out, &has_value), "Bookmarks.at")
        guard has_value != 0 else { return nil }
        return try Bookmarks.Bookmark(copying: out, "Bookmarks.at")
    }

    public static func atSlot(slot: UInt32) throws(IDAError) -> Bookmarks.Bookmark? {
        try requireRuntimeThread("Bookmarks.atSlot")
        var out = IdaxBookmark()
        var has_value: Int32 = 0
        defer { idax_bookmark_free(&out) }
        try checkStatus(idax_bookmark_at_slot(slot, &out, &has_value), "Bookmarks.atSlot")
        guard has_value != 0 else { return nil }
        return try Bookmarks.Bookmark(copying: out, "Bookmarks.atSlot")
    }

    public static func remove(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Bookmarks.remove")
        var out: Int32 = 0
        try checkStatus(idax_bookmark_remove(address, &out), "Bookmarks.remove")
        return out != 0
    }

    public static func removeSlot(slot: UInt32) throws(IDAError) -> Bool {
        try requireRuntimeThread("Bookmarks.removeSlot")
        var out: Int32 = 0
        try checkStatus(idax_bookmark_remove_slot(slot, &out), "Bookmarks.removeSlot")
        return out != 0
    }
}
