// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Comments {
    public static func get(address: UInt64, repeatable: Bool = false) throws(IDAError) -> String {
        try requireRuntimeThread("Comments.get")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_comment_get(address, (repeatable ? 1 : 0), &out), "Comments.get")
        return try borrowCString(out.map { UnsafePointer($0) }, "Comments.get")
    }

    public static func set(address: UInt64, text: String, repeatable: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Comments.set")
        try validateCString(text, "Comments.set")
        try checkStatus(text.withCString { c_text in idax_comment_set(address, c_text, (repeatable ? 1 : 0))}, "Comments.set")
    }

    public static func append(address: UInt64, text: String, repeatable: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Comments.append")
        try validateCString(text, "Comments.append")
        try checkStatus(text.withCString { c_text in idax_comment_append(address, c_text, (repeatable ? 1 : 0))}, "Comments.append")
    }

    public static func remove(address: UInt64, repeatable: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Comments.remove")
        try checkStatus(idax_comment_remove(address, (repeatable ? 1 : 0)), "Comments.remove")
    }

    public static func addAnterior(address: UInt64, text: String) throws(IDAError) {
        try requireRuntimeThread("Comments.addAnterior")
        try validateCString(text, "Comments.addAnterior")
        try checkStatus(text.withCString { c_text in idax_comment_add_anterior(address, c_text)}, "Comments.addAnterior")
    }

    public static func addPosterior(address: UInt64, text: String) throws(IDAError) {
        try requireRuntimeThread("Comments.addPosterior")
        try validateCString(text, "Comments.addPosterior")
        try checkStatus(text.withCString { c_text in idax_comment_add_posterior(address, c_text)}, "Comments.addPosterior")
    }

    public static func getAnterior(address: UInt64, lineIndex: Int32) throws(IDAError) -> String {
        try requireRuntimeThread("Comments.getAnterior")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_comment_get_anterior(address, lineIndex, &out), "Comments.getAnterior")
        return try borrowCString(out.map { UnsafePointer($0) }, "Comments.getAnterior")
    }

    public static func getPosterior(address: UInt64, lineIndex: Int32) throws(IDAError) -> String {
        try requireRuntimeThread("Comments.getPosterior")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_comment_get_posterior(address, lineIndex, &out), "Comments.getPosterior")
        return try borrowCString(out.map { UnsafePointer($0) }, "Comments.getPosterior")
    }

    public static func setAnterior(address: UInt64, lineIndex: Int32, text: String) throws(IDAError) {
        try requireRuntimeThread("Comments.setAnterior")
        try validateCString(text, "Comments.setAnterior")
        try checkStatus(text.withCString { c_text in idax_comment_set_anterior(address, lineIndex, c_text)}, "Comments.setAnterior")
    }

    public static func setPosterior(address: UInt64, lineIndex: Int32, text: String) throws(IDAError) {
        try requireRuntimeThread("Comments.setPosterior")
        try validateCString(text, "Comments.setPosterior")
        try checkStatus(text.withCString { c_text in idax_comment_set_posterior(address, lineIndex, c_text)}, "Comments.setPosterior")
    }

    public static func clearAnterior(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Comments.clearAnterior")
        try checkStatus(idax_comment_clear_anterior(address), "Comments.clearAnterior")
    }

    public static func clearPosterior(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Comments.clearPosterior")
        try checkStatus(idax_comment_clear_posterior(address), "Comments.clearPosterior")
    }

    public static func removeAnteriorLine(address: UInt64, lineIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Comments.removeAnteriorLine")
        try checkStatus(idax_comment_remove_anterior_line(address, lineIndex), "Comments.removeAnteriorLine")
    }

    public static func removePosteriorLine(address: UInt64, lineIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Comments.removePosteriorLine")
        try checkStatus(idax_comment_remove_posterior_line(address, lineIndex), "Comments.removePosteriorLine")
    }

    public static func setAnteriorLines(address: UInt64, lines: [String]) throws(IDAError) {
        try requireRuntimeThread("Comments.setAnteriorLines")
        try checkStatus(try checkedCStringArray(lines, "Comments.setAnteriorLines") { c_lines, c_lines_count in idax_comment_set_anterior_lines(address, c_lines, c_lines_count)}, "Comments.setAnteriorLines")
    }

    public static func setPosteriorLines(address: UInt64, lines: [String]) throws(IDAError) {
        try requireRuntimeThread("Comments.setPosteriorLines")
        try checkStatus(try checkedCStringArray(lines, "Comments.setPosteriorLines") { c_lines, c_lines_count in idax_comment_set_posterior_lines(address, c_lines, c_lines_count)}, "Comments.setPosteriorLines")
    }

    public static func anteriorLines(address: UInt64) throws(IDAError) -> [String] {
        try requireRuntimeThread("Comments.anteriorLines")
        var out: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
        var count: Int = 0
        defer { idax_comment_lines_free(out, count) }
        try checkStatus(idax_comment_anterior_lines(address, &out, &count), "Comments.anteriorLines")
        return try copyNativeValues(out, count: count, "Comments.anteriorLines") { (value) throws(IDAError) -> String in try borrowCString(value.map { UnsafePointer($0) }, "Comments.anteriorLines") }
    }

    public static func posteriorLines(address: UInt64) throws(IDAError) -> [String] {
        try requireRuntimeThread("Comments.posteriorLines")
        var out: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
        var count: Int = 0
        defer { idax_comment_lines_free(out, count) }
        try checkStatus(idax_comment_posterior_lines(address, &out, &count), "Comments.posteriorLines")
        return try copyNativeValues(out, count: count, "Comments.posteriorLines") { (value) throws(IDAError) -> String in try borrowCString(value.map { UnsafePointer($0) }, "Comments.posteriorLines") }
    }

    public static func render(address: UInt64, includeRepeatable: Bool = true, includeExtraLines: Bool = true) throws(IDAError) -> String {
        try requireRuntimeThread("Comments.render")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_comment_render(address, (includeRepeatable ? 1 : 0), (includeExtraLines ? 1 : 0), &out), "Comments.render")
        return try borrowCString(out.map { UnsafePointer($0) }, "Comments.render")
    }
}
