// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum CrossReferences {
    public enum CodeType: Int32, CaseIterable, Sendable {
        case callFar = 0
        case callNear = 1
        case jumpFar = 2
        case jumpNear = 3
        case flow = 4
    }

    public enum DataType: Int32, CaseIterable, Sendable {
        case offset = 0
        case write = 1
        case read = 2
        case text = 3
        case informational = 4
    }

    public enum ReferenceType: Int32, CaseIterable, Sendable {
        case unknown = 0
        case flow = 1
        case callNear = 2
        case callFar = 3
        case jumpNear = 4
        case jumpFar = 5
        case offset = 6
        case read = 7
        case write = 8
        case text = 9
        case informational = 10
    }

    public struct Reference: Equatable, Sendable {
        public var from: UInt64
        public var to: UInt64
        public var isCode: Bool
        public var type: CrossReferences.ReferenceType
        public var userDefined: Bool

        public init(from: UInt64, to: UInt64, isCode: Bool, type: CrossReferences.ReferenceType, userDefined: Bool) {
            self.from = from
            self.to = to
            self.isCode = isCode
            self.type = type
            self.userDefined = userDefined
        }

        internal init(copying native: IdaxXref, _ operation: String) throws(IDAError) {
            self.from = native.from
            self.to = native.to
            self.isCode = native.is_code != 0
            self.type = try checkedNativeEnum(CrossReferences.ReferenceType.self, native.type, operation)
            self.userDefined = native.user_defined != 0
        }
    }

    public static func refsFrom(address: UInt64) throws(IDAError) -> [CrossReferences.Reference] {
        try requireRuntimeThread("CrossReferences.refsFrom")
        var out: UnsafeMutablePointer<IdaxXref>?
        var count: Int = 0
        defer { idax_swift_free_array(out) }
        try checkStatus(idax_xref_refs_from(address, &out, &count), "CrossReferences.refsFrom")
        return try copyNativeValues(out, count: count, "CrossReferences.refsFrom") { (value) throws(IDAError) -> CrossReferences.Reference in try CrossReferences.Reference(copying: value, "CrossReferences.refsFrom") }
    }

    public static func refsTo(address: UInt64) throws(IDAError) -> [CrossReferences.Reference] {
        try requireRuntimeThread("CrossReferences.refsTo")
        var out: UnsafeMutablePointer<IdaxXref>?
        var count: Int = 0
        defer { idax_swift_free_array(out) }
        try checkStatus(idax_xref_refs_to(address, &out, &count), "CrossReferences.refsTo")
        return try copyNativeValues(out, count: count, "CrossReferences.refsTo") { (value) throws(IDAError) -> CrossReferences.Reference in try CrossReferences.Reference(copying: value, "CrossReferences.refsTo") }
    }

    public static func refsFromRange(address: UInt64) throws(IDAError) -> [CrossReferences.Reference] {
        try requireRuntimeThread("CrossReferences.refsFromRange")
        var out: UnsafeMutablePointer<IdaxXref>?
        var count: Int = 0
        defer { idax_swift_free_array(out) }
        try checkStatus(idax_xref_refs_from_range(address, &out, &count), "CrossReferences.refsFromRange")
        return try copyNativeValues(out, count: count, "CrossReferences.refsFromRange") { (value) throws(IDAError) -> CrossReferences.Reference in try CrossReferences.Reference(copying: value, "CrossReferences.refsFromRange") }
    }

    public static func refsToRange(address: UInt64) throws(IDAError) -> [CrossReferences.Reference] {
        try requireRuntimeThread("CrossReferences.refsToRange")
        var out: UnsafeMutablePointer<IdaxXref>?
        var count: Int = 0
        defer { idax_swift_free_array(out) }
        try checkStatus(idax_xref_refs_to_range(address, &out, &count), "CrossReferences.refsToRange")
        return try copyNativeValues(out, count: count, "CrossReferences.refsToRange") { (value) throws(IDAError) -> CrossReferences.Reference in try CrossReferences.Reference(copying: value, "CrossReferences.refsToRange") }
    }

    public static func addCode(from: UInt64, to: UInt64, type: CrossReferences.CodeType) throws(IDAError) {
        try requireRuntimeThread("CrossReferences.addCode")
        try checkStatus(idax_xref_add_code(from, to, Int32(type.rawValue)), "CrossReferences.addCode")
    }

    public static func addData(from: UInt64, to: UInt64, type: CrossReferences.DataType) throws(IDAError) {
        try requireRuntimeThread("CrossReferences.addData")
        try checkStatus(idax_xref_add_data(from, to, Int32(type.rawValue)), "CrossReferences.addData")
    }

    public static func removeCode(from: UInt64, to: UInt64) throws(IDAError) {
        try requireRuntimeThread("CrossReferences.removeCode")
        try checkStatus(idax_xref_remove_code(from, to), "CrossReferences.removeCode")
    }

    public static func removeData(from: UInt64, to: UInt64) throws(IDAError) {
        try requireRuntimeThread("CrossReferences.removeData")
        try checkStatus(idax_xref_remove_data(from, to), "CrossReferences.removeData")
    }
}
