// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Database {
    public enum OpenMode: Int32, CaseIterable, Sendable {
        case analyze = 0
        case skipAnalysis = 1
    }

    public enum LoadIntent: Int32, CaseIterable, Sendable {
        case autoDetect = 0
        case binary = 1
        case nonBinary = 2
    }

    public enum ProcessorId: Int32, CaseIterable, Sendable {
        case intelX86 = 0
        case z80 = 1
        case intelI860 = 2
        case intel8051 = 3
        case tms320C5x = 4
        case mos6502 = 5
        case pdp11 = 6
        case motorola68k = 7
        case javaVm = 8
        case motorola6800 = 9
        case st7 = 10
        case motorola68hc12 = 11
        case mips = 12
        case arm = 13
        case tms320C6x = 14
        case powerPc = 15
        case intel80196 = 16
        case z8 = 17
        case superH = 18
        case dotNet = 19
        case avr = 20
        case h8 = 21
        case pic = 22
        case sparc = 23
        case alpha = 24
        case hppa = 25
        case h8500 = 26
        case triCore = 27
        case dsp56k = 28
        case c166 = 29
        case st20 = 30
        case ia64 = 31
        case intelI960 = 32
        case f2mc16 = 33
        case tms320C54x = 34
        case tms320C55x = 35
        case trimedia = 36
        case m32r = 37
        case nec78k0 = 38
        case nec78k0s = 39
        case mitsubishiM740 = 40
        case mitsubishiM7700 = 41
        case st9 = 42
        case fujitsuFr = 43
        case motorola68hc16 = 44
        case mitsubishiM7900 = 45
        case tms320C3 = 46
        case kr1878 = 47
        case adsp218x = 48
        case oakDsp = 49
        case tlcs900 = 50
        case rockwellC39 = 51
        case cr16 = 52
        case mn10200 = 53
        case tms320C1x = 54
        case necV850x = 55
        case scriptAdapter = 56
        case efiBytecode = 57
        case msp430 = 58
        case spu = 59
        case dalvik = 60
        case wdc65c816 = 61
        case m16c = 62
        case arc = 63
        case unsp = 64
        case tms320C28x = 65
        case dsp96000 = 66
        case spc700 = 67
        case adsp2106x = 68
        case pic16 = 69
        case s390 = 70
        case xtensa = 71
        case riscV = 72
        case rl78 = 73
        case rx = 74
        case wasm = 75
        case nds32 = 76
        case mcore = 77
    }

    public struct CompilerInfo: Equatable, Sendable {
        public var id: UInt32
        public var uncertain: Bool
        public var name: String
        public var abbreviation: String

        public init(id: UInt32, uncertain: Bool, name: String, abbreviation: String) {
            self.id = id
            self.uncertain = uncertain
            self.name = name
            self.abbreviation = abbreviation
        }

        internal init(copying native: IdaxDatabaseCompilerInfo, _ operation: String) throws(IDAError) {
            self.id = native.id
            self.uncertain = native.uncertain != 0
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.abbreviation = try borrowCString(native.abbreviation.map { UnsafePointer($0) }, operation)
        }
    }

    public struct ImportSymbol: Equatable, Sendable {
        public var address: UInt64
        public var name: String
        public var ordinal: UInt64

        public init(address: UInt64, name: String, ordinal: UInt64) {
            self.address = address
            self.name = name
            self.ordinal = ordinal
        }

        internal init(copying native: IdaxDatabaseImportSymbol, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.ordinal = native.ordinal
        }
    }

    public struct ImportModule: Equatable, Sendable {
        public var index: Int
        public var name: String
        public var symbols: [Database.ImportSymbol]

        public init(index: Int, name: String, symbols: [Database.ImportSymbol]) {
            self.index = index
            self.name = name
            self.symbols = symbols
        }

        internal init(copying native: IdaxDatabaseImportModule, _ operation: String) throws(IDAError) {
            self.index = native.index
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.symbols = try copyNativeValues(native.symbols, count: Int(native.symbol_count), operation) { (value) throws(IDAError) -> Database.ImportSymbol in try Database.ImportSymbol(copying: value, operation) }
        }
    }

    public struct Snapshot: Equatable, Sendable {
        public var id: Int64
        public var flags: UInt16
        public var description: String
        public var filename: String
        public var children: [Database.Snapshot]

        public init(id: Int64, flags: UInt16, description: String, filename: String, children: [Database.Snapshot]) {
            self.id = id
            self.flags = flags
            self.description = description
            self.filename = filename
            self.children = children
        }

        internal init(copying native: IdaxDatabaseSnapshot, _ operation: String) throws(IDAError) {
            self.id = native.id
            self.flags = native.flags
            self.description = try borrowCString(native.description.map { UnsafePointer($0) }, operation)
            self.filename = try borrowCString(native.filename.map { UnsafePointer($0) }, operation)
            self.children = try copyNativeValues(native.children, count: Int(native.child_count), operation) { (value) throws(IDAError) -> Database.Snapshot in try Database.Snapshot(copying: value, operation) }
        }
    }

    public struct ProcessorProfile: Equatable, Sendable {
        public var rawId: Int32
        public var knownId: Database.ProcessorId?
        public var name: String
        public var addressBitness: Int32
        public var bigEndian: Bool
        public var abiName: String?

        public init(rawId: Int32, knownId: Database.ProcessorId?, name: String, addressBitness: Int32, bigEndian: Bool, abiName: String?) {
            self.rawId = rawId
            self.knownId = knownId
            self.name = name
            self.addressBitness = addressBitness
            self.bigEndian = bigEndian
            self.abiName = abiName
        }

        internal init(copying native: IdaxDatabaseProcessorProfile, _ operation: String) throws(IDAError) {
            self.rawId = native.raw_id
            self.knownId = native.has_known_id != 0 ? (try checkedNativeEnum(Database.ProcessorId.self, native.known_id, operation)) : nil
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.addressBitness = native.address_bitness
            self.bigEndian = native.big_endian != 0
            self.abiName = native.abi_name == nil ? nil : (try borrowCString(native.abi_name.map { UnsafePointer($0) }, operation))
        }
    }

    public static func save() throws(IDAError) {
        try requireRuntimeThread("Database.save")
        try checkStatus(idax_database_save(), "Database.save")
    }

    public static func saveTo(outputDatabasePath: String) throws(IDAError) {
        try requireRuntimeThread("Database.saveTo")
        try validateCString(outputDatabasePath, "Database.saveTo")
        try checkStatus(outputDatabasePath.withCString { c_output_database_path in idax_database_save_to(c_output_database_path)}, "Database.saveTo")
    }

    public static func fileToDatabase(filePath: String, fileOffset: Int64, address: UInt64, size: UInt64, patchable: Bool = true, remote: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Database.fileToDatabase")
        try validateCString(filePath, "Database.fileToDatabase")
        try checkStatus(filePath.withCString { c_file_path in idax_database_file_to_database(c_file_path, fileOffset, address, size, (patchable ? 1 : 0), (remote ? 1 : 0))}, "Database.fileToDatabase")
    }

    public static func memoryToDatabase(bytes: [UInt8], address: UInt64, fileOffset: Int64 = -1) throws(IDAError) {
        try requireRuntimeThread("Database.memoryToDatabase")
        try checkStatus(bytes.withUnsafeBufferPointer { c_bytes_buffer in let c_bytes = c_bytes_buffer.baseAddress; let c_bytes_count = c_bytes_buffer.count; return idax_database_memory_to_database(c_bytes, c_bytes_count, address, fileOffset)}, "Database.memoryToDatabase")
    }

    public static func compilerInfo() throws(IDAError) -> Database.CompilerInfo {
        try requireRuntimeThread("Database.compilerInfo")
        var out = IdaxDatabaseCompilerInfo()
        defer { idax_database_compiler_info_free(&out) }
        try checkStatus(idax_database_compiler_info(&out), "Database.compilerInfo")
        return try Database.CompilerInfo(copying: out, "Database.compilerInfo")
    }

    public static func importModules() throws(IDAError) -> [Database.ImportModule] {
        try requireRuntimeThread("Database.importModules")
        var out: UnsafeMutablePointer<IdaxDatabaseImportModule>?
        var count: Int = 0
        defer { idax_database_import_modules_free(out, count) }
        try checkStatus(idax_database_import_modules(&out, &count), "Database.importModules")
        return try copyNativeValues(out, count: count, "Database.importModules") { (value) throws(IDAError) -> Database.ImportModule in try Database.ImportModule(copying: value, "Database.importModules") }
    }

    public static func snapshots() throws(IDAError) -> [Database.Snapshot] {
        try requireRuntimeThread("Database.snapshots")
        var out: UnsafeMutablePointer<IdaxDatabaseSnapshot>?
        var count: Int = 0
        defer { idax_database_snapshots_free(out, count) }
        try checkStatus(idax_database_snapshots(&out, &count), "Database.snapshots")
        return try copyNativeValues(out, count: count, "Database.snapshots") { (value) throws(IDAError) -> Database.Snapshot in try Database.Snapshot(copying: value, "Database.snapshots") }
    }

    public static func setSnapshotDescription(description: String) throws(IDAError) {
        try requireRuntimeThread("Database.setSnapshotDescription")
        try validateCString(description, "Database.setSnapshotDescription")
        try checkStatus(description.withCString { c_description in idax_database_set_snapshot_description(c_description)}, "Database.setSnapshotDescription")
    }

    public static func isSnapshotDatabase() throws(IDAError) -> Bool {
        try requireRuntimeThread("Database.isSnapshotDatabase")
        var out: Int32 = 0
        try checkStatus(idax_database_is_snapshot_database(&out), "Database.isSnapshotDatabase")
        return out != 0
    }

    public static func inputFilePath() throws(IDAError) -> String {
        try requireRuntimeThread("Database.inputFilePath")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_input_file_path(&out), "Database.inputFilePath")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.inputFilePath")
    }

    public static func idbPath() throws(IDAError) -> String {
        try requireRuntimeThread("Database.idbPath")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_idb_path(&out), "Database.idbPath")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.idbPath")
    }

    public static func fileTypeName() throws(IDAError) -> String {
        try requireRuntimeThread("Database.fileTypeName")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_file_type_name(&out), "Database.fileTypeName")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.fileTypeName")
    }

    public static func loaderFormatName() throws(IDAError) -> String {
        try requireRuntimeThread("Database.loaderFormatName")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_loader_format_name(&out), "Database.loaderFormatName")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.loaderFormatName")
    }

    public static func inputMd5() throws(IDAError) -> String {
        try requireRuntimeThread("Database.inputMd5")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_input_md5(&out), "Database.inputMd5")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.inputMd5")
    }

    public static func imageBase() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Database.imageBase")
        var out: UInt64 = 0
        try checkStatus(idax_database_image_base(&out), "Database.imageBase")
        return out
    }

    public static func minAddress() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Database.minAddress")
        var out: UInt64 = 0
        try checkStatus(idax_database_min_address(&out), "Database.minAddress")
        return out
    }

    public static func maxAddress() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Database.maxAddress")
        var out: UInt64 = 0
        try checkStatus(idax_database_max_address(&out), "Database.maxAddress")
        return out
    }

    public static func processorId() throws(IDAError) -> Int32 {
        try requireRuntimeThread("Database.processorId")
        var out: Int32 = 0
        try checkStatus(idax_database_processor_id(&out), "Database.processorId")
        return out
    }

    public static func processorProfile() throws(IDAError) -> Database.ProcessorProfile {
        try requireRuntimeThread("Database.processorProfile")
        var out = IdaxDatabaseProcessorProfile()
        defer { idax_database_processor_profile_free(&out) }
        try checkStatus(idax_database_processor_profile(&out), "Database.processorProfile")
        return try Database.ProcessorProfile(copying: out, "Database.processorProfile")
    }

    public static func processorName() throws(IDAError) -> String {
        try requireRuntimeThread("Database.processorName")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_processor_name(&out), "Database.processorName")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.processorName")
    }

    public static func addressBitness() throws(IDAError) -> Int32 {
        try requireRuntimeThread("Database.addressBitness")
        var out: Int32 = 0
        try checkStatus(idax_database_address_bitness(&out), "Database.addressBitness")
        return out
    }

    public static func setAddressBitness(bits: Int32) throws(IDAError) {
        try requireRuntimeThread("Database.setAddressBitness")
        try checkStatus(idax_database_set_address_bitness(bits), "Database.setAddressBitness")
    }

    public static func isBigEndian() throws(IDAError) -> Bool {
        try requireRuntimeThread("Database.isBigEndian")
        var out: Int32 = 0
        try checkStatus(idax_database_is_big_endian(&out), "Database.isBigEndian")
        return out != 0
    }

    public static func abiName() throws(IDAError) -> String {
        try requireRuntimeThread("Database.abiName")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_database_abi_name(&out), "Database.abiName")
        return try borrowCString(out.map { UnsafePointer($0) }, "Database.abiName")
    }

    public static func addressSpan() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Database.addressSpan")
        var out: UInt64 = 0
        try checkStatus(idax_database_address_span(&out), "Database.addressSpan")
        return out
    }
}
