// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Data {
    public enum TypedValueKind: Int32, CaseIterable, Sendable {
        case unsignedInteger = 0
        case signedInteger = 1
        case floatingPoint = 2
        case pointer = 3
        case string = 4
        case bytes = 5
        case array = 6
    }

    public struct StringListOptions: Equatable, Sendable {
        public var stringTypes: [Int32]
        public var minimumLength: Int64
        public var only7bit: Bool
        public var ignoreInstructions: Bool
        public var displayOnlyExistingStrings: Bool

        public init(stringTypes: [Int32] = [0], minimumLength: Int64 = 5, only7bit: Bool = true, ignoreInstructions: Bool = false, displayOnlyExistingStrings: Bool = false) {
            self.stringTypes = stringTypes
            self.minimumLength = minimumLength
            self.only7bit = only7bit
            self.ignoreInstructions = ignoreInstructions
            self.displayOnlyExistingStrings = displayOnlyExistingStrings
        }

        internal init(copying native: IdaxDataStringListOptions, _ operation: String) throws(IDAError) {
            self.stringTypes = try copyNativeValues(native.string_types, count: Int(native.string_type_count), operation) { (value) throws(IDAError) -> Int32 in value }
            self.minimumLength = native.minimum_length
            self.only7bit = native.only_7bit != 0
            self.ignoreInstructions = native.ignore_instructions != 0
            self.displayOnlyExistingStrings = native.display_only_existing_strings != 0
        }
    }

    public struct StringLiteral: Equatable, Sendable {
        public var address: UInt64
        public var byteLength: UInt64
        public var stringType: Int32
        public var text: String

        public init(address: UInt64 = badAddress, byteLength: UInt64 = 0, stringType: Int32 = 0, text: String = "") {
            self.address = address
            self.byteLength = byteLength
            self.stringType = stringType
            self.text = text
        }

        internal init(copying native: IdaxDataStringLiteral, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.byteLength = native.byte_length
            self.stringType = native.string_type
            self.text = try borrowCString(native.text.map { UnsafePointer($0) }, operation)
        }
    }

    public static func readByte(address: UInt64) throws(IDAError) -> UInt8 {
        try requireRuntimeThread("Data.readByte")
        var out: UInt8 = 0
        try checkStatus(idax_data_read_byte(address, &out), "Data.readByte")
        return out
    }

    public static func readWord(address: UInt64) throws(IDAError) -> UInt16 {
        try requireRuntimeThread("Data.readWord")
        var out: UInt16 = 0
        try checkStatus(idax_data_read_word(address, &out), "Data.readWord")
        return out
    }

    public static func readDword(address: UInt64) throws(IDAError) -> UInt32 {
        try requireRuntimeThread("Data.readDword")
        var out: UInt32 = 0
        try checkStatus(idax_data_read_dword(address, &out), "Data.readDword")
        return out
    }

    public static func readQword(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Data.readQword")
        var out: UInt64 = 0
        try checkStatus(idax_data_read_qword(address, &out), "Data.readQword")
        return out
    }

    public static func readBytes(address: UInt64, count: UInt64) throws(IDAError) -> [UInt8] {
        try requireRuntimeThread("Data.readBytes")
        var out: UnsafeMutablePointer<UInt8>?
        var out_len: Int = 0
        defer { idax_free_bytes(out) }
        try checkStatus(idax_data_read_bytes(address, count, &out, &out_len), "Data.readBytes")
        return try copyNativeValues(out, count: out_len, "Data.readBytes") { (value) throws(IDAError) -> UInt8 in value }
    }

    public static func stringListOptions() throws(IDAError) -> Data.StringListOptions {
        try requireRuntimeThread("Data.stringListOptions")
        var out = IdaxDataStringListOptions()
        defer { idax_data_string_list_options_free(&out) }
        try checkStatus(idax_data_string_list_options(&out), "Data.stringListOptions")
        return try Data.StringListOptions(copying: out, "Data.stringListOptions")
    }

    public static func configureStringList(stringTypes: [Int32], minimumLength: Int64, only7bit: Bool, ignoreInstructions: Bool, displayOnlyExistingStrings: Bool) throws(IDAError) {
        try requireRuntimeThread("Data.configureStringList")
        try checkStatus(stringTypes.withUnsafeBufferPointer { c_string_types_buffer in let c_string_types = c_string_types_buffer.baseAddress; let c_string_types_count = c_string_types_buffer.count; return idax_data_configure_string_list(c_string_types, c_string_types_count, minimumLength, (only7bit ? 1 : 0), (ignoreInstructions ? 1 : 0), (displayOnlyExistingStrings ? 1 : 0))}, "Data.configureStringList")
    }

    public static func rebuildStringList() throws(IDAError) {
        try requireRuntimeThread("Data.rebuildStringList")
        try checkStatus(idax_data_rebuild_string_list(), "Data.rebuildStringList")
    }

    public static func clearStringList() throws(IDAError) {
        try requireRuntimeThread("Data.clearStringList")
        try checkStatus(idax_data_clear_string_list(), "Data.clearStringList")
    }

    public static func stringLiterals(rebuild: Bool = true) throws(IDAError) -> [Data.StringLiteral] {
        try requireRuntimeThread("Data.stringLiterals")
        var out: UnsafeMutablePointer<IdaxDataStringLiteral>?
        var count: Int = 0
        defer { idax_data_string_literals_free(out, count) }
        try checkStatus(idax_data_string_literals((rebuild ? 1 : 0), &out, &count), "Data.stringLiterals")
        return try copyNativeValues(out, count: count, "Data.stringLiterals") { (value) throws(IDAError) -> Data.StringLiteral in try Data.StringLiteral(copying: value, "Data.stringLiterals") }
    }

    public static func writeByte(address: UInt64, value: UInt8) throws(IDAError) {
        try requireRuntimeThread("Data.writeByte")
        try checkStatus(idax_data_write_byte(address, value), "Data.writeByte")
    }

    public static func writeWord(address: UInt64, value: UInt16) throws(IDAError) {
        try requireRuntimeThread("Data.writeWord")
        try checkStatus(idax_data_write_word(address, value), "Data.writeWord")
    }

    public static func writeDword(address: UInt64, value: UInt32) throws(IDAError) {
        try requireRuntimeThread("Data.writeDword")
        try checkStatus(idax_data_write_dword(address, value), "Data.writeDword")
    }

    public static func writeQword(address: UInt64, value: UInt64) throws(IDAError) {
        try requireRuntimeThread("Data.writeQword")
        try checkStatus(idax_data_write_qword(address, value), "Data.writeQword")
    }

    public static func writeBytes(address: UInt64, data: [UInt8]) throws(IDAError) {
        try requireRuntimeThread("Data.writeBytes")
        try checkStatus(data.withUnsafeBufferPointer { c_data_buffer in let c_data = c_data_buffer.baseAddress; let c_data_count = c_data_buffer.count; return idax_data_write_bytes(address, c_data, c_data_count)}, "Data.writeBytes")
    }

    public static func patchByte(address: UInt64, value: UInt8) throws(IDAError) {
        try requireRuntimeThread("Data.patchByte")
        try checkStatus(idax_data_patch_byte(address, value), "Data.patchByte")
    }

    public static func patchWord(address: UInt64, value: UInt16) throws(IDAError) {
        try requireRuntimeThread("Data.patchWord")
        try checkStatus(idax_data_patch_word(address, value), "Data.patchWord")
    }

    public static func patchDword(address: UInt64, value: UInt32) throws(IDAError) {
        try requireRuntimeThread("Data.patchDword")
        try checkStatus(idax_data_patch_dword(address, value), "Data.patchDword")
    }

    public static func patchQword(address: UInt64, value: UInt64) throws(IDAError) {
        try requireRuntimeThread("Data.patchQword")
        try checkStatus(idax_data_patch_qword(address, value), "Data.patchQword")
    }

    public static func patchBytes(address: UInt64, data: [UInt8]) throws(IDAError) {
        try requireRuntimeThread("Data.patchBytes")
        try checkStatus(data.withUnsafeBufferPointer { c_data_buffer in let c_data = c_data_buffer.baseAddress; let c_data_count = c_data_buffer.count; return idax_data_patch_bytes(address, c_data, c_data_count)}, "Data.patchBytes")
    }

    public static func revertPatch(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Data.revertPatch")
        try checkStatus(idax_data_revert_patch(address), "Data.revertPatch")
    }

    public static func revertPatches(address: UInt64, count: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Data.revertPatches")
        var reverted: UInt64 = 0
        try checkStatus(idax_data_revert_patches(address, count, &reverted), "Data.revertPatches")
        return reverted
    }

    public static func originalByte(address: UInt64) throws(IDAError) -> UInt8 {
        try requireRuntimeThread("Data.originalByte")
        var out: UInt8 = 0
        try checkStatus(idax_data_original_byte(address, &out), "Data.originalByte")
        return out
    }

    public static func originalWord(address: UInt64) throws(IDAError) -> UInt16 {
        try requireRuntimeThread("Data.originalWord")
        var out: UInt16 = 0
        try checkStatus(idax_data_original_word(address, &out), "Data.originalWord")
        return out
    }

    public static func originalDword(address: UInt64) throws(IDAError) -> UInt32 {
        try requireRuntimeThread("Data.originalDword")
        var out: UInt32 = 0
        try checkStatus(idax_data_original_dword(address, &out), "Data.originalDword")
        return out
    }

    public static func originalQword(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Data.originalQword")
        var out: UInt64 = 0
        try checkStatus(idax_data_original_qword(address, &out), "Data.originalQword")
        return out
    }

    public static func defineByte(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineByte")
        try checkStatus(idax_data_define_byte(address, count), "Data.defineByte")
    }

    public static func defineWord(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineWord")
        try checkStatus(idax_data_define_word(address, count), "Data.defineWord")
    }

    public static func defineDword(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineDword")
        try checkStatus(idax_data_define_dword(address, count), "Data.defineDword")
    }

    public static func defineQword(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineQword")
        try checkStatus(idax_data_define_qword(address, count), "Data.defineQword")
    }

    public static func defineOword(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineOword")
        try checkStatus(idax_data_define_oword(address, count), "Data.defineOword")
    }

    public static func defineYword(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineYword")
        try checkStatus(idax_data_define_yword(address, count), "Data.defineYword")
    }

    public static func defineZword(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineZword")
        try checkStatus(idax_data_define_zword(address, count), "Data.defineZword")
    }

    public static func tbyteElementSize() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Data.tbyteElementSize")
        var out: UInt64 = 0
        try checkStatus(idax_data_tbyte_element_size(&out), "Data.tbyteElementSize")
        return out
    }

    public static func defineTbyte(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineTbyte")
        try checkStatus(idax_data_define_tbyte(address, count), "Data.defineTbyte")
    }

    public static func packedRealElementSize() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Data.packedRealElementSize")
        var out: UInt64 = 0
        try checkStatus(idax_data_packed_real_element_size(&out), "Data.packedRealElementSize")
        return out
    }

    public static func definePackedReal(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.definePackedReal")
        try checkStatus(idax_data_define_packed_real(address, count), "Data.definePackedReal")
    }

    public static func defineFloat(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineFloat")
        try checkStatus(idax_data_define_float(address, count), "Data.defineFloat")
    }

    public static func defineDouble(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.defineDouble")
        try checkStatus(idax_data_define_double(address, count), "Data.defineDouble")
    }

    public static func defineString(address: UInt64, length: UInt64, stringType: Int32 = 0) throws(IDAError) {
        try requireRuntimeThread("Data.defineString")
        try checkStatus(idax_data_define_string(address, length, stringType), "Data.defineString")
    }

    public static func defineStruct(address: UInt64, length: UInt64, structureId: UInt64) throws(IDAError) {
        try requireRuntimeThread("Data.defineStruct")
        try checkStatus(idax_data_define_struct(address, length, structureId), "Data.defineStruct")
    }

    public static func undefine(address: UInt64, count: UInt64 = 1) throws(IDAError) {
        try requireRuntimeThread("Data.undefine")
        try checkStatus(idax_data_undefine(address, count), "Data.undefine")
    }
}
