// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Decompiler {
    public enum Maturity: Int32, CaseIterable, Sendable {
        case zero = 0
        case built = 1
        case trans1 = 2
        case nice = 3
        case trans2 = 4
        case cpa = 5
        case trans3 = 6
        case casted = 7
        case final = 8
    }

    public enum MicrocodeApplyResult: Int32, CaseIterable, Sendable {
        case notHandled = 0
        case handled = 1
        case error = 2
    }

    public enum MicrocodeOpcode: Int32, CaseIterable, Sendable {
        case noOperation = 0
        case move = 1
        case add = 2
        case subtract = 3
        case multiply = 4
        case zeroExtend = 5
        case loadMemory = 6
        case storeMemory = 7
        case bitwiseOr = 8
        case bitwiseAnd = 9
        case bitwiseXor = 10
        case shiftLeft = 11
        case shiftRightLogical = 12
        case shiftRightArithmetic = 13
        case floatAdd = 14
        case floatSub = 15
        case floatMul = 16
        case floatDiv = 17
        case integerToFloat = 18
        case floatToFloat = 19
        case signedExtend = 20
        case call = 21
        case indirectCall = 22
        case goto = 23
        case indirectJump = 24
        case `return` = 25
        case other = 26
        case negate = 27
        case logicalNot = 28
        case bitwiseNot = 29
        case lowPart = 30
        case highPart = 31
        case unsignedDivide = 32
        case signedDivide = 33
        case unsignedRemainder = 34
        case signedRemainder = 35
        case carryFromAdd = 36
        case overflowFromAdd = 37
        case carryFromShiftLeft = 38
        case carryFromShiftRight = 39
        case setNegative = 40
        case setOverflow = 41
        case setParity = 42
        case setNotEqual = 43
        case setEqual = 44
        case setGreaterThanOrEqualUnsigned = 45
        case setLessThanUnsigned = 46
        case setGreaterThanUnsigned = 47
        case setLessThanOrEqualUnsigned = 48
        case setGreaterThanSigned = 49
        case setGreaterThanOrEqualSigned = 50
        case setLessThanSigned = 51
        case setLessThanOrEqualSigned = 52
        case jumpIfNonzero = 53
        case jumpIfNotEqual = 54
        case jumpIfEqual = 55
        case jumpIfGreaterThanOrEqualUnsigned = 56
        case jumpIfLessThanUnsigned = 57
        case jumpIfGreaterThanUnsigned = 58
        case jumpIfLessThanOrEqualUnsigned = 59
        case jumpIfGreaterThanSigned = 60
        case jumpIfGreaterThanOrEqualSigned = 61
        case jumpIfLessThanSigned = 62
        case jumpIfLessThanOrEqualSigned = 63
        case jumpTable = 64
        case push = 65
        case pop = 66
        case undefined = 67
        case external = 68
        case floatToSignedInteger = 69
        case floatToUnsignedInteger = 70
        case unsignedIntegerToFloat = 71
        case floatNegate = 72
        case loadConstant = 73
    }

    public enum MicrocodeOperandKind: Int32, CaseIterable, Sendable {
        case empty = 0
        case register = 1
        case localVariable = 2
        case registerPair = 3
        case globalAddress = 4
        case stackVariable = 5
        case helperReference = 6
        case blockReference = 7
        case nestedInstruction = 8
        case unsignedImmediate = 9
        case signedImmediate = 10
        case addressReference = 11
        case callArguments = 12
        case stringConstant = 13
        case floatingPointConstant = 14
        case other = 15
        case switchCases = 16
    }

    public enum MicrocodeMaturity: Int32, CaseIterable, Sendable {
        case generated = 1
        case preoptimized = 2
        case locallyOptimized = 3
        case callsAnalyzed = 4
        case globallyOptimized1 = 5
        case globallyOptimized2 = 6
        case globallyOptimized3 = 7
        case localVariables = 8
    }

    public enum MicrocodeInsertPolicy: Int32, CaseIterable, Sendable {
        case tail = 0
        case beginning = 1
        case beforeTail = 2
    }

    public enum MicrocodeValueKind: Int32, CaseIterable, Sendable {
        case register = 0
        case localVariable = 1
        case registerPair = 2
        case globalAddress = 3
        case stackVariable = 4
        case helperReference = 5
        case blockReference = 6
        case nestedInstruction = 7
        case unsignedImmediate = 8
        case signedImmediate = 9
        case float32Immediate = 10
        case float64Immediate = 11
        case byteArray = 12
        case vector = 13
        case typeDeclarationView = 14
    }

    public enum MicrocodeValueLocationKind: Int32, CaseIterable, Sendable {
        case unspecified = 0
        case register = 1
        case registerWithOffset = 2
        case registerPair = 3
        case registerRelative = 4
        case stackOffset = 5
        case staticAddress = 6
        case scattered = 7
    }

    public enum MicrocodeBlockKind: Int32, CaseIterable, Sendable {
        case unknown = 0
        case exit = 1
        case nonReturning = 2
        case singleSuccessor = 3
        case conditional = 4
        case `switch` = 5
        case external = 6
    }

    public enum MicrocodeArgumentFlag: Int32, CaseIterable, Sendable {
        case hiddenArgument = 1
        case returnValuePointer = 2
        case structArgument = 4
        case arrayArgument = 8
        case unusedArgument = 16
    }

    public enum MicrocodeCallingConvention: Int32, CaseIterable, Sendable {
        case unspecified = 0
        case cdecl = 1
        case stdcall = 2
        case fastcall = 3
        case thiscall = 4
    }

    public enum MicrocodeFunctionRole: Int32, CaseIterable, Sendable {
        case unknown = 0
        case empty = 1
        case memset = 2
        case memset32 = 3
        case memset64 = 4
        case memcpy = 5
        case strcpy = 6
        case strlen = 7
        case strcat = 8
        case tail = 9
        case bug = 10
        case alloca = 11
        case byteSwap = 12
        case present = 13
        case containingRecord = 14
        case fastFail = 15
        case readFlags = 16
        case isMulOk = 17
        case saturatedMul = 18
        case bitTest = 19
        case bitTestAndSet = 20
        case bitTestAndReset = 21
        case bitTestAndComplement = 22
        case vaArg = 23
        case vaCopy = 24
        case vaStart = 25
        case vaEnd = 26
        case rotateLeft = 27
        case rotateRight = 28
        case carryFlagSub3 = 29
        case overflowFlagSub3 = 30
        case absoluteValue = 31
        case threeWayCompare0 = 32
        case threeWayCompare1 = 33
        case wideMemCopy = 34
        case wideMemSet = 35
        case wideStrCopy = 36
        case wideStrLen = 37
        case wideStrCat = 38
        case sseCompare4 = 39
        case sseCompare8 = 40
    }

    public enum VariableStorage: Int32, CaseIterable, Sendable {
        case unknown = 0
        case register = 1
        case stack = 2
    }

    public enum LocalVariableLocationKind: Int32, CaseIterable, Sendable {
        case none = 0
        case register = 1
        case stack = 2
    }

    public enum ItemType: Int32, CaseIterable, Sendable {
        case exprEmpty = 0
        case exprComma = 1
        case exprAssign = 2
        case exprAssignBitOr = 3
        case exprAssignXor = 4
        case exprAssignBitAnd = 5
        case exprAssignAdd = 6
        case exprAssignSub = 7
        case exprAssignMul = 8
        case exprAssignShiftRightSigned = 9
        case exprAssignShiftRightUnsigned = 10
        case exprAssignShiftLeft = 11
        case exprAssignDivSigned = 12
        case exprAssignDivUnsigned = 13
        case exprAssignModSigned = 14
        case exprAssignModUnsigned = 15
        case exprTernary = 16
        case exprLogicalOr = 17
        case exprLogicalAnd = 18
        case exprBitOr = 19
        case exprXor = 20
        case exprBitAnd = 21
        case exprEqual = 22
        case exprNotEqual = 23
        case exprSignedGE = 24
        case exprUnsignedGE = 25
        case exprSignedLE = 26
        case exprUnsignedLE = 27
        case exprSignedGT = 28
        case exprUnsignedGT = 29
        case exprSignedLT = 30
        case exprUnsignedLT = 31
        case exprShiftRightSigned = 32
        case exprShiftRightUnsigned = 33
        case exprShiftLeft = 34
        case exprAdd = 35
        case exprSub = 36
        case exprMul = 37
        case exprDivSigned = 38
        case exprDivUnsigned = 39
        case exprModSigned = 40
        case exprModUnsigned = 41
        case exprFloatAdd = 42
        case exprFloatSub = 43
        case exprFloatMul = 44
        case exprFloatDiv = 45
        case exprFloatNeg = 46
        case exprNeg = 47
        case exprCast = 48
        case exprLogicalNot = 49
        case exprBitNot = 50
        case exprDeref = 51
        case exprRef = 52
        case exprPostInc = 53
        case exprPostDec = 54
        case exprPreInc = 55
        case exprPreDec = 56
        case exprCall = 57
        case exprIndex = 58
        case exprMemberRef = 59
        case exprMemberPtr = 60
        case exprNumber = 61
        case exprFloatNumber = 62
        case exprString = 63
        case exprObject = 64
        case exprVariable = 65
        case exprInsn = 66
        case exprSizeof = 67
        case exprHelper = 68
        case exprType = 69
        public static let exprLast = Self.exprType
        case stmtEmpty = 70
        case stmtBlock = 71
        case stmtExpr = 72
        case stmtIf = 73
        case stmtFor = 74
        case stmtWhile = 75
        case stmtDo = 76
        case stmtSwitch = 77
        case stmtBreak = 78
        case stmtContinue = 79
        case stmtReturn = 80
        case stmtGoto = 81
        case stmtAsm = 82
        case stmtTry = 83
        case stmtThrow = 84
    }

    public enum VisitAction: Int32, CaseIterable, Sendable {
        case `continue` = 0
        case stop = 1
        case skipChildren = 2
    }

    public enum CommentPositionKind: Int32, CaseIterable, Sendable {
        case `default` = 0
        case argument = 1
        case parenthesisOpen = 2
        case assembly = 3
        case elseLine = 4
        case doLine = 5
        case semicolon = 6
        case openBrace = 7
        case closeBrace = 8
        case parenthesisClose = 9
        case labelColon = 10
        case blockBefore = 11
        case blockAfter = 12
        case tryLine = 13
        case switchCase = 14
    }

    public struct MicrocodeLocationPart: Equatable, Sendable {
        public var kind: Decompiler.MicrocodeValueLocationKind
        public var registerId: Int32
        public var secondRegisterId: Int32
        public var registerOffset: Int32
        public var registerRelativeOffset: Int64
        public var stackOffset: Int64
        public var staticAddress: UInt64
        public var byteOffset: Int32
        public var byteSize: Int32

        public init(kind: Decompiler.MicrocodeValueLocationKind = .unspecified, registerId: Int32 = 0, secondRegisterId: Int32 = 0, registerOffset: Int32 = 0, registerRelativeOffset: Int64 = 0, stackOffset: Int64 = 0, staticAddress: UInt64 = badAddress, byteOffset: Int32 = 0, byteSize: Int32 = 0) {
            self.kind = kind
            self.registerId = registerId
            self.secondRegisterId = secondRegisterId
            self.registerOffset = registerOffset
            self.registerRelativeOffset = registerRelativeOffset
            self.stackOffset = stackOffset
            self.staticAddress = staticAddress
            self.byteOffset = byteOffset
            self.byteSize = byteSize
        }

        internal init(copying native: IdaxMicrocodeLocationPart, _ operation: String) throws(IDAError) {
            self.kind = try checkedNativeEnum(Decompiler.MicrocodeValueLocationKind.self, native.kind, operation)
            self.registerId = native.register_id
            self.secondRegisterId = native.second_register_id
            self.registerOffset = native.register_offset
            self.registerRelativeOffset = native.register_relative_offset
            self.stackOffset = native.stack_offset
            self.staticAddress = native.static_address
            self.byteOffset = native.byte_offset
            self.byteSize = native.byte_size
        }
    }

    public struct MicrocodeValueLocation: Equatable, Sendable {
        public var kind: Decompiler.MicrocodeValueLocationKind
        public var registerId: Int32
        public var secondRegisterId: Int32
        public var registerOffset: Int32
        public var registerRelativeOffset: Int64
        public var stackOffset: Int64
        public var staticAddress: UInt64
        public var scatteredParts: [Decompiler.MicrocodeLocationPart]

        public init(kind: Decompiler.MicrocodeValueLocationKind = .unspecified, registerId: Int32 = 0, secondRegisterId: Int32 = 0, registerOffset: Int32 = 0, registerRelativeOffset: Int64 = 0, stackOffset: Int64 = 0, staticAddress: UInt64 = badAddress, scatteredParts: [Decompiler.MicrocodeLocationPart] = []) {
            self.kind = kind
            self.registerId = registerId
            self.secondRegisterId = secondRegisterId
            self.registerOffset = registerOffset
            self.registerRelativeOffset = registerRelativeOffset
            self.stackOffset = stackOffset
            self.staticAddress = staticAddress
            self.scatteredParts = scatteredParts
        }

        internal init(copying native: IdaxMicrocodeValueLocation, _ operation: String) throws(IDAError) {
            self.kind = try checkedNativeEnum(Decompiler.MicrocodeValueLocationKind.self, native.kind, operation)
            self.registerId = native.register_id
            self.secondRegisterId = native.second_register_id
            self.registerOffset = native.register_offset
            self.registerRelativeOffset = native.register_relative_offset
            self.stackOffset = native.stack_offset
            self.staticAddress = native.static_address
            self.scatteredParts = try copyNativeValues(native.scattered_parts, count: Int(native.scattered_part_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeLocationPart in try Decompiler.MicrocodeLocationPart(copying: value, operation) }
        }
    }

    public struct LocalVariable: Equatable, Sendable {
        public var name: String
        public var typeName: String
        public var isArgument: Bool
        public var width: Int32
        public var hasUserName: Bool
        public var storage: Decompiler.VariableStorage
        public var comment: String
        public var index: Int
        public var stackOffset: Int64
        public var location: Decompiler.MicrocodeValueLocation?
        public var processorRegisterName: String?
        public var hasNiceName: Bool

        public init(name: String = "", typeName: String = "", isArgument: Bool = false, width: Int32 = 0, hasUserName: Bool = false, storage: Decompiler.VariableStorage = .unknown, comment: String = "", index: Int = 0, stackOffset: Int64 = -1, location: Decompiler.MicrocodeValueLocation? = nil, processorRegisterName: String? = nil, hasNiceName: Bool = false) {
            self.name = name
            self.typeName = typeName
            self.isArgument = isArgument
            self.width = width
            self.hasUserName = hasUserName
            self.storage = storage
            self.comment = comment
            self.index = index
            self.stackOffset = stackOffset
            self.location = location
            self.processorRegisterName = processorRegisterName
            self.hasNiceName = hasNiceName
        }

        internal init(copying native: IdaxLocalVariable, _ operation: String) throws(IDAError) {
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.typeName = try borrowCString(native.type_name.map { UnsafePointer($0) }, operation)
            self.isArgument = native.is_argument != 0
            self.width = native.width
            self.hasUserName = native.has_user_name != 0
            self.storage = try checkedNativeEnum(Decompiler.VariableStorage.self, native.storage, operation)
            self.comment = try borrowCString(native.comment.map { UnsafePointer($0) }, operation)
            self.index = native.index
            self.stackOffset = native.stack_offset
            self.location = try copyNativeOptional(native.location, operation) { (value) throws(IDAError) -> Decompiler.MicrocodeValueLocation in try Decompiler.MicrocodeValueLocation(copying: value, operation) }
            self.processorRegisterName = native.processor_register_name == nil ? nil : (try borrowCString(native.processor_register_name.map { UnsafePointer($0) }, operation))
            self.hasNiceName = native.has_nice_name != 0
        }
    }

    public struct MicrocodeRegisterRange: Equatable, Sendable {
        public var registerId: Int32
        public var byteWidth: Int32

        public init(registerId: Int32 = 0, byteWidth: Int32 = 0) {
            self.registerId = registerId
            self.byteWidth = byteWidth
        }

        internal init(copying native: IdaxMicrocodeRegisterRange, _ operation: String) throws(IDAError) {
            self.registerId = native.register_id
            self.byteWidth = native.byte_width
        }
    }

    public struct MicrocodeSwitchCase: Equatable, Sendable {
        public var value: Int64
        public var targetBlock: Int32

        public init(value: Int64 = 0, targetBlock: Int32 = 0) {
            self.value = value
            self.targetBlock = targetBlock
        }

        internal init(copying native: IdaxMicrocodeSwitchCase, _ operation: String) throws(IDAError) {
            self.value = native.value
            self.targetBlock = native.target_block
        }
    }

    public struct MicrocodeCallArgumentProperties: Equatable, Sendable {
        public var hidden: Bool
        public var returnValuePointer: Bool
        public var structureArgument: Bool
        public var arrayArgument: Bool
        public var unused: Bool
        public var swiftSelf: Bool

        public init(hidden: Bool = false, returnValuePointer: Bool = false, structureArgument: Bool = false, arrayArgument: Bool = false, unused: Bool = false, swiftSelf: Bool = false) {
            self.hidden = hidden
            self.returnValuePointer = returnValuePointer
            self.structureArgument = structureArgument
            self.arrayArgument = arrayArgument
            self.unused = unused
            self.swiftSelf = swiftSelf
        }

        internal init(copying native: IdaxMicrocodeCallArgumentProperties, _ operation: String) throws(IDAError) {
            self.hidden = native.hidden != 0
            self.returnValuePointer = native.return_value_pointer != 0
            self.structureArgument = native.structure_argument != 0
            self.arrayArgument = native.array_argument != 0
            self.unused = native.unused != 0
            self.swiftSelf = native.swift_self != 0
        }
    }

    public struct MicrocodeOperand: Equatable, Sendable {
        private struct Fields: Equatable, Sendable {
        var kind: Decompiler.MicrocodeOperandKind
        var registerId: Int32
        var localVariableIndex: Int32
        var localVariableOffset: Int64
        var secondRegisterId: Int32
        var globalAddress: UInt64
        var stackOffset: Int64
        var helperName: String
        var blockIndex: Int32
        var processorRegisterId: Int32
        var nestedInstruction: Decompiler.MicrocodeInstruction?
        var unsignedImmediate: UInt64
        var signedImmediate: Int64
        var byteWidth: Int32
        var markUserDefinedType: Bool
        var referencedOperand: Decompiler.MicrocodeOperand?
        var callArguments: [Decompiler.MicrocodeOperand]
        var callTarget: UInt64
        var text: String
        var stringConstant: String
        var floatingPointConstant: Double?
        var globalName: String
        var valueNumber: UInt16?
        var callArgumentProperties: [Decompiler.MicrocodeCallArgumentProperties]
        var callReturnOperands: [Decompiler.MicrocodeOperand]
        var callReturnRegisters: [Decompiler.MicrocodeRegisterRange]
        var switchCases: [Decompiler.MicrocodeSwitchCase]
        var switchDefaultTarget: Int32?
        }
        private indirect enum Storage: Equatable, Sendable { case value(Fields) }
        private var storage: Storage
        private var fields: Fields { switch storage { case .value(let value): return value } }
        public var kind: Decompiler.MicrocodeOperandKind {
            get { fields.kind }
            set { var value = fields; value.kind = newValue; storage = .value(value) }
        }
        public var registerId: Int32 {
            get { fields.registerId }
            set { var value = fields; value.registerId = newValue; storage = .value(value) }
        }
        public var localVariableIndex: Int32 {
            get { fields.localVariableIndex }
            set { var value = fields; value.localVariableIndex = newValue; storage = .value(value) }
        }
        public var localVariableOffset: Int64 {
            get { fields.localVariableOffset }
            set { var value = fields; value.localVariableOffset = newValue; storage = .value(value) }
        }
        public var secondRegisterId: Int32 {
            get { fields.secondRegisterId }
            set { var value = fields; value.secondRegisterId = newValue; storage = .value(value) }
        }
        public var globalAddress: UInt64 {
            get { fields.globalAddress }
            set { var value = fields; value.globalAddress = newValue; storage = .value(value) }
        }
        public var stackOffset: Int64 {
            get { fields.stackOffset }
            set { var value = fields; value.stackOffset = newValue; storage = .value(value) }
        }
        public var helperName: String {
            get { fields.helperName }
            set { var value = fields; value.helperName = newValue; storage = .value(value) }
        }
        public var blockIndex: Int32 {
            get { fields.blockIndex }
            set { var value = fields; value.blockIndex = newValue; storage = .value(value) }
        }
        public var processorRegisterId: Int32 {
            get { fields.processorRegisterId }
            set { var value = fields; value.processorRegisterId = newValue; storage = .value(value) }
        }
        public var nestedInstruction: Decompiler.MicrocodeInstruction? {
            get { fields.nestedInstruction }
            set { var value = fields; value.nestedInstruction = newValue; storage = .value(value) }
        }
        public var unsignedImmediate: UInt64 {
            get { fields.unsignedImmediate }
            set { var value = fields; value.unsignedImmediate = newValue; storage = .value(value) }
        }
        public var signedImmediate: Int64 {
            get { fields.signedImmediate }
            set { var value = fields; value.signedImmediate = newValue; storage = .value(value) }
        }
        public var byteWidth: Int32 {
            get { fields.byteWidth }
            set { var value = fields; value.byteWidth = newValue; storage = .value(value) }
        }
        public var markUserDefinedType: Bool {
            get { fields.markUserDefinedType }
            set { var value = fields; value.markUserDefinedType = newValue; storage = .value(value) }
        }
        public var referencedOperand: Decompiler.MicrocodeOperand? {
            get { fields.referencedOperand }
            set { var value = fields; value.referencedOperand = newValue; storage = .value(value) }
        }
        public var callArguments: [Decompiler.MicrocodeOperand] {
            get { fields.callArguments }
            set { var value = fields; value.callArguments = newValue; storage = .value(value) }
        }
        public var callTarget: UInt64 {
            get { fields.callTarget }
            set { var value = fields; value.callTarget = newValue; storage = .value(value) }
        }
        public var text: String {
            get { fields.text }
            set { var value = fields; value.text = newValue; storage = .value(value) }
        }
        public var stringConstant: String {
            get { fields.stringConstant }
            set { var value = fields; value.stringConstant = newValue; storage = .value(value) }
        }
        public var floatingPointConstant: Double? {
            get { fields.floatingPointConstant }
            set { var value = fields; value.floatingPointConstant = newValue; storage = .value(value) }
        }
        public var globalName: String {
            get { fields.globalName }
            set { var value = fields; value.globalName = newValue; storage = .value(value) }
        }
        public var valueNumber: UInt16? {
            get { fields.valueNumber }
            set { var value = fields; value.valueNumber = newValue; storage = .value(value) }
        }
        public var callArgumentProperties: [Decompiler.MicrocodeCallArgumentProperties] {
            get { fields.callArgumentProperties }
            set { var value = fields; value.callArgumentProperties = newValue; storage = .value(value) }
        }
        public var callReturnOperands: [Decompiler.MicrocodeOperand] {
            get { fields.callReturnOperands }
            set { var value = fields; value.callReturnOperands = newValue; storage = .value(value) }
        }
        public var callReturnRegisters: [Decompiler.MicrocodeRegisterRange] {
            get { fields.callReturnRegisters }
            set { var value = fields; value.callReturnRegisters = newValue; storage = .value(value) }
        }
        public var switchCases: [Decompiler.MicrocodeSwitchCase] {
            get { fields.switchCases }
            set { var value = fields; value.switchCases = newValue; storage = .value(value) }
        }
        public var switchDefaultTarget: Int32? {
            get { fields.switchDefaultTarget }
            set { var value = fields; value.switchDefaultTarget = newValue; storage = .value(value) }
        }
        public init(kind: Decompiler.MicrocodeOperandKind = .empty, registerId: Int32 = 0, localVariableIndex: Int32 = 0, localVariableOffset: Int64 = 0, secondRegisterId: Int32 = 0, globalAddress: UInt64 = badAddress, stackOffset: Int64 = 0, helperName: String = "", blockIndex: Int32 = 0, processorRegisterId: Int32 = -1, nestedInstruction: Decompiler.MicrocodeInstruction? = nil, unsignedImmediate: UInt64 = 0, signedImmediate: Int64 = 0, byteWidth: Int32 = 0, markUserDefinedType: Bool = false, referencedOperand: Decompiler.MicrocodeOperand? = nil, callArguments: [Decompiler.MicrocodeOperand] = [], callTarget: UInt64 = badAddress, text: String = "", stringConstant: String = "", floatingPointConstant: Double? = nil, globalName: String = "", valueNumber: UInt16? = nil, callArgumentProperties: [Decompiler.MicrocodeCallArgumentProperties] = [], callReturnOperands: [Decompiler.MicrocodeOperand] = [], callReturnRegisters: [Decompiler.MicrocodeRegisterRange] = [], switchCases: [Decompiler.MicrocodeSwitchCase] = [], switchDefaultTarget: Int32? = nil) { storage = .value(Fields(kind: kind, registerId: registerId, localVariableIndex: localVariableIndex, localVariableOffset: localVariableOffset, secondRegisterId: secondRegisterId, globalAddress: globalAddress, stackOffset: stackOffset, helperName: helperName, blockIndex: blockIndex, processorRegisterId: processorRegisterId, nestedInstruction: nestedInstruction, unsignedImmediate: unsignedImmediate, signedImmediate: signedImmediate, byteWidth: byteWidth, markUserDefinedType: markUserDefinedType, referencedOperand: referencedOperand, callArguments: callArguments, callTarget: callTarget, text: text, stringConstant: stringConstant, floatingPointConstant: floatingPointConstant, globalName: globalName, valueNumber: valueNumber, callArgumentProperties: callArgumentProperties, callReturnOperands: callReturnOperands, callReturnRegisters: callReturnRegisters, switchCases: switchCases, switchDefaultTarget: switchDefaultTarget)) }
        internal init(copying native: IdaxMicrocodeOperand, _ operation: String) throws(IDAError) {
            storage = .value(Fields(
                kind: try checkedNativeEnum(Decompiler.MicrocodeOperandKind.self, native.kind, operation),
                registerId: native.register_id,
                localVariableIndex: native.local_variable_index,
                localVariableOffset: native.local_variable_offset,
                secondRegisterId: native.second_register_id,
                globalAddress: native.global_address,
                stackOffset: native.stack_offset,
                helperName: try borrowCString(native.helper_name.map { UnsafePointer($0) }, operation),
                blockIndex: native.block_index,
                processorRegisterId: native.processor_register_id,
                nestedInstruction: try copyNativeOptional(native.nested_instruction, operation) { (value) throws(IDAError) -> Decompiler.MicrocodeInstruction in try Decompiler.MicrocodeInstruction(copying: value, operation) },
                unsignedImmediate: native.unsigned_immediate,
                signedImmediate: native.signed_immediate,
                byteWidth: native.byte_width,
                markUserDefinedType: native.mark_user_defined_type != 0,
                referencedOperand: try copyNativeOptional(native.referenced_operand, operation) { (value) throws(IDAError) -> Decompiler.MicrocodeOperand in try Decompiler.MicrocodeOperand(copying: value, operation) },
                callArguments: try copyNativeValues(native.call_arguments, count: Int(native.call_argument_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeOperand in try Decompiler.MicrocodeOperand(copying: value, operation) },
                callTarget: native.call_target,
                text: try borrowCString(native.text.map { UnsafePointer($0) }, operation),
                stringConstant: try borrowCString(native.string_constant.map { UnsafePointer($0) }, operation),
                floatingPointConstant: native.has_floating_point_constant != 0 ? (native.floating_point_constant) : nil,
                globalName: try borrowCString(native.global_name.map { UnsafePointer($0) }, operation),
                valueNumber: native.has_value_number != 0 ? (native.value_number) : nil,
                callArgumentProperties: try copyNativeValues(native.call_argument_properties, count: Int(native.call_argument_property_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeCallArgumentProperties in try Decompiler.MicrocodeCallArgumentProperties(copying: value, operation) },
                callReturnOperands: try copyNativeValues(native.call_return_operands, count: Int(native.call_return_operand_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeOperand in try Decompiler.MicrocodeOperand(copying: value, operation) },
                callReturnRegisters: try copyNativeValues(native.call_return_registers, count: Int(native.call_return_register_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeRegisterRange in try Decompiler.MicrocodeRegisterRange(copying: value, operation) },
                switchCases: try copyNativeValues(native.switch_cases, count: Int(native.switch_case_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeSwitchCase in try Decompiler.MicrocodeSwitchCase(copying: value, operation) },
                switchDefaultTarget: native.has_switch_default_target != 0 ? (native.switch_default_target) : nil))
        }
    }

    public struct MicrocodeInstruction: Equatable, Sendable {
        public var opcode: Decompiler.MicrocodeOpcode
        public var left: Decompiler.MicrocodeOperand
        public var right: Decompiler.MicrocodeOperand
        public var destination: Decompiler.MicrocodeOperand
        public var floatingPointInstruction: Bool
        public var modifiesDestination: Bool
        public var address: UInt64
        public var text: String

        public init(opcode: Decompiler.MicrocodeOpcode = .noOperation, left: Decompiler.MicrocodeOperand = .init(), right: Decompiler.MicrocodeOperand = .init(), destination: Decompiler.MicrocodeOperand = .init(), floatingPointInstruction: Bool = false, modifiesDestination: Bool = false, address: UInt64 = badAddress, text: String = "") {
            self.opcode = opcode
            self.left = left
            self.right = right
            self.destination = destination
            self.floatingPointInstruction = floatingPointInstruction
            self.modifiesDestination = modifiesDestination
            self.address = address
            self.text = text
        }

        internal init(copying native: IdaxMicrocodeInstruction, _ operation: String) throws(IDAError) {
            self.opcode = try checkedNativeEnum(Decompiler.MicrocodeOpcode.self, native.opcode, operation)
            self.left = try Decompiler.MicrocodeOperand(copying: native.left, operation)
            self.right = try Decompiler.MicrocodeOperand(copying: native.right, operation)
            self.destination = try Decompiler.MicrocodeOperand(copying: native.destination, operation)
            self.floatingPointInstruction = native.floating_point_instruction != 0
            self.modifiesDestination = native.modifies_destination != 0
            self.address = native.address
            self.text = try borrowCString(native.text.map { UnsafePointer($0) }, operation)
        }
    }

    public struct MicrocodeFunctionArgument: Equatable, Sendable {
        public var name: String
        public var location: Decompiler.MicrocodeValueLocation
        public var byteWidth: Int32

        public init(name: String = "", location: Decompiler.MicrocodeValueLocation = .init(), byteWidth: Int32 = 0) {
            self.name = name
            self.location = location
            self.byteWidth = byteWidth
        }

        internal init(copying native: IdaxMicrocodeFunctionArgument, _ operation: String) throws(IDAError) {
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.location = try Decompiler.MicrocodeValueLocation(copying: native.location, operation)
            self.byteWidth = native.byte_width
        }
    }

    public struct MicrocodeBlock: Equatable, Sendable {
        public var index: Int32
        public var startAddress: UInt64
        public var endAddress: UInt64
        public var predecessors: [Int32]
        public var successors: [Int32]
        public var instructions: [Decompiler.MicrocodeInstruction]
        public var kind: Decompiler.MicrocodeBlockKind

        public init(index: Int32 = 0, startAddress: UInt64 = badAddress, endAddress: UInt64 = badAddress, predecessors: [Int32] = [], successors: [Int32] = [], instructions: [Decompiler.MicrocodeInstruction] = [], kind: Decompiler.MicrocodeBlockKind = .unknown) {
            self.index = index
            self.startAddress = startAddress
            self.endAddress = endAddress
            self.predecessors = predecessors
            self.successors = successors
            self.instructions = instructions
            self.kind = kind
        }

        internal init(copying native: IdaxMicrocodeBlock, _ operation: String) throws(IDAError) {
            self.index = native.index
            self.startAddress = native.start_address
            self.endAddress = native.end_address
            self.predecessors = try copyNativeValues(native.predecessors, count: Int(native.predecessor_count), operation) { (value) throws(IDAError) -> Int32 in value }
            self.successors = try copyNativeValues(native.successors, count: Int(native.successor_count), operation) { (value) throws(IDAError) -> Int32 in value }
            self.instructions = try copyNativeValues(native.instructions, count: Int(native.instruction_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeInstruction in try Decompiler.MicrocodeInstruction(copying: value, operation) }
            self.kind = try checkedNativeEnum(Decompiler.MicrocodeBlockKind.self, native.kind, operation)
        }
    }

    public struct MicrocodeFunction: Equatable, Sendable {
        public var entryAddress: UInt64
        public var maturity: Decompiler.MicrocodeMaturity
        public var arguments: [Decompiler.MicrocodeFunctionArgument]
        public var returnLocation: Decompiler.MicrocodeValueLocation?
        public var blocks: [Decompiler.MicrocodeBlock]
        public var stackFrameSize: Int64
        public var localStackSize: Int64
        public var savedRegisterSize: Int64
        public var returnVariableIndex: Int?
        public var localVariables: [Decompiler.LocalVariable]

        public init(entryAddress: UInt64 = badAddress, maturity: Decompiler.MicrocodeMaturity = .generated, arguments: [Decompiler.MicrocodeFunctionArgument] = [], returnLocation: Decompiler.MicrocodeValueLocation? = nil, blocks: [Decompiler.MicrocodeBlock] = [], stackFrameSize: Int64 = 0, localStackSize: Int64 = 0, savedRegisterSize: Int64 = 0, returnVariableIndex: Int? = nil, localVariables: [Decompiler.LocalVariable] = []) {
            self.entryAddress = entryAddress
            self.maturity = maturity
            self.arguments = arguments
            self.returnLocation = returnLocation
            self.blocks = blocks
            self.stackFrameSize = stackFrameSize
            self.localStackSize = localStackSize
            self.savedRegisterSize = savedRegisterSize
            self.returnVariableIndex = returnVariableIndex
            self.localVariables = localVariables
        }

        internal init(copying native: IdaxMicrocodeFunction, _ operation: String) throws(IDAError) {
            self.entryAddress = native.entry_address
            self.maturity = try checkedNativeEnum(Decompiler.MicrocodeMaturity.self, native.maturity, operation)
            self.arguments = try copyNativeValues(native.arguments, count: Int(native.argument_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeFunctionArgument in try Decompiler.MicrocodeFunctionArgument(copying: value, operation) }
            self.returnLocation = native.has_return_location != 0 ? (try Decompiler.MicrocodeValueLocation(copying: native.return_location, operation)) : nil
            self.blocks = try copyNativeValues(native.blocks, count: Int(native.block_count), operation) { (value) throws(IDAError) -> Decompiler.MicrocodeBlock in try Decompiler.MicrocodeBlock(copying: value, operation) }
            self.stackFrameSize = native.stack_frame_size
            self.localStackSize = native.local_stack_size
            self.savedRegisterSize = native.saved_register_size
            self.returnVariableIndex = native.has_return_variable_index != 0 ? (native.return_variable_index) : nil
            self.localVariables = try copyNativeValues(native.local_variables, count: Int(native.local_variable_count), operation) { (value) throws(IDAError) -> Decompiler.LocalVariable in try Decompiler.LocalVariable(copying: value, operation) }
        }
    }

    public struct PseudocodeComment: Equatable, Sendable {
        public var address: UInt64
        public var position: Decompiler.CommentPosition
        public var text: String

        public init(address: UInt64 = badAddress, position: Decompiler.CommentPosition = .init(), text: String = "") {
            self.address = address
            self.position = position
            self.text = text
        }

        internal init(copying native: IdaxPseudocodeComment, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.position = try Decompiler.CommentPosition(copying: native.position, operation)
            self.text = try borrowCString(native.text.map { UnsafePointer($0) }, operation)
        }
    }

    public struct CtreeItem: Equatable, Sendable {
        public var type: Decompiler.ItemType
        public var address: UInt64
        public var isExpression: Bool

        public init(type: Decompiler.ItemType = .exprEmpty, address: UInt64 = badAddress, isExpression: Bool = false) {
            self.type = type
            self.address = address
            self.isExpression = isExpression
        }

        internal init(copying native: IdaxDecompilerCtreeItemInfo, _ operation: String) throws(IDAError) {
            self.type = try checkedNativeEnum(Decompiler.ItemType.self, native.type, operation)
            self.address = native.address
            self.isExpression = native.is_expression != 0
        }
    }

    public struct ItemAtPosition: Equatable, Sendable {
        public var type: Decompiler.ItemType
        public var address: UInt64
        public var itemIndex: Int32
        public var isExpression: Bool

        public init(type: Decompiler.ItemType = .exprEmpty, address: UInt64 = badAddress, itemIndex: Int32 = -1, isExpression: Bool = false) {
            self.type = type
            self.address = address
            self.itemIndex = itemIndex
            self.isExpression = isExpression
        }

        internal init(copying native: IdaxDecompilerItemAtPosition, _ operation: String) throws(IDAError) {
            self.type = try checkedNativeEnum(Decompiler.ItemType.self, native.type, operation)
            self.address = native.address
            self.itemIndex = native.item_index
            self.isExpression = native.is_expression != 0
        }
    }

    public static func available() throws(IDAError) -> Bool {
        try requireRuntimeThread("Decompiler.available")
        var out: Int32 = 0
        try checkStatus(idax_decompiler_available(&out), "Decompiler.available")
        return out != 0
    }

    public static func markDirty(functionAddress: UInt64, closeViews: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Decompiler.markDirty")
        try checkStatus(idax_decompiler_mark_dirty(functionAddress, (closeViews ? 1 : 0)), "Decompiler.markDirty")
    }

    public static func markDirtyWithCallers(functionAddress: UInt64, closeViews: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Decompiler.markDirtyWithCallers")
        try checkStatus(idax_decompiler_mark_dirty_with_callers(functionAddress, (closeViews ? 1 : 0)), "Decompiler.markDirtyWithCallers")
    }

    public static func itemTypeName(itemType: Decompiler.ItemType) throws(IDAError) -> String {
        try requireRuntimeThread("Decompiler.itemTypeName")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_decompiler_item_type_name(Int32(itemType.rawValue), &out), "Decompiler.itemTypeName")
        return try borrowCString(out.map { UnsafePointer($0) }, "Decompiler.itemTypeName")
    }
}
