// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Diagnostics {
    public enum LogLevel: Int32, CaseIterable, Sendable {
        case error = 0
        case warning = 1
        case info = 2
        case debug = 3
        case trace = 4
    }

    public struct PerformanceCounters: Equatable, Sendable {
        public var logMessages: UInt64
        public var invariantFailures: UInt64

        public init(logMessages: UInt64, invariantFailures: UInt64) {
            self.logMessages = logMessages
            self.invariantFailures = invariantFailures
        }

        internal init(copying native: IdaxPerformanceCounters, _ operation: String) throws(IDAError) {
            self.logMessages = native.log_messages
            self.invariantFailures = native.invariant_failures
        }
    }

    public static func setLogLevel(level: Diagnostics.LogLevel) throws(IDAError) {
        try requireRuntimeThread("Diagnostics.setLogLevel")
        try checkStatus(idax_diagnostics_set_log_level(Int32(level.rawValue)), "Diagnostics.setLogLevel")
    }

    public static func logLevel() throws(IDAError) -> Diagnostics.LogLevel {
        try requireRuntimeThread("Diagnostics.logLevel")
        let result = idax_diagnostics_log_level()
        return try checkedNativeEnum(Diagnostics.LogLevel.self, result, "Diagnostics.logLevel")
    }

    public static func log(level: Diagnostics.LogLevel, domain: String, message: String) throws(IDAError) {
        try requireRuntimeThread("Diagnostics.log")
        try validateCString(domain, "Diagnostics.log")
        try validateCString(message, "Diagnostics.log")
        domain.withCString { c_domain in message.withCString { c_message in idax_diagnostics_log(Int32(level.rawValue), c_domain, c_message)}}
    }

    public static func resetPerformanceCounters() throws(IDAError) {
        try requireRuntimeThread("Diagnostics.resetPerformanceCounters")
        idax_diagnostics_reset_performance_counters()
    }

    public static func performanceCounters() throws(IDAError) -> Diagnostics.PerformanceCounters {
        try requireRuntimeThread("Diagnostics.performanceCounters")
        var out = IdaxPerformanceCounters()
        try checkStatus(idax_diagnostics_performance_counters(&out), "Diagnostics.performanceCounters")
        return try Diagnostics.PerformanceCounters(copying: out, "Diagnostics.performanceCounters")
    }
}
