// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Entries {
    public struct EntryPoint: Equatable, Sendable {
        public var ordinal: UInt64
        public var address: UInt64
        public var name: String
        public var forwarder: String

        public init(ordinal: UInt64, address: UInt64, name: String, forwarder: String) {
            self.ordinal = ordinal
            self.address = address
            self.name = name
            self.forwarder = forwarder
        }

        internal init(copying native: IdaxEntryPoint, _ operation: String) throws(IDAError) {
            self.ordinal = native.ordinal
            self.address = native.address
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.forwarder = try borrowCString(native.forwarder.map { UnsafePointer($0) }, operation)
        }
    }

    public static func count() throws(IDAError) -> Int {
        try requireRuntimeThread("Entries.count")
        var out: Int = 0
        try checkStatus(idax_entry_count(&out), "Entries.count")
        return out
    }

    public static func byIndex(index: Int) throws(IDAError) -> Entries.EntryPoint {
        try requireRuntimeThread("Entries.byIndex")
        try requireNonnegative(index, "Entries.byIndex")
        var out = IdaxEntryPoint()
        defer { idax_entry_free(&out) }
        try checkStatus(idax_entry_by_index(index, &out), "Entries.byIndex")
        return try Entries.EntryPoint(copying: out, "Entries.byIndex")
    }

    public static func byOrdinal(ordinal: UInt64) throws(IDAError) -> Entries.EntryPoint {
        try requireRuntimeThread("Entries.byOrdinal")
        var out = IdaxEntryPoint()
        defer { idax_entry_free(&out) }
        try checkStatus(idax_entry_by_ordinal(ordinal, &out), "Entries.byOrdinal")
        return try Entries.EntryPoint(copying: out, "Entries.byOrdinal")
    }

    public static func add(ordinal: UInt64, address: UInt64, name: String, makeCode: Bool = true) throws(IDAError) {
        try requireRuntimeThread("Entries.add")
        try validateCString(name, "Entries.add")
        try checkStatus(name.withCString { c_name in idax_entry_add(ordinal, address, c_name, (makeCode ? 1 : 0))}, "Entries.add")
    }

    public static func rename(ordinal: UInt64, name: String) throws(IDAError) {
        try requireRuntimeThread("Entries.rename")
        try validateCString(name, "Entries.rename")
        try checkStatus(name.withCString { c_name in idax_entry_rename(ordinal, c_name)}, "Entries.rename")
    }

    public static func forwarder(ordinal: UInt64) throws(IDAError) -> String {
        try requireRuntimeThread("Entries.forwarder")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_entry_forwarder(ordinal, &out), "Entries.forwarder")
        return try borrowCString(out.map { UnsafePointer($0) }, "Entries.forwarder")
    }

    public static func setForwarder(ordinal: UInt64, target: String) throws(IDAError) {
        try requireRuntimeThread("Entries.setForwarder")
        try validateCString(target, "Entries.setForwarder")
        try checkStatus(target.withCString { c_target in idax_entry_set_forwarder(ordinal, c_target)}, "Entries.setForwarder")
    }

    public static func clearForwarder(ordinal: UInt64) throws(IDAError) {
        try requireRuntimeThread("Entries.clearForwarder")
        try checkStatus(idax_entry_clear_forwarder(ordinal), "Entries.clearForwarder")
    }
}
