// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Exceptions {
    public enum CatchSelectorKind: Int32, CaseIterable, Sendable {
        case typed = 0
        case catchAll = 1
        case cleanup = 2
    }

    public enum SehDisposition: Int32, CaseIterable, Sendable {
        case continueExecution = -1
        case continueSearch = 0
        case executeHandler = 1
    }

    public static func systemRegionStart(address: UInt64) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Exceptions.systemRegionStart")
        var out: UInt64 = 0
        var has_value: Int32 = 0
        try checkStatus(idax_exception_system_region_start(address, &out, &has_value), "Exceptions.systemRegionStart")
        guard has_value != 0 else { return nil }
        return out
    }
}
