// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Fixups {
    public enum Kind: Int32, CaseIterable, Sendable {
        case off8 = 0
        case off16 = 1
        case seg16 = 2
        case ptr16 = 3
        case off32 = 4
        case ptr32 = 5
        case hi8 = 6
        case hi16 = 7
        case low8 = 8
        case low16 = 9
        case off64 = 10
        case off8Signed = 11
        case off16Signed = 12
        case off32Signed = 13
        case custom = 14
    }

    public struct Descriptor: Equatable, Sendable {
        public var source: UInt64
        public var type: Fixups.Kind
        public var flags: UInt32
        public var base: UInt64
        public var target: UInt64
        public var selector: UInt16
        public var offset: UInt64
        public var displacement: Int64

        public init(source: UInt64 = 0, type: Fixups.Kind = .off32, flags: UInt32 = 0, base: UInt64 = 0, target: UInt64 = 0, selector: UInt16 = 0, offset: UInt64 = 0, displacement: Int64 = 0) {
            self.source = source
            self.type = type
            self.flags = flags
            self.base = base
            self.target = target
            self.selector = selector
            self.offset = offset
            self.displacement = displacement
        }

        internal init(copying native: IdaxFixup, _ operation: String) throws(IDAError) {
            self.source = native.source
            self.type = try checkedNativeEnum(Fixups.Kind.self, native.type, operation)
            self.flags = native.flags
            self.base = native.base
            self.target = native.target
            self.selector = native.selector
            self.offset = native.offset
            self.displacement = native.displacement
        }
    }

    public static func at(source: UInt64) throws(IDAError) -> Fixups.Descriptor {
        try requireRuntimeThread("Fixups.at")
        var out = IdaxFixup()
        try checkStatus(idax_fixup_at(source, &out), "Fixups.at")
        return try Fixups.Descriptor(copying: out, "Fixups.at")
    }

    public static func remove(source: UInt64) throws(IDAError) {
        try requireRuntimeThread("Fixups.remove")
        try checkStatus(idax_fixup_remove(source), "Fixups.remove")
    }

    public static func exists(source: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Fixups.exists")
        let result = idax_fixup_exists(source)
        return result != 0
    }

    public static func contains(start: UInt64, size: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Fixups.contains")
        let result = idax_fixup_contains(start, size)
        return result != 0
    }

    public static func inRange(start: UInt64, end: UInt64) throws(IDAError) -> [Fixups.Descriptor] {
        try requireRuntimeThread("Fixups.inRange")
        var out: UnsafeMutablePointer<IdaxFixup>?
        var count: Int = 0
        defer { idax_swift_free_array(out) }
        try checkStatus(idax_fixup_in_range(start, end, &out, &count), "Fixups.inRange")
        return try copyNativeValues(out, count: count, "Fixups.inRange") { (value) throws(IDAError) -> Fixups.Descriptor in try Fixups.Descriptor(copying: value, "Fixups.inRange") }
    }

    public static func first() throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Fixups.first")
        var out: UInt64 = 0
        try checkStatus(idax_fixup_first(&out), "Fixups.first")
        return out
    }

    public static func next(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Fixups.next")
        var out: UInt64 = 0
        try checkStatus(idax_fixup_next(address, &out), "Fixups.next")
        return out
    }

    public static func prev(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Fixups.prev")
        var out: UInt64 = 0
        try checkStatus(idax_fixup_prev(address, &out), "Fixups.prev")
        return out
    }
}
