// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Functions {
    public struct Function: Equatable, Sendable {
        public var start: UInt64
        public var end: UInt64
        public var name: String
        public var bitness: Int32
        public var returns: Bool
        public var isLibrary: Bool
        public var isThunk: Bool
        public var isVisible: Bool
        public var frameLocalSize: UInt64
        public var frameRegsSize: UInt64
        public var frameArgsSize: UInt64

        public init(start: UInt64, end: UInt64, name: String, bitness: Int32, returns: Bool, isLibrary: Bool, isThunk: Bool, isVisible: Bool, frameLocalSize: UInt64, frameRegsSize: UInt64, frameArgsSize: UInt64) {
            self.start = start
            self.end = end
            self.name = name
            self.bitness = bitness
            self.returns = returns
            self.isLibrary = isLibrary
            self.isThunk = isThunk
            self.isVisible = isVisible
            self.frameLocalSize = frameLocalSize
            self.frameRegsSize = frameRegsSize
            self.frameArgsSize = frameArgsSize
        }

        internal init(copying native: IdaxFunction, _ operation: String) throws(IDAError) {
            self.start = native.start
            self.end = native.end
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.bitness = native.bitness
            self.returns = native.returns != 0
            self.isLibrary = native.is_library != 0
            self.isThunk = native.is_thunk != 0
            self.isVisible = native.is_visible != 0
            self.frameLocalSize = native.frame_local_size
            self.frameRegsSize = native.frame_regs_size
            self.frameArgsSize = native.frame_args_size
        }
    }

    public struct Chunk: Equatable, Sendable {
        public var start: UInt64
        public var end: UInt64
        public var isTail: Bool
        public var owner: UInt64

        public init(start: UInt64, end: UInt64, isTail: Bool, owner: UInt64) {
            self.start = start
            self.end = end
            self.isTail = isTail
            self.owner = owner
        }

        internal init(copying native: IdaxChunk, _ operation: String) throws(IDAError) {
            self.start = native.start
            self.end = native.end
            self.isTail = native.is_tail != 0
            self.owner = native.owner
        }
    }

    public struct FrameVariable: Equatable, Sendable {
        public var name: String
        public var byteOffset: Int
        public var byteSize: Int
        public var comment: String
        public var isSpecial: Bool

        public init(name: String, byteOffset: Int, byteSize: Int, comment: String, isSpecial: Bool) {
            self.name = name
            self.byteOffset = byteOffset
            self.byteSize = byteSize
            self.comment = comment
            self.isSpecial = isSpecial
        }

        internal init(copying native: IdaxFrameVariable, _ operation: String) throws(IDAError) {
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.byteOffset = native.byte_offset
            self.byteSize = native.byte_size
            self.comment = try borrowCString(native.comment.map { UnsafePointer($0) }, operation)
            self.isSpecial = native.is_special != 0
        }
    }

    public struct RegisterVariable: Equatable, Sendable {
        public var rangeStart: UInt64
        public var rangeEnd: UInt64
        public var canonicalName: String
        public var userName: String
        public var comment: String

        public init(rangeStart: UInt64, rangeEnd: UInt64, canonicalName: String, userName: String, comment: String) {
            self.rangeStart = rangeStart
            self.rangeEnd = rangeEnd
            self.canonicalName = canonicalName
            self.userName = userName
            self.comment = comment
        }

        internal init(copying native: IdaxRegisterVariable, _ operation: String) throws(IDAError) {
            self.rangeStart = native.range_start
            self.rangeEnd = native.range_end
            self.canonicalName = try borrowCString(native.canonical_name.map { UnsafePointer($0) }, operation)
            self.userName = try borrowCString(native.user_name.map { UnsafePointer($0) }, operation)
            self.comment = try borrowCString(native.comment.map { UnsafePointer($0) }, operation)
        }
    }

    public struct StackFrame: Equatable, Sendable {
        public var localVariablesSize: UInt64
        public var savedRegistersSize: UInt64
        public var argumentsSize: UInt64
        public var totalSize: UInt64
        public var variables: [Functions.FrameVariable]

        public init(localVariablesSize: UInt64, savedRegistersSize: UInt64, argumentsSize: UInt64, totalSize: UInt64, variables: [Functions.FrameVariable]) {
            self.localVariablesSize = localVariablesSize
            self.savedRegistersSize = savedRegistersSize
            self.argumentsSize = argumentsSize
            self.totalSize = totalSize
            self.variables = variables
        }

        internal init(copying native: IdaxStackFrame, _ operation: String) throws(IDAError) {
            self.localVariablesSize = native.local_variables_size
            self.savedRegistersSize = native.saved_registers_size
            self.argumentsSize = native.arguments_size
            self.totalSize = native.total_size
            self.variables = try copyNativeValues(native.variables, count: Int(native.variable_count), operation) { (value) throws(IDAError) -> Functions.FrameVariable in try Functions.FrameVariable(copying: value, operation) }
        }
    }

    public static func at(address: UInt64) throws(IDAError) -> Functions.Function {
        try requireRuntimeThread("Functions.at")
        var out = IdaxFunction()
        defer { idax_function_free(&out) }
        try checkStatus(idax_function_at(address, &out), "Functions.at")
        return try Functions.Function(copying: out, "Functions.at")
    }

    public static func byIndex(index: Int) throws(IDAError) -> Functions.Function {
        try requireRuntimeThread("Functions.byIndex")
        try requireNonnegative(index, "Functions.byIndex")
        var out = IdaxFunction()
        defer { idax_function_free(&out) }
        try checkStatus(idax_function_by_index(index, &out), "Functions.byIndex")
        return try Functions.Function(copying: out, "Functions.byIndex")
    }

    public static func count() throws(IDAError) -> Int {
        try requireRuntimeThread("Functions.count")
        var out: Int = 0
        try checkStatus(idax_function_count(&out), "Functions.count")
        return out
    }

    public static func create(start: UInt64, end: UInt64 = badAddress) throws(IDAError) -> Functions.Function {
        try requireRuntimeThread("Functions.create")
        var out = IdaxFunction()
        defer { idax_function_free(&out) }
        try checkStatus(idax_function_create(start, end, &out), "Functions.create")
        return try Functions.Function(copying: out, "Functions.create")
    }

    public static func remove(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.remove")
        try checkStatus(idax_function_remove(address), "Functions.remove")
    }

    public static func nameAt(address: UInt64) throws(IDAError) -> String {
        try requireRuntimeThread("Functions.nameAt")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_function_name_at(address, &out), "Functions.nameAt")
        return try borrowCString(out.map { UnsafePointer($0) }, "Functions.nameAt")
    }

    public static func setStart(address: UInt64, newStart: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.setStart")
        try checkStatus(idax_function_set_start(address, newStart), "Functions.setStart")
    }

    public static func setEnd(address: UInt64, newEnd: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.setEnd")
        try checkStatus(idax_function_set_end(address, newEnd), "Functions.setEnd")
    }

    public static func update(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.update")
        try checkStatus(idax_function_update(address), "Functions.update")
    }

    public static func reanalyze(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.reanalyze")
        try checkStatus(idax_function_reanalyze(address), "Functions.reanalyze")
    }

    public static func comment(address: UInt64, repeatable: Bool = false) throws(IDAError) -> String {
        try requireRuntimeThread("Functions.comment")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_function_comment(address, (repeatable ? 1 : 0), &out), "Functions.comment")
        return try borrowCString(out.map { UnsafePointer($0) }, "Functions.comment")
    }

    public static func setComment(address: UInt64, text: String, repeatable: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Functions.setComment")
        try validateCString(text, "Functions.setComment")
        try checkStatus(text.withCString { c_text in idax_function_set_comment(address, c_text, (repeatable ? 1 : 0))}, "Functions.setComment")
    }

    public static func callers(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Functions.callers")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_function_callers(address, &out, &count), "Functions.callers")
        return try copyNativeValues(out, count: count, "Functions.callers") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func callees(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Functions.callees")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_function_callees(address, &out, &count), "Functions.callees")
        return try copyNativeValues(out, count: count, "Functions.callees") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func isOutlined(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Functions.isOutlined")
        var out: Int32 = 0
        try checkStatus(idax_function_is_outlined(address, &out), "Functions.isOutlined")
        return out != 0
    }

    public static func setOutlined(address: UInt64, outlined: Bool) throws(IDAError) {
        try requireRuntimeThread("Functions.setOutlined")
        try checkStatus(idax_function_set_outlined(address, (outlined ? 1 : 0)), "Functions.setOutlined")
    }

    public static func chunks(address: UInt64) throws(IDAError) -> [Functions.Chunk] {
        try requireRuntimeThread("Functions.chunks")
        var out: UnsafeMutablePointer<IdaxChunk>?
        var count: Int = 0
        defer { idax_swift_free_array(out) }
        try checkStatus(idax_function_chunks(address, &out, &count), "Functions.chunks")
        return try copyNativeValues(out, count: count, "Functions.chunks") { (value) throws(IDAError) -> Functions.Chunk in try Functions.Chunk(copying: value, "Functions.chunks") }
    }

    public static func chunkCount(address: UInt64) throws(IDAError) -> Int {
        try requireRuntimeThread("Functions.chunkCount")
        var out: Int = 0
        try checkStatus(idax_function_chunk_count(address, &out), "Functions.chunkCount")
        return out
    }

    public static func addTail(functionAddress: UInt64, tailStart: UInt64, tailEnd: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.addTail")
        try checkStatus(idax_function_add_tail(functionAddress, tailStart, tailEnd), "Functions.addTail")
    }

    public static func removeTail(functionAddress: UInt64, tailEa: UInt64) throws(IDAError) {
        try requireRuntimeThread("Functions.removeTail")
        try checkStatus(idax_function_remove_tail(functionAddress, tailEa), "Functions.removeTail")
    }

    public static func frame(address: UInt64) throws(IDAError) -> Functions.StackFrame {
        try requireRuntimeThread("Functions.frame")
        var out = IdaxStackFrame()
        defer { idax_stack_frame_free(&out) }
        try checkStatus(idax_function_frame(address, &out), "Functions.frame")
        return try Functions.StackFrame(copying: out, "Functions.frame")
    }

    public static func spDeltaAt(address: UInt64) throws(IDAError) -> Int64 {
        try requireRuntimeThread("Functions.spDeltaAt")
        var out: Int64 = 0
        try checkStatus(idax_function_sp_delta_at(address, &out), "Functions.spDeltaAt")
        return out
    }

    public static func frameVariableByName(address: UInt64, name: String) throws(IDAError) -> Functions.FrameVariable {
        try requireRuntimeThread("Functions.frameVariableByName")
        try validateCString(name, "Functions.frameVariableByName")
        var out = IdaxFrameVariable()
        defer { idax_frame_variable_free(&out) }
        try checkStatus(name.withCString { c_name in idax_function_frame_variable_by_name(address, c_name, &out)}, "Functions.frameVariableByName")
        return try Functions.FrameVariable(copying: out, "Functions.frameVariableByName")
    }

    public static func frameVariableByOffset(address: UInt64, byteOffset: Int) throws(IDAError) -> Functions.FrameVariable {
        try requireRuntimeThread("Functions.frameVariableByOffset")
        try requireNonnegative(byteOffset, "Functions.frameVariableByOffset")
        var out = IdaxFrameVariable()
        defer { idax_frame_variable_free(&out) }
        try checkStatus(idax_function_frame_variable_by_offset(address, byteOffset, &out), "Functions.frameVariableByOffset")
        return try Functions.FrameVariable(copying: out, "Functions.frameVariableByOffset")
    }

    public static func defineStackVariable(functionAddress: UInt64, name: String, frameOffset: Int32, type: TypeInfo) throws(IDAError) {
        return try TypeInfo.withHandles([type], "Functions.defineStackVariable") { (handles) throws(IDAError) -> Void in
            try requireRuntimeThread("Functions.defineStackVariable")
            try validateCString(name, "Functions.defineStackVariable")
            let c_type = handles[0]
            try checkStatus(name.withCString { c_name in idax_function_define_stack_variable(functionAddress, c_name, frameOffset, c_type)}, "Functions.defineStackVariable")
        }
    }

    public static func setPrototype(functionAddress: UInt64, type: TypeInfo) throws(IDAError) {
        return try TypeInfo.withHandles([type], "Functions.setPrototype") { (handles) throws(IDAError) -> Void in
            try requireRuntimeThread("Functions.setPrototype")
            let c_type = handles[0]
            try checkStatus(idax_function_set_prototype(functionAddress, c_type), "Functions.setPrototype")
        }
    }

    public static func applyDecl(functionAddress: UInt64, cDecl: String) throws(IDAError) {
        try requireRuntimeThread("Functions.applyDecl")
        try validateCString(cDecl, "Functions.applyDecl")
        try checkStatus(cDecl.withCString { c_c_decl in idax_function_apply_decl(functionAddress, c_c_decl)}, "Functions.applyDecl")
    }

    public static func declaration(functionAddress: UInt64, nameOverride: String = "") throws(IDAError) -> String {
        try requireRuntimeThread("Functions.declaration")
        try validateCString(nameOverride, "Functions.declaration")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(nameOverride.withCString { c_name_override in idax_function_declaration(functionAddress, c_name_override, &out)}, "Functions.declaration")
        return try borrowCString(out.map { UnsafePointer($0) }, "Functions.declaration")
    }

    public static func addRegisterVariable(functionAddress: UInt64, rangeStart: UInt64, rangeEnd: UInt64, registerName: String, userName: String, comment: String = "") throws(IDAError) {
        try requireRuntimeThread("Functions.addRegisterVariable")
        try validateCString(registerName, "Functions.addRegisterVariable")
        try validateCString(userName, "Functions.addRegisterVariable")
        try validateCString(comment, "Functions.addRegisterVariable")
        try checkStatus(registerName.withCString { c_register_name in userName.withCString { c_user_name in comment.withCString { c_comment in idax_function_add_register_variable(functionAddress, rangeStart, rangeEnd, c_register_name, c_user_name, c_comment)}}}, "Functions.addRegisterVariable")
    }

    public static func findRegisterVariable(functionAddress: UInt64, address: UInt64, registerName: String) throws(IDAError) -> Functions.RegisterVariable {
        try requireRuntimeThread("Functions.findRegisterVariable")
        try validateCString(registerName, "Functions.findRegisterVariable")
        var out = IdaxRegisterVariable()
        defer { idax_register_variable_free(&out) }
        try checkStatus(registerName.withCString { c_register_name in idax_function_find_register_variable(functionAddress, address, c_register_name, &out)}, "Functions.findRegisterVariable")
        return try Functions.RegisterVariable(copying: out, "Functions.findRegisterVariable")
    }

    public static func removeRegisterVariable(functionAddress: UInt64, rangeStart: UInt64, rangeEnd: UInt64, registerName: String) throws(IDAError) {
        try requireRuntimeThread("Functions.removeRegisterVariable")
        try validateCString(registerName, "Functions.removeRegisterVariable")
        try checkStatus(registerName.withCString { c_register_name in idax_function_remove_register_variable(functionAddress, rangeStart, rangeEnd, c_register_name)}, "Functions.removeRegisterVariable")
    }

    public static func renameRegisterVariable(functionAddress: UInt64, address: UInt64, registerName: String, newUserName: String) throws(IDAError) {
        try requireRuntimeThread("Functions.renameRegisterVariable")
        try validateCString(registerName, "Functions.renameRegisterVariable")
        try validateCString(newUserName, "Functions.renameRegisterVariable")
        try checkStatus(registerName.withCString { c_register_name in newUserName.withCString { c_new_user_name in idax_function_rename_register_variable(functionAddress, address, c_register_name, c_new_user_name)}}, "Functions.renameRegisterVariable")
    }

    public static func hasRegisterVariables(functionAddress: UInt64, address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Functions.hasRegisterVariables")
        var out: Int32 = 0
        try checkStatus(idax_function_has_register_variables(functionAddress, address, &out), "Functions.hasRegisterVariables")
        return out != 0
    }

    public static func registerVariables(functionAddress: UInt64) throws(IDAError) -> [Functions.RegisterVariable] {
        try requireRuntimeThread("Functions.registerVariables")
        var out: UnsafeMutablePointer<IdaxRegisterVariable>?
        var count: Int = 0
        defer { idax_register_variables_free(out, count) }
        try checkStatus(idax_function_register_variables(functionAddress, &out, &count), "Functions.registerVariables")
        return try copyNativeValues(out, count: count, "Functions.registerVariables") { (value) throws(IDAError) -> Functions.RegisterVariable in try Functions.RegisterVariable(copying: value, "Functions.registerVariables") }
    }

    public static func itemAddresses(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Functions.itemAddresses")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_function_item_addresses(address, &out, &count), "Functions.itemAddresses")
        return try copyNativeValues(out, count: count, "Functions.itemAddresses") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func codeAddresses(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Functions.codeAddresses")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_function_code_addresses(address, &out, &count), "Functions.codeAddresses")
        return try copyNativeValues(out, count: count, "Functions.codeAddresses") { (value) throws(IDAError) -> UInt64 in value }
    }
}
