// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Instructions {
    public enum OperandType: Int32, CaseIterable, Sendable {
        case none = 0
        case register = 1
        case memoryDirect = 2
        case memoryPhrase = 3
        case memoryDisplacement = 4
        case immediate = 5
        case farAddress = 6
        case nearAddress = 7
        case processorSpecific0 = 8
        case processorSpecific1 = 9
        case processorSpecific2 = 10
        case processorSpecific3 = 11
        case processorSpecific4 = 12
        case processorSpecific5 = 13
    }

    public enum OperandFormat: Int32, CaseIterable, Sendable {
        case `default` = 0
        case hex = 1
        case decimal = 2
        case octal = 3
        case binary = 4
        case character = 5
        case float = 6
        case offset = 7
        case stackVariable = 8
    }

    public enum RegisterCategory: Int32, CaseIterable, Sendable {
        case unknown = 0
        case generalPurpose = 1
        case segment = 2
        case floatingPoint = 3
        case vector = 4
        case mask = 5
        case control = 6
        case debug = 7
        case other = 8
    }

    public enum BranchCondition: Int32, CaseIterable, Sendable {
        case none = 0
        case always = 1
        case equal = 2
        case notEqual = 3
        case lessThanSigned = 4
        case lessThanOrEqualSigned = 5
        case greaterThanSigned = 6
        case greaterThanOrEqualSigned = 7
        case lessThanUnsigned = 8
        case lessThanOrEqualUnsigned = 9
        case greaterThanUnsigned = 10
        case greaterThanOrEqualUnsigned = 11
        case zero = 12
        case notZero = 13
        case negative = 14
        case notNegative = 15
        case overflow = 16
        case noOverflow = 17
        case parity = 18
        case noParity = 19
        case countZero = 20
        case bitZero = 21
        case bitNotZero = 22
        case countNotZero = 23
        case countNotZeroAndEqual = 24
        case countNotZeroAndNotEqual = 25
        case unknown = 26
        case never = 27
    }

    public struct Instruction: Equatable, Sendable {
        public var address: UInt64
        public var size: UInt64
        public var opcode: UInt16
        public var mnemonic: String
        public var operands: [Instructions.Operand]
        public var branchCondition: Instructions.BranchCondition

        public init(address: UInt64, size: UInt64, opcode: UInt16, mnemonic: String, operands: [Instructions.Operand], branchCondition: Instructions.BranchCondition) {
            self.address = address
            self.size = size
            self.opcode = opcode
            self.mnemonic = mnemonic
            self.operands = operands
            self.branchCondition = branchCondition
        }

        internal init(copying native: IdaxInstruction, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.size = native.size
            self.opcode = native.opcode
            self.mnemonic = try borrowCString(native.mnemonic.map { UnsafePointer($0) }, operation)
            self.operands = try copyNativeValues(native.operands, count: Int(native.operand_count), operation) { (value) throws(IDAError) -> Instructions.Operand in try Instructions.Operand(copying: value, operation) }
            self.branchCondition = try checkedNativeEnum(Instructions.BranchCondition.self, native.branch_condition, operation)
        }
    }

    public struct Operand: Equatable, Sendable {
        public var index: Int32
        public var type: Instructions.OperandType
        public var registerId: UInt16
        public var value: UInt64
        public var targetAddress: UInt64
        public var byteWidth: Int32
        public var encodedValueByteOffset: Int?
        public var secondaryEncodedValueByteOffset: Int?
        public var registerName: String
        public var registerCategory: Instructions.RegisterCategory
        public var isRead: Bool
        public var isWritten: Bool

        public init(index: Int32, type: Instructions.OperandType, registerId: UInt16, value: UInt64, targetAddress: UInt64, byteWidth: Int32, encodedValueByteOffset: Int?, secondaryEncodedValueByteOffset: Int?, registerName: String, registerCategory: Instructions.RegisterCategory, isRead: Bool, isWritten: Bool) {
            self.index = index
            self.type = type
            self.registerId = registerId
            self.value = value
            self.targetAddress = targetAddress
            self.byteWidth = byteWidth
            self.encodedValueByteOffset = encodedValueByteOffset
            self.secondaryEncodedValueByteOffset = secondaryEncodedValueByteOffset
            self.registerName = registerName
            self.registerCategory = registerCategory
            self.isRead = isRead
            self.isWritten = isWritten
        }

        internal init(copying native: IdaxOperand, _ operation: String) throws(IDAError) {
            self.index = native.index
            self.type = try checkedNativeEnum(Instructions.OperandType.self, native.type, operation)
            self.registerId = native.register_id
            self.value = native.value
            self.targetAddress = native.target_address
            self.byteWidth = native.byte_width
            self.encodedValueByteOffset = native.encoded_value_byte_offset == -1 ? nil : Int(native.encoded_value_byte_offset)
            self.secondaryEncodedValueByteOffset = native.secondary_encoded_value_byte_offset == -1 ? nil : Int(native.secondary_encoded_value_byte_offset)
            self.registerName = try borrowCString(native.register_name.map { UnsafePointer($0) }, operation)
            self.registerCategory = try checkedNativeEnum(Instructions.RegisterCategory.self, native.register_category, operation)
            self.isRead = native.is_read != 0
            self.isWritten = native.is_written != 0
        }
    }

    public static func branchCondition(address: UInt64) throws(IDAError) -> Instructions.BranchCondition {
        try requireRuntimeThread("Instructions.branchCondition")
        var out: Int32 = 0
        try checkStatus(idax_instruction_branch_condition(address, &out), "Instructions.branchCondition")
        return try checkedNativeEnum(Instructions.BranchCondition.self, out, "Instructions.branchCondition")
    }

    public static func decode(address: UInt64) throws(IDAError) -> Instructions.Instruction {
        try requireRuntimeThread("Instructions.decode")
        var out = IdaxInstruction()
        defer { idax_instruction_free(&out) }
        try checkStatus(idax_instruction_decode(address, &out), "Instructions.decode")
        return try Instructions.Instruction(copying: out, "Instructions.decode")
    }

    public static func create(address: UInt64) throws(IDAError) -> Instructions.Instruction {
        try requireRuntimeThread("Instructions.create")
        var out = IdaxInstruction()
        defer { idax_instruction_free(&out) }
        try checkStatus(idax_instruction_create(address, &out), "Instructions.create")
        return try Instructions.Instruction(copying: out, "Instructions.create")
    }

    public static func text(address: UInt64) throws(IDAError) -> String {
        try requireRuntimeThread("Instructions.text")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_instruction_text(address, &out), "Instructions.text")
        return try borrowCString(out.map { UnsafePointer($0) }, "Instructions.text")
    }

    public static func setOperandHex(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandHex")
        try checkStatus(idax_instruction_set_operand_hex(address, operandIndex), "Instructions.setOperandHex")
    }

    public static func setOperandDecimal(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandDecimal")
        try checkStatus(idax_instruction_set_operand_decimal(address, operandIndex), "Instructions.setOperandDecimal")
    }

    public static func setOperandOctal(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandOctal")
        try checkStatus(idax_instruction_set_operand_octal(address, operandIndex), "Instructions.setOperandOctal")
    }

    public static func setOperandBinary(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandBinary")
        try checkStatus(idax_instruction_set_operand_binary(address, operandIndex), "Instructions.setOperandBinary")
    }

    public static func setOperandCharacter(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandCharacter")
        try checkStatus(idax_instruction_set_operand_character(address, operandIndex), "Instructions.setOperandCharacter")
    }

    public static func setOperandFloat(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandFloat")
        try checkStatus(idax_instruction_set_operand_float(address, operandIndex), "Instructions.setOperandFloat")
    }

    public static func setOperandFormat(address: UInt64, operandIndex: Int32, format: Instructions.OperandFormat, base: UInt64 = 0) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandFormat")
        try checkStatus(idax_instruction_set_operand_format(address, operandIndex, Int32(format.rawValue), base), "Instructions.setOperandFormat")
    }

    public static func setOperandOffset(address: UInt64, operandIndex: Int32, base: UInt64 = 0) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandOffset")
        try checkStatus(idax_instruction_set_operand_offset(address, operandIndex, base), "Instructions.setOperandOffset")
    }

    public static func setOperandEnum(address: UInt64, operandIndex: Int32, enumName: String, serial: UInt8 = 0) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandEnum")
        try validateCString(enumName, "Instructions.setOperandEnum")
        try checkStatus(enumName.withCString { c_enum_name in idax_instruction_set_operand_enum(address, operandIndex, c_enum_name, serial)}, "Instructions.setOperandEnum")
    }

    public static func setOperandStructOffsetByName(address: UInt64, operandIndex: Int32, structureName: String, delta: Int64 = 0) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandStructOffsetByName")
        try validateCString(structureName, "Instructions.setOperandStructOffsetByName")
        try checkStatus(structureName.withCString { c_structure_name in idax_instruction_set_operand_struct_offset_by_name(address, operandIndex, c_structure_name, delta)}, "Instructions.setOperandStructOffsetByName")
    }

    public static func ensureOperandStructMemberOffset(address: UInt64, operandIndex: Int32, structureName: String, memberByteOffset: Int, delta: Int64 = 0) throws(IDAError) -> Bool {
        try requireRuntimeThread("Instructions.ensureOperandStructMemberOffset")
        try validateCString(structureName, "Instructions.ensureOperandStructMemberOffset")
        try requireNonnegative(memberByteOffset, "Instructions.ensureOperandStructMemberOffset")
        var out_added: Int32 = 0
        try checkStatus(structureName.withCString { c_structure_name in idax_instruction_ensure_operand_struct_member_offset(address, operandIndex, c_structure_name, memberByteOffset, delta, &out_added)}, "Instructions.ensureOperandStructMemberOffset")
        return out_added != 0
    }

    public static func setOperandBasedStructOffset(address: UInt64, operandIndex: Int32, operandValue: UInt64, base: UInt64) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandBasedStructOffset")
        try checkStatus(idax_instruction_set_operand_based_struct_offset(address, operandIndex, operandValue, base), "Instructions.setOperandBasedStructOffset")
    }

    public static func operandStructOffsetPathNames(address: UInt64, operandIndex: Int32) throws(IDAError) -> [String] {
        try requireRuntimeThread("Instructions.operandStructOffsetPathNames")
        var out: UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?
        var count: Int = 0
        defer { idax_instruction_string_array_free(out, count) }
        try checkStatus(idax_instruction_operand_struct_offset_path_names(address, operandIndex, &out, &count), "Instructions.operandStructOffsetPathNames")
        return try copyNativeValues(out, count: count, "Instructions.operandStructOffsetPathNames") { (value) throws(IDAError) -> String in try borrowCString(value.map { UnsafePointer($0) }, "Instructions.operandStructOffsetPathNames") }
    }

    public static func setOperandStackVariable(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.setOperandStackVariable")
        try checkStatus(idax_instruction_set_operand_stack_variable(address, operandIndex), "Instructions.setOperandStackVariable")
    }

    public static func clearOperandRepresentation(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.clearOperandRepresentation")
        try checkStatus(idax_instruction_clear_operand_representation(address, operandIndex), "Instructions.clearOperandRepresentation")
    }

    public static func setForcedOperand(address: UInt64, operandIndex: Int32, text: String) throws(IDAError) {
        try requireRuntimeThread("Instructions.setForcedOperand")
        try validateCString(text, "Instructions.setForcedOperand")
        try checkStatus(text.withCString { c_text in idax_instruction_set_forced_operand(address, operandIndex, c_text)}, "Instructions.setForcedOperand")
    }

    public static func getForcedOperand(address: UInt64, operandIndex: Int32) throws(IDAError) -> String {
        try requireRuntimeThread("Instructions.getForcedOperand")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_instruction_get_forced_operand(address, operandIndex, &out), "Instructions.getForcedOperand")
        return try borrowCString(out.map { UnsafePointer($0) }, "Instructions.getForcedOperand")
    }

    public static func operandText(address: UInt64, operandIndex: Int32) throws(IDAError) -> String {
        try requireRuntimeThread("Instructions.operandText")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_instruction_operand_text(address, operandIndex, &out), "Instructions.operandText")
        return try borrowCString(out.map { UnsafePointer($0) }, "Instructions.operandText")
    }

    public static func operandByteWidth(address: UInt64, operandIndex: Int32) throws(IDAError) -> Int32 {
        try requireRuntimeThread("Instructions.operandByteWidth")
        var out: Int32 = 0
        try checkStatus(idax_instruction_operand_byte_width(address, operandIndex, &out), "Instructions.operandByteWidth")
        return out
    }

    public static func operandRegisterName(address: UInt64, operandIndex: Int32) throws(IDAError) -> String {
        try requireRuntimeThread("Instructions.operandRegisterName")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_instruction_operand_register_name(address, operandIndex, &out), "Instructions.operandRegisterName")
        return try borrowCString(out.map { UnsafePointer($0) }, "Instructions.operandRegisterName")
    }

    public static func operandRegisterCategory(address: UInt64, operandIndex: Int32) throws(IDAError) -> Instructions.RegisterCategory {
        try requireRuntimeThread("Instructions.operandRegisterCategory")
        var out: Int32 = 0
        try checkStatus(idax_instruction_operand_register_category(address, operandIndex, &out), "Instructions.operandRegisterCategory")
        return try checkedNativeEnum(Instructions.RegisterCategory.self, out, "Instructions.operandRegisterCategory")
    }

    public static func toggleOperandSign(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.toggleOperandSign")
        try checkStatus(idax_instruction_toggle_operand_sign(address, operandIndex), "Instructions.toggleOperandSign")
    }

    public static func toggleOperandNegate(address: UInt64, operandIndex: Int32) throws(IDAError) {
        try requireRuntimeThread("Instructions.toggleOperandNegate")
        try checkStatus(idax_instruction_toggle_operand_negate(address, operandIndex), "Instructions.toggleOperandNegate")
    }

    public static func codeRefsFrom(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Instructions.codeRefsFrom")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_instruction_code_refs_from(address, &out, &count), "Instructions.codeRefsFrom")
        return try copyNativeValues(out, count: count, "Instructions.codeRefsFrom") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func dataRefsFrom(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Instructions.dataRefsFrom")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_instruction_data_refs_from(address, &out, &count), "Instructions.dataRefsFrom")
        return try copyNativeValues(out, count: count, "Instructions.dataRefsFrom") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func callTargets(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Instructions.callTargets")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_instruction_call_targets(address, &out, &count), "Instructions.callTargets")
        return try copyNativeValues(out, count: count, "Instructions.callTargets") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func jumpTargets(address: UInt64) throws(IDAError) -> [UInt64] {
        try requireRuntimeThread("Instructions.jumpTargets")
        var out: UnsafeMutablePointer<UInt64>?
        var count: Int = 0
        defer { idax_free_addresses(out) }
        try checkStatus(idax_instruction_jump_targets(address, &out, &count), "Instructions.jumpTargets")
        return try copyNativeValues(out, count: count, "Instructions.jumpTargets") { (value) throws(IDAError) -> UInt64 in value }
    }

    public static func hasFallThrough(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Instructions.hasFallThrough")
        let result = idax_instruction_has_fall_through(address)
        return result != 0
    }

    public static func isCall(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Instructions.isCall")
        let result = idax_instruction_is_call(address)
        return result != 0
    }

    public static func isReturn(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Instructions.isReturn")
        let result = idax_instruction_is_return(address)
        return result != 0
    }

    public static func isJump(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Instructions.isJump")
        let result = idax_instruction_is_jump(address)
        return result != 0
    }

    public static func isConditionalJump(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Instructions.isConditionalJump")
        let result = idax_instruction_is_conditional_jump(address)
        return result != 0
    }

    public static func next(address: UInt64) throws(IDAError) -> Instructions.Instruction {
        try requireRuntimeThread("Instructions.next")
        var out = IdaxInstruction()
        defer { idax_instruction_free(&out) }
        try checkStatus(idax_instruction_next(address, &out), "Instructions.next")
        return try Instructions.Instruction(copying: out, "Instructions.next")
    }

    public static func prev(address: UInt64) throws(IDAError) -> Instructions.Instruction {
        try requireRuntimeThread("Instructions.prev")
        var out = IdaxInstruction()
        defer { idax_instruction_free(&out) }
        try checkStatus(idax_instruction_prev(address, &out), "Instructions.prev")
        return try Instructions.Instruction(copying: out, "Instructions.prev")
    }
}
