// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Lines {
    public enum Color: Int32, CaseIterable, Sendable {
        case `default` = 1
        case regularComment = 2
        case repeatableComment = 3
        case autoComment = 4
        case instruction = 5
        case dataName = 6
        case regularDataName = 7
        case demangledName = 8
        case symbol = 9
        case charLiteral = 10
        case string = 11
        case number = 12
        case void = 13
        case codeReference = 14
        case dataReference = 15
        case codeRefTail = 16
        case dataRefTail = 17
        case error = 18
        case prefix = 19
        case binaryPrefix = 20
        case extra = 21
        case altOperand = 22
        case hiddenName = 23
        case libraryName = 24
        case localName = 25
        case dummyCodeName = 26
        case asmDirective = 27
        case macro = 28
        case dataString = 29
        case dataChar = 30
        case dataNumber = 31
        case keyword = 32
        case register = 33
        case importedName = 34
        case segmentName = 35
        case unknownName = 36
        case codeName = 37
        case userName = 38
        case collapsed = 39
    }

    public struct SourceFile: Equatable, Sendable {
        public var filename: String
        public var start: UInt64
        public var end: UInt64

        public init(filename: String, start: UInt64, end: UInt64) {
            self.filename = filename
            self.start = start
            self.end = end
        }

        internal init(copying native: IdaxLinesSourceFile, _ operation: String) throws(IDAError) {
            self.filename = try borrowCString(native.filename.map { UnsafePointer($0) }, operation)
            self.start = native.start
            self.end = native.end
        }
    }

    public static func addSourceFile(start: UInt64, end: UInt64, filename: String) throws(IDAError) {
        try requireRuntimeThread("Lines.addSourceFile")
        try validateCString(filename, "Lines.addSourceFile")
        try checkStatus(filename.withCString { c_filename in idax_lines_add_source_file(start, end, c_filename)}, "Lines.addSourceFile")
    }

    public static func sourceFileAt(address: UInt64) throws(IDAError) -> Lines.SourceFile {
        try requireRuntimeThread("Lines.sourceFileAt")
        var out = IdaxLinesSourceFile()
        defer { idax_lines_source_file_free(&out) }
        try checkStatus(idax_lines_source_file_at(address, &out), "Lines.sourceFileAt")
        return try Lines.SourceFile(copying: out, "Lines.sourceFileAt")
    }

    public static func removeSourceFile(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Lines.removeSourceFile")
        try checkStatus(idax_lines_remove_source_file(address), "Lines.removeSourceFile")
    }

    public static func colstr(text: String, color: Lines.Color) throws(IDAError) -> String {
        try requireRuntimeThread("Lines.colstr")
        try validateCString(text, "Lines.colstr")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(text.withCString { c_text in idax_lines_colstr(c_text, UInt8(color.rawValue), &out)}, "Lines.colstr")
        return try borrowCString(out.map { UnsafePointer($0) }, "Lines.colstr")
    }

    public static func tagRemove(taggedText: String) throws(IDAError) -> String {
        try requireRuntimeThread("Lines.tagRemove")
        try validateCString(taggedText, "Lines.tagRemove")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(taggedText.withCString { c_tagged_text in idax_lines_tag_remove(c_tagged_text, &out)}, "Lines.tagRemove")
        return try borrowCString(out.map { UnsafePointer($0) }, "Lines.tagRemove")
    }

    public static func tagAdvance(taggedText: String, pos: Int32) throws(IDAError) -> Int32 {
        try requireRuntimeThread("Lines.tagAdvance")
        try validateCString(taggedText, "Lines.tagAdvance")
        let result = taggedText.withCString { c_tagged_text in idax_lines_tag_advance(c_tagged_text, pos)}
        return result
    }

    public static func tagStrlen(taggedText: String) throws(IDAError) -> Int {
        try requireRuntimeThread("Lines.tagStrlen")
        try validateCString(taggedText, "Lines.tagStrlen")
        let result = taggedText.withCString { c_tagged_text in idax_lines_tag_strlen(c_tagged_text)}
        return result
    }

    public static func makeAddrTag(itemIndex: Int32) throws(IDAError) -> String {
        try requireRuntimeThread("Lines.makeAddrTag")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_lines_make_addr_tag(itemIndex, &out), "Lines.makeAddrTag")
        return try borrowCString(out.map { UnsafePointer($0) }, "Lines.makeAddrTag")
    }

    public static func decodeAddrTag(taggedText: String, pos: Int) throws(IDAError) -> Int32 {
        try requireRuntimeThread("Lines.decodeAddrTag")
        try validateCString(taggedText, "Lines.decodeAddrTag")
        try requireNonnegative(pos, "Lines.decodeAddrTag")
        let result = taggedText.withCString { c_tagged_text in idax_lines_decode_addr_tag(c_tagged_text, pos)}
        return result
    }
}
