// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Lumina {
    public enum Feature: Int32, CaseIterable, Sendable {
        case primaryMetadata = 0
        case decompiler = 1
        case telemetry = 2
        case secondaryMetadata = 3
    }

    public enum PushMode: Int32, CaseIterable, Sendable {
        case preferBetterOrDifferent = 0
        case override = 1
        case keepExisting = 2
        case merge = 3
    }

    public enum OperationCode: Int32, CaseIterable, Sendable {
        case badPattern = -3
        case notFound = -2
        case error = -1
        case ok = 0
        case added = 1
    }

    public static func hasConnection(feature: Lumina.Feature = .primaryMetadata) throws(IDAError) -> Bool {
        try requireRuntimeThread("Lumina.hasConnection")
        var out: Int32 = 0
        try checkStatus(idax_lumina_has_connection(Int32(feature.rawValue), &out), "Lumina.hasConnection")
        return out != 0
    }

    public static func closeConnection(feature: Lumina.Feature = .primaryMetadata) throws(IDAError) {
        try requireRuntimeThread("Lumina.closeConnection")
        try checkStatus(idax_lumina_close_connection(Int32(feature.rawValue)), "Lumina.closeConnection")
    }

    public static func closeAllConnections() throws(IDAError) {
        try requireRuntimeThread("Lumina.closeAllConnections")
        try checkStatus(idax_lumina_close_all_connections(), "Lumina.closeAllConnections")
    }
}
