internal import CIDAX

extension Names {
    public struct ListOptions: Equatable, Sendable {
        public var start: Address
        public var end: Address
        public var includeUserDefined: Bool
        public var includeAutoGenerated: Bool
        public init(start: Address = badAddress, end: Address = badAddress,
            includeUserDefined: Bool = true, includeAutoGenerated: Bool = true
        ) {
            self.start = start
            self.end = end
            self.includeUserDefined = includeUserDefined
            self.includeAutoGenerated = includeAutoGenerated
        }
    }
    public static func all(options: ListOptions = .init()) throws(IDAError) -> [Entry] {
        let operation = "Names.all"
        try requireRuntimeThread(operation)
        var output: UnsafeMutablePointer<IdaxNameEntry>?
        var count = 0
        defer { idax_name_entries_free(output, count) }
        try checkStatus(idax_name_all(options.start, options.end,
            options.includeUserDefined ? 1 : 0, options.includeAutoGenerated ? 1 : 0,
            &output, &count), operation)
        return try copyNativeValues(output, count: count, operation) {
            (value) throws(IDAError) -> Entry in try Entry(copying: value, operation)
        }
    }
    public static func demangled(symbol: String, form: DemangleForm = .short) throws(IDAError) -> String {
        try demangle(symbol: symbol, form: form)
    }
}
