// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Names {
    public enum DemangleForm: Int32, CaseIterable, Sendable {
        case short = 0
        case long = 1
        case full = 2
    }

    public struct Entry: Equatable, Sendable {
        public var address: UInt64
        public var name: String
        public var userDefined: Bool
        public var autoGenerated: Bool

        public init(address: UInt64, name: String, userDefined: Bool, autoGenerated: Bool) {
            self.address = address
            self.name = name
            self.userDefined = userDefined
            self.autoGenerated = autoGenerated
        }

        internal init(copying native: IdaxNameEntry, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.userDefined = native.user_defined != 0
            self.autoGenerated = native.auto_generated != 0
        }
    }

    public static func get(address: UInt64) throws(IDAError) -> String {
        try requireRuntimeThread("Names.get")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_name_get(address, &out), "Names.get")
        return try borrowCString(out.map { UnsafePointer($0) }, "Names.get")
    }

    public static func set(address: UInt64, name: String) throws(IDAError) {
        try requireRuntimeThread("Names.set")
        try validateCString(name, "Names.set")
        try checkStatus(name.withCString { c_name in idax_name_set(address, c_name)}, "Names.set")
    }

    public static func forceSet(address: UInt64, name: String) throws(IDAError) {
        try requireRuntimeThread("Names.forceSet")
        try validateCString(name, "Names.forceSet")
        try checkStatus(name.withCString { c_name in idax_name_force_set(address, c_name)}, "Names.forceSet")
    }

    public static func remove(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Names.remove")
        try checkStatus(idax_name_remove(address), "Names.remove")
    }

    public static func demangled(address: UInt64, form: Names.DemangleForm = .short) throws(IDAError) -> String {
        try requireRuntimeThread("Names.demangled")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_name_demangled(address, Int32(form.rawValue), &out), "Names.demangled")
        return try borrowCString(out.map { UnsafePointer($0) }, "Names.demangled")
    }

    public static func demangle(symbol: String, form: Names.DemangleForm = .short) throws(IDAError) -> String {
        try requireRuntimeThread("Names.demangle")
        try validateCString(symbol, "Names.demangle")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(symbol.withCString { c_symbol in idax_name_demangle(c_symbol, Int32(form.rawValue), &out)}, "Names.demangle")
        return try borrowCString(out.map { UnsafePointer($0) }, "Names.demangle")
    }

    public static func resolve(name: String, context: UInt64 = badAddress) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Names.resolve")
        try validateCString(name, "Names.resolve")
        var out: UInt64 = 0
        try checkStatus(name.withCString { c_name in idax_name_resolve(c_name, context, &out)}, "Names.resolve")
        return out
    }

    public static func allUserDefined(start: UInt64 = badAddress, end: UInt64 = badAddress) throws(IDAError) -> [Names.Entry] {
        try requireRuntimeThread("Names.allUserDefined")
        var out: UnsafeMutablePointer<IdaxNameEntry>?
        var count: Int = 0
        defer { idax_name_entries_free(out, count) }
        try checkStatus(idax_name_all_user_defined(start, end, &out, &count), "Names.allUserDefined")
        return try copyNativeValues(out, count: count, "Names.allUserDefined") { (value) throws(IDAError) -> Names.Entry in try Names.Entry(copying: value, "Names.allUserDefined") }
    }

    public static func isPublic(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Names.isPublic")
        let result = idax_name_is_public(address)
        return result != 0
    }

    public static func isWeak(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Names.isWeak")
        let result = idax_name_is_weak(address)
        return result != 0
    }

    public static func isUserDefined(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Names.isUserDefined")
        let result = idax_name_is_user_defined(address)
        return result != 0
    }

    public static func isAutoGenerated(address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Names.isAutoGenerated")
        let result = idax_name_is_auto_generated(address)
        return result != 0
    }

    public static func isValidIdentifier(text: String) throws(IDAError) -> Bool {
        try requireRuntimeThread("Names.isValidIdentifier")
        try validateCString(text, "Names.isValidIdentifier")
        var out: Int32 = 0
        try checkStatus(text.withCString { c_text in idax_name_is_valid_identifier(c_text, &out)}, "Names.isValidIdentifier")
        return out != 0
    }

    public static func sanitizeIdentifier(text: String) throws(IDAError) -> String {
        try requireRuntimeThread("Names.sanitizeIdentifier")
        try validateCString(text, "Names.sanitizeIdentifier")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(text.withCString { c_text in idax_name_sanitize_identifier(c_text, &out)}, "Names.sanitizeIdentifier")
        return try borrowCString(out.map { UnsafePointer($0) }, "Names.sanitizeIdentifier")
    }

    public static func setPublic(address: UInt64, value: Bool = true) throws(IDAError) {
        try requireRuntimeThread("Names.setPublic")
        try checkStatus(idax_name_set_public(address, (value ? 1 : 0)), "Names.setPublic")
    }

    public static func setWeak(address: UInt64, value: Bool = true) throws(IDAError) {
        try requireRuntimeThread("Names.setWeak")
        try checkStatus(idax_name_set_weak(address, (value ? 1 : 0)), "Names.setWeak")
    }
}
