// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Offsets {
    public enum ReferenceKind: Int32, CaseIterable, Sendable {
        case offset8 = 0
        case offset16 = 1
        case offset32 = 2
        case offset64 = 3
        case low8 = 4
        case low16 = 5
        case low32 = 6
        case high8 = 7
        case high16 = 8
        case high32 = 9
        case custom = 10
    }

    public enum ExpressionComplexity: Int32, CaseIterable, Sendable {
        case simple = 0
        case complex = 1
    }

    public static func possibleOffset32Target(address: UInt64) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Offsets.possibleOffset32Target")
        var out: UInt64 = 0
        var has_value: Int32 = 0
        try checkStatus(idax_offset_possible_offset32_target(address, &out, &has_value), "Offsets.possibleOffset32Target")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func probableBase(address: UInt64, operandValue: UInt64) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Offsets.probableBase")
        var out: UInt64 = 0
        var has_value: Int32 = 0
        try checkStatus(idax_offset_probable_base(address, operandValue, &out, &has_value), "Offsets.probableBase")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func calculateBaseValue(target: UInt64, base: UInt64) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Offsets.calculateBaseValue")
        var out: UInt64 = 0
        var has_value: Int32 = 0
        try checkStatus(idax_offset_calculate_base_value(target, base, &out, &has_value), "Offsets.calculateBaseValue")
        guard has_value != 0 else { return nil }
        return out
    }
}
