// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Parser {
    public enum InputKind: Int32, CaseIterable, Sendable {
        case sourceText = 0
        case filePath = 1
    }

    public struct ParseReport: Equatable, Sendable {
        public var errorCount: Int

        public init(errorCount: Int = 0) {
            self.errorCount = errorCount
        }

        internal init(copying native: IdaxParserParseReport, _ operation: String) throws(IDAError) {
            self.errorCount = native.error_count
        }
    }
}
