// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Paths {
    public static func basename(path: String) throws(IDAError) -> String {
        try requireRuntimeThread("Paths.basename")
        try validateCString(path, "Paths.basename")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(path.withCString { c_path in idax_path_basename(c_path, &out)}, "Paths.basename")
        return try borrowCString(out.map { UnsafePointer($0) }, "Paths.basename")
    }

    public static func dirname(path: String) throws(IDAError) -> String {
        try requireRuntimeThread("Paths.dirname")
        try validateCString(path, "Paths.dirname")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(path.withCString { c_path in idax_path_dirname(c_path, &out)}, "Paths.dirname")
        return try borrowCString(out.map { UnsafePointer($0) }, "Paths.dirname")
    }

    public static func isDirectory(path: String) throws(IDAError) -> Bool {
        try requireRuntimeThread("Paths.isDirectory")
        try validateCString(path, "Paths.isDirectory")
        var out: Int32 = 0
        try checkStatus(path.withCString { c_path in idax_path_is_directory(c_path, &out)}, "Paths.isDirectory")
        return out != 0
    }
}
