// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Problems {
    public enum Kind: Int32, CaseIterable, Sendable {
        case missingOffsetBase = 1
        case missingName = 2
        case missingForcedOperand = 3
        case missingComment = 4
        case missingReferences = 5
        case ignoredJumpTable = 6
        case disassemblyFailure = 7
        case alreadyItemHead = 8
        case flowBeyondLimits = 9
        case tooManyLines = 10
        case stackTraceFailure = 11
        case attention = 12
        case analysisDecision = 13
        case rolledBackDecision = 14
        case flairCollision = 15
        case flairIndecision = 16
    }

    public static func description(kind: Problems.Kind, address: UInt64) throws(IDAError) -> String? {
        try requireRuntimeThread("Problems.description")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_problem_description(Int32(kind.rawValue), address, &out), "Problems.description")
        return out == nil ? nil : (try borrowCString(out.map { UnsafePointer($0) }, "Problems.description"))
    }

    public static func next(kind: Problems.Kind, atOrAfter: UInt64 = 0) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Problems.next")
        var out: UInt64 = 0
        var has_value: Int32 = 0
        try checkStatus(idax_problem_next(Int32(kind.rawValue), atOrAfter, &out, &has_value), "Problems.next")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func remove(kind: Problems.Kind, address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Problems.remove")
        var out: Int32 = 0
        try checkStatus(idax_problem_remove(Int32(kind.rawValue), address, &out), "Problems.remove")
        return out != 0
    }

    public static func name(kind: Problems.Kind, longForm: Bool = true) throws(IDAError) -> String {
        try requireRuntimeThread("Problems.name")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_problem_name(Int32(kind.rawValue), (longForm ? 1 : 0), &out), "Problems.name")
        return try borrowCString(out.map { UnsafePointer($0) }, "Problems.name")
    }

    public static func contains(kind: Problems.Kind, address: UInt64) throws(IDAError) -> Bool {
        try requireRuntimeThread("Problems.contains")
        var out: Int32 = 0
        try checkStatus(idax_problem_contains(Int32(kind.rawValue), address, &out), "Problems.contains")
        return out != 0
    }
}
