// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Registers {
    public enum TrackingState: Int32, CaseIterable, Sendable {
        case undefined = 0
        case deadEnd = 1
        case aborted = 2
        case badInstruction = 3
        case unknownInstruction = 4
        case functionInput = 5
        case loopVariant = 6
        case incompatibleValues = 7
        case tooManyReferences = 8
        case tooManyValues = 9
        case constant = 10
        case stackPointerDelta = 11
    }

    public enum ReferenceMutation: Int32, CaseIterable, Sendable {
        case added = 0
        case removed = 1
    }

    public struct TrackedValue: Equatable, Sendable {
        public var state: Registers.TrackingState
        public var candidates: [Registers.ValueCandidate]
        public var cause: Registers.ValueOrigin?
        public var abortingDepth: Int32?
        public var description: String

        public init(state: Registers.TrackingState, candidates: [Registers.ValueCandidate], cause: Registers.ValueOrigin?, abortingDepth: Int32?, description: String) {
            self.state = state
            self.candidates = candidates
            self.cause = cause
            self.abortingDepth = abortingDepth
            self.description = description
        }

        internal init(copying native: IdaxTrackedRegisterValue, _ operation: String) throws(IDAError) {
            self.state = try checkedNativeEnum(Registers.TrackingState.self, native.state, operation)
            self.candidates = try copyNativeValues(native.candidates, count: Int(native.candidate_count), operation) { (value) throws(IDAError) -> Registers.ValueCandidate in try Registers.ValueCandidate(copying: value, operation) }
            self.cause = native.has_cause != 0 ? (try Registers.ValueOrigin(copying: native.cause, operation)) : nil
            self.abortingDepth = native.has_aborting_depth != 0 ? (native.aborting_depth) : nil
            self.description = try borrowCString(native.description.map { UnsafePointer($0) }, operation)
        }
    }

    public struct NearestValue: Equatable, Sendable {
        public var selectedIndex: Int
        public var registerName: String
        public var value: Registers.TrackedValue

        public init(selectedIndex: Int, registerName: String, value: Registers.TrackedValue) {
            self.selectedIndex = selectedIndex
            self.registerName = registerName
            self.value = value
        }

        internal init(copying native: IdaxNearestRegisterValue, _ operation: String) throws(IDAError) {
            self.selectedIndex = native.selected_index
            self.registerName = try borrowCString(native.register_name.map { UnsafePointer($0) }, operation)
            self.value = try Registers.TrackedValue(copying: native.value, operation)
        }
    }

    public struct ValueOrigin: Equatable, Sendable {
        public var address: UInt64
        public var instructionCode: UInt16
        public var shortInstruction: Bool
        public var programCounterBased: Bool
        public var globalOffsetTableLike: Bool

        public init(address: UInt64, instructionCode: UInt16, shortInstruction: Bool, programCounterBased: Bool, globalOffsetTableLike: Bool) {
            self.address = address
            self.instructionCode = instructionCode
            self.shortInstruction = shortInstruction
            self.programCounterBased = programCounterBased
            self.globalOffsetTableLike = globalOffsetTableLike
        }

        internal init(copying native: IdaxRegisterValueOrigin, _ operation: String) throws(IDAError) {
            self.address = native.address
            self.instructionCode = native.instruction_code
            self.shortInstruction = native.short_instruction != 0
            self.programCounterBased = native.program_counter_based != 0
            self.globalOffsetTableLike = native.global_offset_table_like != 0
        }
    }

    public struct ValueCandidate: Equatable, Sendable {
        public var constant: UInt64?
        public var stackPointerDelta: Int64?
        public var origin: Registers.ValueOrigin

        public init(constant: UInt64?, stackPointerDelta: Int64?, origin: Registers.ValueOrigin) {
            self.constant = constant
            self.stackPointerDelta = stackPointerDelta
            self.origin = origin
        }

        internal init(copying native: IdaxRegisterValueCandidate, _ operation: String) throws(IDAError) {
            self.constant = native.has_constant != 0 ? (native.constant) : nil
            self.stackPointerDelta = native.has_stack_pointer_delta != 0 ? (native.stack_pointer_delta) : nil
            self.origin = try Registers.ValueOrigin(copying: native.origin, operation)
        }
    }

    public static func track(address: UInt64, registerName: String, maxDepth: Int32 = 0) throws(IDAError) -> Registers.TrackedValue {
        try requireRuntimeThread("Registers.track")
        try validateCString(registerName, "Registers.track")
        var out = IdaxTrackedRegisterValue()
        defer { idax_registers_tracked_value_free(&out) }
        try checkStatus(registerName.withCString { c_register_name in idax_registers_track(address, c_register_name, maxDepth, &out)}, "Registers.track")
        return try Registers.TrackedValue(copying: out, "Registers.track")
    }

    public static func constantAt(address: UInt64, registerName: String, maxDepth: Int32 = 0) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Registers.constantAt")
        try validateCString(registerName, "Registers.constantAt")
        var out: UInt64 = 0
        var has_value: Int32 = 0
        try checkStatus(registerName.withCString { c_register_name in idax_registers_constant_at(address, c_register_name, maxDepth, &out, &has_value)}, "Registers.constantAt")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func stackDeltaAt(address: UInt64, registerName: String) throws(IDAError) -> Int64? {
        try requireRuntimeThread("Registers.stackDeltaAt")
        try validateCString(registerName, "Registers.stackDeltaAt")
        var out: Int64 = 0
        var has_value: Int32 = 0
        try checkStatus(registerName.withCString { c_register_name in idax_registers_stack_delta_at(address, c_register_name, &out, &has_value)}, "Registers.stackDeltaAt")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func nearestAt(address: UInt64, firstRegister: String, secondRegister: String) throws(IDAError) -> Registers.NearestValue? {
        try requireRuntimeThread("Registers.nearestAt")
        try validateCString(firstRegister, "Registers.nearestAt")
        try validateCString(secondRegister, "Registers.nearestAt")
        var out = IdaxNearestRegisterValue()
        var has_value: Int32 = 0
        defer { idax_registers_nearest_value_free(&out) }
        try checkStatus(firstRegister.withCString { c_first_register in secondRegister.withCString { c_second_register in idax_registers_nearest_at(address, c_first_register, c_second_register, &out, &has_value)}}, "Registers.nearestAt")
        guard has_value != 0 else { return nil }
        return try Registers.NearestValue(copying: out, "Registers.nearestAt")
    }

    public static func clearControlFlowCache() throws(IDAError) {
        try requireRuntimeThread("Registers.clearControlFlowCache")
        try checkStatus(idax_registers_clear_control_flow_cache(), "Registers.clearControlFlowCache")
    }

    public static func clearDataReferenceCache() throws(IDAError) {
        try requireRuntimeThread("Registers.clearDataReferenceCache")
        try checkStatus(idax_registers_clear_data_reference_cache(), "Registers.clearDataReferenceCache")
    }

    public static func controlFlowReferenceChanged(from: UInt64, to: UInt64, mutation: Registers.ReferenceMutation) throws(IDAError) {
        try requireRuntimeThread("Registers.controlFlowReferenceChanged")
        try checkStatus(idax_registers_control_flow_reference_changed(from, to, Int32(mutation.rawValue)), "Registers.controlFlowReferenceChanged")
    }

    public static func dataReferenceChanged(to: UInt64, mutation: Registers.ReferenceMutation) throws(IDAError) {
        try requireRuntimeThread("Registers.dataReferenceChanged")
        try checkStatus(idax_registers_data_reference_changed(to, Int32(mutation.rawValue)), "Registers.dataReferenceChanged")
    }
}
