// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Search {
    public enum Direction: Int32, CaseIterable, Sendable {
        case forward = 0
        case backward = 1
    }

    public static func nextCode(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Search.nextCode")
        var out: UInt64 = 0
        try checkStatus(idax_search_next_code(address, &out), "Search.nextCode")
        return out
    }

    public static func nextData(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Search.nextData")
        var out: UInt64 = 0
        try checkStatus(idax_search_next_data(address, &out), "Search.nextData")
        return out
    }

    public static func nextUnknown(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Search.nextUnknown")
        var out: UInt64 = 0
        try checkStatus(idax_search_next_unknown(address, &out), "Search.nextUnknown")
        return out
    }

    public static func nextError(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Search.nextError")
        var out: UInt64 = 0
        try checkStatus(idax_search_next_error(address, &out), "Search.nextError")
        return out
    }

    public static func nextDefined(address: UInt64) throws(IDAError) -> UInt64 {
        try requireRuntimeThread("Search.nextDefined")
        var out: UInt64 = 0
        try checkStatus(idax_search_next_defined(address, &out), "Search.nextDefined")
        return out
    }
}
