// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Segments {
    public enum Kind: Int32, CaseIterable, Sendable {
        case normal = 0
        case external = 1
        case code = 2
        case data = 3
        case bss = 4
        case absoluteSymbols = 5
        case common = 6
        case null = 7
        case undefined = 8
        case `import` = 9
        case internalMemory = 10
        case group = 11
    }

    public enum SegmentRegisterSource: Int32, CaseIterable, Sendable {
        case inherited = 0
        case user = 1
        case analysis = 2
        case analysisAtSegmentStart = 3
    }

    public struct Segment: Equatable, Sendable {
        public var start: UInt64
        public var end: UInt64
        public var bitness: Int32
        public var type: Segments.Kind
        public var permRead: Bool
        public var permWrite: Bool
        public var permExec: Bool
        public var name: String
        public var className: String
        public var visible: Bool

        public init(start: UInt64, end: UInt64, bitness: Int32, type: Segments.Kind, permRead: Bool, permWrite: Bool, permExec: Bool, name: String, className: String, visible: Bool) {
            self.start = start
            self.end = end
            self.bitness = bitness
            self.type = type
            self.permRead = permRead
            self.permWrite = permWrite
            self.permExec = permExec
            self.name = name
            self.className = className
            self.visible = visible
        }

        internal init(copying native: IdaxSegment, _ operation: String) throws(IDAError) {
            self.start = native.start
            self.end = native.end
            self.bitness = native.bitness
            self.type = try checkedNativeEnum(Segments.Kind.self, native.type, operation)
            self.permRead = native.perm_read != 0
            self.permWrite = native.perm_write != 0
            self.permExec = native.perm_exec != 0
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.className = try borrowCString(native.class_name.map { UnsafePointer($0) }, operation)
            self.visible = native.visible != 0
        }
    }

    public struct RegisterDescriptor: Equatable, Sendable {
        public var name: String
        public var bitWidth: Int
        public var isCode: Bool
        public var isData: Bool

        public init(name: String, bitWidth: Int, isCode: Bool, isData: Bool) {
            self.name = name
            self.bitWidth = bitWidth
            self.isCode = isCode
            self.isData = isData
        }

        internal init(copying native: IdaxSegmentRegisterDescriptor, _ operation: String) throws(IDAError) {
            self.name = try borrowCString(native.name.map { UnsafePointer($0) }, operation)
            self.bitWidth = native.bit_width
            self.isCode = native.is_code != 0
            self.isData = native.is_data != 0
        }
    }

    public struct RegisterRange: Equatable, Sendable {
        public var start: UInt64
        public var end: UInt64
        public var value: UInt64?
        public var source: Segments.SegmentRegisterSource

        public init(start: UInt64, end: UInt64, value: UInt64?, source: Segments.SegmentRegisterSource) {
            self.start = start
            self.end = end
            self.value = value
            self.source = source
        }

        internal init(copying native: IdaxSegmentRegisterRange, _ operation: String) throws(IDAError) {
            self.start = native.start
            self.end = native.end
            self.value = native.has_value != 0 ? (native.value) : nil
            self.source = try checkedNativeEnum(Segments.SegmentRegisterSource.self, native.source, operation)
        }
    }

    public static func at(address: UInt64) throws(IDAError) -> Segments.Segment {
        try requireRuntimeThread("Segments.at")
        var out = IdaxSegment()
        defer { idax_segment_free(&out) }
        try checkStatus(idax_segment_at(address, &out), "Segments.at")
        return try Segments.Segment(copying: out, "Segments.at")
    }

    public static func byName(name: String) throws(IDAError) -> Segments.Segment {
        try requireRuntimeThread("Segments.byName")
        try validateCString(name, "Segments.byName")
        var out = IdaxSegment()
        defer { idax_segment_free(&out) }
        try checkStatus(name.withCString { c_name in idax_segment_by_name(c_name, &out)}, "Segments.byName")
        return try Segments.Segment(copying: out, "Segments.byName")
    }

    public static func byIndex(index: Int) throws(IDAError) -> Segments.Segment {
        try requireRuntimeThread("Segments.byIndex")
        try requireNonnegative(index, "Segments.byIndex")
        var out = IdaxSegment()
        defer { idax_segment_free(&out) }
        try checkStatus(idax_segment_by_index(index, &out), "Segments.byIndex")
        return try Segments.Segment(copying: out, "Segments.byIndex")
    }

    public static func count() throws(IDAError) -> Int {
        try requireRuntimeThread("Segments.count")
        var out: Int = 0
        try checkStatus(idax_segment_count(&out), "Segments.count")
        return out
    }

    public static func remove(address: UInt64) throws(IDAError) {
        try requireRuntimeThread("Segments.remove")
        try checkStatus(idax_segment_remove(address), "Segments.remove")
    }

    public static func setName(address: UInt64, name: String) throws(IDAError) {
        try requireRuntimeThread("Segments.setName")
        try validateCString(name, "Segments.setName")
        try checkStatus(name.withCString { c_name in idax_segment_set_name(address, c_name)}, "Segments.setName")
    }

    public static func setClass(address: UInt64, className: String) throws(IDAError) {
        try requireRuntimeThread("Segments.setClass")
        try validateCString(className, "Segments.setClass")
        try checkStatus(className.withCString { c_class_name in idax_segment_set_class(address, c_class_name)}, "Segments.setClass")
    }

    public static func setType(address: UInt64, type: Segments.Kind) throws(IDAError) {
        try requireRuntimeThread("Segments.setType")
        try checkStatus(idax_segment_set_type(address, Int32(type.rawValue)), "Segments.setType")
    }

    public static func setPermissions(address: UInt64, read: Bool, write: Bool, exec: Bool) throws(IDAError) {
        try requireRuntimeThread("Segments.setPermissions")
        try checkStatus(idax_segment_set_permissions(address, (read ? 1 : 0), (write ? 1 : 0), (exec ? 1 : 0)), "Segments.setPermissions")
    }

    public static func setBitness(address: UInt64, bits: Int32) throws(IDAError) {
        try requireRuntimeThread("Segments.setBitness")
        try checkStatus(idax_segment_set_bitness(address, bits), "Segments.setBitness")
    }

    public static func comment(address: UInt64, repeatable: Bool = false) throws(IDAError) -> String {
        try requireRuntimeThread("Segments.comment")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_segment_comment(address, (repeatable ? 1 : 0), &out), "Segments.comment")
        return try borrowCString(out.map { UnsafePointer($0) }, "Segments.comment")
    }

    public static func setComment(address: UInt64, text: String, repeatable: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Segments.setComment")
        try validateCString(text, "Segments.setComment")
        try checkStatus(text.withCString { c_text in idax_segment_set_comment(address, c_text, (repeatable ? 1 : 0))}, "Segments.setComment")
    }

    public static func resize(address: UInt64, newStart: UInt64, newEnd: UInt64) throws(IDAError) {
        try requireRuntimeThread("Segments.resize")
        try checkStatus(idax_segment_resize(address, newStart, newEnd), "Segments.resize")
    }

    public static func move(address: UInt64, newStart: UInt64) throws(IDAError) {
        try requireRuntimeThread("Segments.move")
        try checkStatus(idax_segment_move(address, newStart), "Segments.move")
    }

    public static func next(address: UInt64) throws(IDAError) -> Segments.Segment {
        try requireRuntimeThread("Segments.next")
        var out = IdaxSegment()
        defer { idax_segment_free(&out) }
        try checkStatus(idax_segment_next(address, &out), "Segments.next")
        return try Segments.Segment(copying: out, "Segments.next")
    }

    public static func prev(address: UInt64) throws(IDAError) -> Segments.Segment {
        try requireRuntimeThread("Segments.prev")
        var out = IdaxSegment()
        defer { idax_segment_free(&out) }
        try checkStatus(idax_segment_prev(address, &out), "Segments.prev")
        return try Segments.Segment(copying: out, "Segments.prev")
    }

    public static func setDefaultSegmentRegister(address: UInt64, registerIndex: Int32, value: UInt64) throws(IDAError) {
        try requireRuntimeThread("Segments.setDefaultSegmentRegister")
        try checkStatus(idax_segment_set_default_segment_register(address, registerIndex, value), "Segments.setDefaultSegmentRegister")
    }

    public static func setDefaultSegmentRegisterForAll(registerIndex: Int32, value: UInt64) throws(IDAError) {
        try requireRuntimeThread("Segments.setDefaultSegmentRegisterForAll")
        try checkStatus(idax_segment_set_default_segment_register_for_all(registerIndex, value), "Segments.setDefaultSegmentRegisterForAll")
    }

    public static func registers() throws(IDAError) -> [Segments.RegisterDescriptor] {
        try requireRuntimeThread("Segments.registers")
        var out: UnsafeMutablePointer<IdaxSegmentRegisterDescriptor>?
        var count: Int = 0
        defer { idax_segment_register_descriptors_free(out, count) }
        try checkStatus(idax_segment_registers(&out, &count), "Segments.registers")
        return try copyNativeValues(out, count: count, "Segments.registers") { (value) throws(IDAError) -> Segments.RegisterDescriptor in try Segments.RegisterDescriptor(copying: value, "Segments.registers") }
    }

    public static func registerValue(address: UInt64, registerName: String) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Segments.registerValue")
        try validateCString(registerName, "Segments.registerValue")
        var has_value: Int32 = 0
        var out: UInt64 = 0
        try checkStatus(registerName.withCString { c_register_name in idax_segment_register_value(address, c_register_name, &has_value, &out)}, "Segments.registerValue")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func defaultRegisterValue(address: UInt64, registerName: String) throws(IDAError) -> UInt64? {
        try requireRuntimeThread("Segments.defaultRegisterValue")
        try validateCString(registerName, "Segments.defaultRegisterValue")
        var has_value: Int32 = 0
        var out: UInt64 = 0
        try checkStatus(registerName.withCString { c_register_name in idax_segment_default_register_value(address, c_register_name, &has_value, &out)}, "Segments.defaultRegisterValue")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func registerRange(address: UInt64, registerName: String) throws(IDAError) -> Segments.RegisterRange {
        try requireRuntimeThread("Segments.registerRange")
        try validateCString(registerName, "Segments.registerRange")
        var out = IdaxSegmentRegisterRange()
        try checkStatus(registerName.withCString { c_register_name in idax_segment_register_range(address, c_register_name, &out)}, "Segments.registerRange")
        return try Segments.RegisterRange(copying: out, "Segments.registerRange")
    }

    public static func previousRegisterRange(address: UInt64, registerName: String) throws(IDAError) -> Segments.RegisterRange? {
        try requireRuntimeThread("Segments.previousRegisterRange")
        try validateCString(registerName, "Segments.previousRegisterRange")
        var out = IdaxSegmentRegisterRange()
        var has_value: Int32 = 0
        try checkStatus(registerName.withCString { c_register_name in idax_segment_previous_register_range(address, c_register_name, &out, &has_value)}, "Segments.previousRegisterRange")
        guard has_value != 0 else { return nil }
        return try Segments.RegisterRange(copying: out, "Segments.previousRegisterRange")
    }

    public static func registerRanges(registerName: String) throws(IDAError) -> [Segments.RegisterRange] {
        try requireRuntimeThread("Segments.registerRanges")
        try validateCString(registerName, "Segments.registerRanges")
        var out: UnsafeMutablePointer<IdaxSegmentRegisterRange>?
        var count: Int = 0
        defer { idax_segment_register_ranges_free(out) }
        try checkStatus(registerName.withCString { c_register_name in idax_segment_register_ranges(c_register_name, &out, &count)}, "Segments.registerRanges")
        return try copyNativeValues(out, count: count, "Segments.registerRanges") { (value) throws(IDAError) -> Segments.RegisterRange in try Segments.RegisterRange(copying: value, "Segments.registerRanges") }
    }

    public static func registerRangeIndex(address: UInt64, registerName: String) throws(IDAError) -> Int? {
        try requireRuntimeThread("Segments.registerRangeIndex")
        try validateCString(registerName, "Segments.registerRangeIndex")
        var out: Int = 0
        var has_value: Int32 = 0
        try checkStatus(registerName.withCString { c_register_name in idax_segment_register_range_index(address, c_register_name, &out, &has_value)}, "Segments.registerRangeIndex")
        guard has_value != 0 else { return nil }
        return out
    }

    public static func removeRegisterRange(address: UInt64, registerName: String) throws(IDAError) {
        try requireRuntimeThread("Segments.removeRegisterRange")
        try validateCString(registerName, "Segments.removeRegisterRange")
        try checkStatus(registerName.withCString { c_register_name in idax_segment_remove_register_range(address, c_register_name)}, "Segments.removeRegisterRange")
    }

    public static func copyRegisterRanges(destinationRegister: String, sourceRegister: String, mapSelectorsToAddresses: Bool = false) throws(IDAError) {
        try requireRuntimeThread("Segments.copyRegisterRanges")
        try validateCString(destinationRegister, "Segments.copyRegisterRanges")
        try validateCString(sourceRegister, "Segments.copyRegisterRanges")
        try checkStatus(destinationRegister.withCString { c_destination_register in sourceRegister.withCString { c_source_register in idax_segment_copy_register_ranges(c_destination_register, c_source_register, (mapSelectorsToAddresses ? 1 : 0))}}, "Segments.copyRegisterRanges")
    }
}
