// Generated by scripts/generate_values.py from value_schema.json.
// Edit the semantic schema or add a hand-written adapter; do not edit this file.
internal import CIDAX

public enum Undo {
    public static func createPoint(actionName: String, label: String) throws(IDAError) -> Bool {
        try requireRuntimeThread("Undo.createPoint")
        try validateCString(actionName, "Undo.createPoint")
        try validateCString(label, "Undo.createPoint")
        var out: Int32 = 0
        try checkStatus(actionName.withCString { c_action_name in label.withCString { c_label in idax_undo_create_point(c_action_name, c_label, &out)}}, "Undo.createPoint")
        return out != 0
    }

    public static func undoActionLabel() throws(IDAError) -> String? {
        try requireRuntimeThread("Undo.undoActionLabel")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_undo_undo_action_label(&out), "Undo.undoActionLabel")
        return out == nil ? nil : (try borrowCString(out.map { UnsafePointer($0) }, "Undo.undoActionLabel"))
    }

    public static func redoActionLabel() throws(IDAError) -> String? {
        try requireRuntimeThread("Undo.redoActionLabel")
        var out: UnsafeMutablePointer<CChar>?
        defer { idax_free_string(out) }
        try checkStatus(idax_undo_redo_action_label(&out), "Undo.redoActionLabel")
        return out == nil ? nil : (try borrowCString(out.map { UnsafePointer($0) }, "Undo.redoActionLabel"))
    }

    public static func performUndo() throws(IDAError) -> Bool {
        try requireRuntimeThread("Undo.performUndo")
        var out: Int32 = 0
        try checkStatus(idax_undo_perform_undo(&out), "Undo.performUndo")
        return out != 0
    }

    public static func performRedo() throws(IDAError) -> Bool {
        try requireRuntimeThread("Undo.performRedo")
        var out: Int32 = 0
        try checkStatus(idax_undo_perform_redo(&out), "Undo.performRedo")
        return out != 0
    }
}
