internal import CIDA

/// Demangling output form.
public enum DemangledForm: Int32, Sendable {
    case short = 0
    case long = 1
    case typeOnly = 2
}

/// Naming and demangling operations.
///
/// Mirrors C++ `ida::name`.
public enum Name {
    public static func get(at address: Address) throws(IDAError) -> String {
        try withStringOutput("name.get") { idax_name_get(address, $0) }
    }

    public static func set(_ name: String, at address: Address) throws(IDAError) {
        try checkStatus(name.withCString { idax_name_set(address, $0) }, "name.set")
    }

    public static func forceSet(_ name: String, at address: Address) throws(IDAError) {
        try checkStatus(name.withCString { idax_name_force_set(address, $0) }, "name.forceSet")
    }

    public static func remove(at address: Address) throws(IDAError) {
        try checkStatus(idax_name_remove(address), "name.remove")
    }

    public static func demangled(at address: Address, form: DemangledForm = .short) throws(IDAError) -> String {
        try withStringOutput("name.demangled") { idax_name_demangled(address, form.rawValue, $0) }
    }

    public static func resolve(_ name: String, context: Address = 0) throws(IDAError) -> Address {
        try withOutput("name.resolve", UInt64(0)) { out in
            name.withCString { idax_name_resolve($0, context, out) }
        }
    }

    // MARK: - Predicates

    public static func isPublic(_ address: Address) -> Bool {
        idax_name_is_public(address) != 0
    }

    public static func isWeak(_ address: Address) -> Bool {
        idax_name_is_weak(address) != 0
    }

    public static func isUserDefined(_ address: Address) -> Bool {
        idax_name_is_user_defined(address) != 0
    }

    public static func isAutoGenerated(_ address: Address) -> Bool {
        idax_name_is_auto_generated(address) != 0
    }

    public static func setPublic(_ value: Bool, at address: Address) throws(IDAError) {
        try checkStatus(idax_name_set_public(address, value ? 1 : 0), "name.setPublic")
    }

    public static func setWeak(_ value: Bool, at address: Address) throws(IDAError) {
        try checkStatus(idax_name_set_weak(address, value ? 1 : 0), "name.setWeak")
    }

    // MARK: - Enumeration

    public static func allUserDefined(start: Address, end: Address) throws(IDAError) -> [NameEntry] {
        var ptr: UnsafeMutablePointer<IdaxNameEntry>? = nil
        var count: Int = 0
        try checkStatus(idax_name_all_user_defined(start, end, &ptr, &count), "name.allUserDefined")
        defer { idax_name_entries_free(ptr, count) }
        guard let ptr, count > 0 else { return [] }
        let buf = UnsafeBufferPointer(start: ptr, count: count)
        return buf.map { raw in
            NameEntry(
                address: raw.address,
                name: borrowCString(raw.name),
                isUserDefined: raw.user_defined != 0,
                isAutoGenerated: raw.auto_generated != 0
            )
        }
    }

    // MARK: - Validation

    public static func isValidIdentifier(_ text: String) throws(IDAError) -> Bool {
        let result = try withOutput("name.isValidIdentifier", Int32(0)) { out in
            text.withCString { idax_name_is_valid_identifier($0, out) }
        }
        return result != 0
    }

    public static func sanitizeIdentifier(_ text: String) throws(IDAError) -> String {
        try withStringOutput("name.sanitizeIdentifier") { out in
            text.withCString { idax_name_sanitize_identifier($0, out) }
        }
    }
}

/// Named address entry from user-defined name enumeration.
public struct NameEntry: Sendable {
    public let address: Address
    public let name: String
    public let isUserDefined: Bool
    public let isAutoGenerated: Bool
}
