import CIDA

/// Demangling output form.
public enum DemangledForm: Int32, Sendable {
    case short = 0
    case long = 1
    case typeOnly = 2
}

/// Naming and demangling operations.
///
/// Mirrors C++ `ida::name`.
public enum Name {
    public static func get(at address: Address) throws(IDAError) -> String {
        try withStringOutput("name.get") { idax_name_get(address, $0) }
    }

    public static func set(_ name: String, at address: Address) throws(IDAError) {
        try checkStatus(name.withCString { idax_name_set(address, $0) }, "name.set")
    }

    public static func forceSet(_ name: String, at address: Address) throws(IDAError) {
        try checkStatus(name.withCString { idax_name_force_set(address, $0) }, "name.forceSet")
    }

    public static func remove(at address: Address) throws(IDAError) {
        try checkStatus(idax_name_remove(address), "name.remove")
    }

    public static func demangled(at address: Address, form: DemangledForm = .short) throws(IDAError) -> String {
        try withStringOutput("name.demangled") { idax_name_demangled(address, form.rawValue, $0) }
    }

    public static func resolve(_ name: String, context: Address = 0) throws(IDAError) -> Address {
        try withOutput("name.resolve", UInt64(0)) { out in
            name.withCString { idax_name_resolve($0, context, out) }
        }
    }

    // MARK: - Predicates

    public static func isPublic(_ address: Address) -> Bool {
        idax_name_is_public(address) != 0
    }

    public static func isWeak(_ address: Address) -> Bool {
        idax_name_is_weak(address) != 0
    }

    public static func isUserDefined(_ address: Address) -> Bool {
        idax_name_is_user_defined(address) != 0
    }

    public static func isAutoGenerated(_ address: Address) -> Bool {
        idax_name_is_auto_generated(address) != 0
    }

    public static func setPublic(_ value: Bool, at address: Address) throws(IDAError) {
        try checkStatus(idax_name_set_public(address, value ? 1 : 0), "name.setPublic")
    }

    public static func setWeak(_ value: Bool, at address: Address) throws(IDAError) {
        try checkStatus(idax_name_set_weak(address, value ? 1 : 0), "name.setWeak")
    }
}
