import CIDAX
import Foundation
import XCTest
@testable import IDAX

final class ValueDomainTests: XCTestCase {
    func testRangeBoundsAndTypedDiscriminants() {
        let range = Addresses.Range(start: 8, end: 12)
        XCTAssertEqual(range.size, 4)
        XCTAssertTrue(range.contains(8))
        XCTAssertFalse(range.contains(12))
        XCTAssertEqual(Addresses.Range(start: 12, end: 8).size, 0)
        XCTAssertTrue(Addresses.Range(start: .max, end: .max).isEmpty)
        XCTAssertEqual(Database.processorIdFromRaw(0), .intelX86)
        XCTAssertNil(Database.processorIdFromRaw(.max))
        XCTAssertTrue(CrossReferences.isCall(.callNear))
        XCTAssertFalse(CrossReferences.isCall(.jumpNear))
        XCTAssertTrue(CrossReferences.isData(.informational))
        XCTAssertFalse(CrossReferences.isData(.unknown))
        XCTAssertEqual(Names.ListOptions().start, badAddress)
        XCTAssertTrue(Names.ListOptions().includeAutoGenerated)
        XCTAssertEqual(Bookmarks.maxSlots, 1024)
        XCTAssertEqual(Instructions.OperandEnum(name: "Flags").serial, 0)
        var source = Lines.SourceFile(filename: "source.c", range: range)
        XCTAssertEqual(source.range, range)
        source.range = .init(start: 16, end: 24)
        XCTAssertEqual(source.start, 16)
        XCTAssertEqual(source.end, 24)
    }

    func testOperandAbsenceAndSignedDisplacementSurviveNativeCopy() throws {
        var native = IdaxOperand()
        native.type = Instructions.OperandType.memoryDisplacement.rawValue
        native.value = .max
        native.encoded_value_byte_offset = -1
        native.secondary_encoded_value_byte_offset = 0
        let operand = try "rax".withCString { pointer in
            native.register_name = UnsafeMutablePointer(mutating: pointer)
            return try Instructions.Operand(copying: native, "operand test")
        }
        XCTAssertNil(operand.encodedValueByteOffset)
        XCTAssertEqual(operand.secondaryEncodedValueByteOffset, 0)
        XCTAssertEqual(operand.displacement, -1)
        XCTAssertTrue(operand.isMemory)
        XCTAssertFalse(operand.isRegister)
        let instruction = Instructions.Instruction(address: 0, size: 4, opcode: 0,
            mnemonic: "test", operands: [operand], branchCondition: .equal)
        XCTAssertEqual(instruction.operandCount, 1)
        XCTAssertEqual(try instruction.operand(index: 0), operand)
        XCTAssertThrowsError(try instruction.operand(index: -1))
        XCTAssertThrowsError(try instruction.operand(index: 1))
    }

    func testLuminaResultCopiesEveryPerFunctionCode() throws {
        var codes: [Int32] = [-3, -2, -1, 0, 1]
        let result = try codes.withUnsafeMutableBufferPointer { buffer in
            var native = IdaxSwiftLuminaBatchResult()
            native.requested = 7
            native.completed = 5
            native.succeeded = 2
            native.failed = 3
            native.codes = buffer.baseAddress
            native.code_count = buffer.count
            return try Lumina.BatchResult(copying: native, "Lumina copy")
        }
        codes[0] = 0
        XCTAssertEqual(result.requested, 7)
        XCTAssertEqual(result.codes, [.badPattern, .notFound, .error, .ok, .added])
        var malformed = IdaxSwiftLuminaBatchResult()
        malformed.code_count = 1
        XCTAssertThrowsError(try Lumina.BatchResult(copying: malformed, "malformed Lumina result"))
        let base = IDAError(category: .validation, code: 9, message: "message", context: "origin")
        XCTAssertEqual(Diagnostics.enrich(base, contextSuffix: "detail").context, "origin | detail")
        XCTAssertEqual(Diagnostics.enrich(base, contextSuffix: "detail").code, 9)
    }

    func testProcessorABINamePreservesAbsentAndEmptyValues() throws {
        var native = IdaxDatabaseProcessorProfile()
        try "metapc".withCString { name in
            native.name = UnsafeMutablePointer(mutating: name)
            let absent = try Database.ProcessorProfile(copying: native, "ABI absence")
            XCTAssertNil(absent.abiName)
            try "".withCString { abi in
                native.abi_name = UnsafeMutablePointer(mutating: abi)
                let empty = try Database.ProcessorProfile(copying: native, "ABI empty")
                XCTAssertEqual(empty.abiName, "")
            }
        }
    }

    func testOfflineDyldInventoryOwnsPathsAndRejectsIncompleteTables() throws {
        XCTAssertFalse(Runtime.isInitialized)
        let file = FileManager.default.temporaryDirectory.appendingPathComponent("idax-swift-dyld-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: file) }
        var bytes = [UInt8](repeating: 0, count: 0x400)
        func put(_ offset: Int, _ value: UInt64, width: Int = 4) {
            for index in 0..<width { bytes[offset + index] = UInt8(truncatingIfNeeded: value >> (8 * index)) }
        }
        func string(_ offset: Int, _ value: String) {
            let encoded = Array(value.utf8) + [0]
            bytes.replaceSubrange(offset..<(offset + encoded.count), with: encoded)
        }
        string(0, "dyld_v1  arm64e")
        put(0x10, 0x1c8)
        put(0x1c0, 0x200)
        put(0x1c4, 2)
        put(0x18, 0x280) // Obsolete table must not replace the modern table.
        put(0x1c, 1)
        put(0x200, 0x123456789abcdef0, width: 8)
        put(0x218, 0x300)
        put(0x220, 0xfedcba9876543210, width: 8)
        put(0x238, 0x330)
        string(0x300, "/usr/lib/alpha.dylib")
        string(0x330, "/usr/lib/beta.dylib")
        try Foundation.Data(bytes).write(to: file)
        let modules = try DyldCache.listModules(cachePath: file.path)
        XCTAssertEqual(modules.map(\.path), ["/usr/lib/alpha.dylib", "/usr/lib/beta.dylib"])
        XCTAssertEqual(modules.map(\.loadAddress), [0x123456789abcdef0, 0xfedcba9876543210])
        XCTAssertThrowsError(try DyldCache.listModules(cachePath: file.path + "\0suffix")) { error in
            XCTAssertEqual((error as? IDAError)?.category, .validation)
        }
        put(0x238, 0x400)
        try Foundation.Data(bytes).write(to: file)
        XCTAssertThrowsError(try DyldCache.listModules(cachePath: file.path))
        XCTAssertEqual(modules[1].path, "/usr/lib/beta.dylib")
        XCTAssertFalse(Runtime.isInitialized)
    }
}
