from collections.abc import Iterator
from enum import Enum

class Range:
    start: int
    end: int
    def __init__(self, start: int = ..., end: int = ...) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def empty(self) -> bool: ...
    def contains(self, address: int) -> bool: ...
    def __contains__(self, address: object) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

class Predicate(Enum):
    MAPPED = ...
    LOADED = ...
    CODE = ...
    DATA = ...
    UNKNOWN = ...
    HEAD = ...
    TAIL = ...

class ItemRange:
    def __iter__(self) -> Iterator[int]: ...

class PredicateRange:
    def __iter__(self) -> Iterator[int]: ...

def item_start(address: int) -> int: ...
def item_end(address: int) -> int: ...
def item_size(address: int) -> int: ...
def next_head(address: int, limit: int = ...) -> int: ...
def prev_head(address: int, limit: int = ...) -> int: ...
def next_defined(address: int, limit: int = ...) -> int: ...
def prev_defined(address: int, limit: int = ...) -> int: ...
def next_not_tail(address: int) -> int: ...
def prev_not_tail(address: int) -> int: ...
def next_mapped(address: int) -> int: ...
def prev_mapped(address: int) -> int: ...
def is_mapped(address: int) -> bool: ...
def is_loaded(address: int) -> bool: ...
def is_code(address: int) -> bool: ...
def is_data(address: int) -> bool: ...
def is_unknown(address: int) -> bool: ...
def is_head(address: int) -> bool: ...
def is_tail(address: int) -> bool: ...
def find_first(start: int, end: int, predicate: Predicate) -> int: ...
def find_next(address: int, predicate: Predicate, end: int = ...) -> int: ...
def items(start: int, end: int) -> ItemRange: ...
def code_items(start: int, end: int) -> PredicateRange: ...
def data_items(start: int, end: int) -> PredicateRange: ...
def unknown_bytes(start: int, end: int) -> PredicateRange: ...
