def is_enabled() -> bool: ...
def set_enabled(enabled: bool) -> None: ...
def is_idle() -> bool: ...
def wait() -> None: ...
def wait_range(start: int, end: int) -> None: ...
def schedule(address: int) -> None: ...
def schedule_range(start: int, end: int) -> None: ...
def schedule_code(address: int) -> None: ...
def schedule_function(address: int) -> None: ...
def schedule_reanalysis(address: int) -> None: ...
def schedule_reanalysis_range(start: int, end: int) -> None: ...
def cancel(start: int, end: int) -> None: ...
def revert_decisions(start: int, end: int) -> None: ...
