from typing import Final

MAX_SLOTS: Final[int]

class Bookmark:
    @property
    def address(self) -> int: ...
    @property
    def slot(self) -> int: ...
    @property
    def description(self) -> str: ...

def all() -> list[Bookmark]: ...
def at(address: int) -> Bookmark | None: ...
def at_slot(slot: int) -> Bookmark | None: ...
def set(address: int, description: str, slot: int | None = ...) -> Bookmark: ...
def remove(address: int) -> bool: ...
def remove_slot(slot: int) -> bool: ...
