def get(address: int, repeatable: bool = ...) -> str: ...
def set(address: int, text: str, repeatable: bool = ...) -> None: ...
def append(address: int, text: str, repeatable: bool = ...) -> None: ...
def remove(address: int, repeatable: bool = ...) -> None: ...
def add_anterior(address: int, text: str) -> None: ...
def add_posterior(address: int, text: str) -> None: ...
def get_anterior(address: int, line_index: int) -> str: ...
def get_posterior(address: int, line_index: int) -> str: ...
def set_anterior(address: int, line_index: int, text: str) -> None: ...
def set_posterior(address: int, line_index: int, text: str) -> None: ...
def remove_anterior_line(address: int, line_index: int) -> None: ...
def remove_posterior_line(address: int, line_index: int) -> None: ...
def set_anterior_lines(address: int, lines: list[str]) -> None: ...
def set_posterior_lines(address: int, lines: list[str]) -> None: ...
def clear_anterior(address: int) -> None: ...
def clear_posterior(address: int) -> None: ...
def anterior_lines(address: int) -> list[str]: ...
def posterior_lines(address: int) -> list[str]: ...
def render(address: int, include_repeatable: bool = ...,
           include_extra_lines: bool = ...) -> str: ...
