from collections.abc import Callable
from enum import Enum
from typing import TypeAlias
from .type import TypeInfo

Buffer: TypeAlias = bytes | bytearray | memoryview

class TypedValueKind(Enum):
    UNSIGNED_INTEGER = ...
    SIGNED_INTEGER = ...
    FLOATING_POINT = ...
    POINTER = ...
    STRING = ...
    BYTES = ...
    ARRAY = ...

class TypedValue:
    kind: TypedValueKind
    unsigned_value: int
    signed_value: int
    floating_value: float
    pointer_value: int
    string_value: str
    bytes: bytes
    elements: list[TypedValue]
    def __init__(self) -> None: ...

class StringListOptions:
    string_types: list[int]
    minimum_length: int
    only_7bit: bool
    ignore_instructions: bool
    display_only_existing_strings: bool
    def __init__(self) -> None: ...

class StringLiteral:
    address: int
    byte_length: int
    string_type: int
    text: str
    def __init__(self) -> None: ...

class CustomDataTypeId:
    value: int
    def __init__(self, value: int = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class CustomDataFormatId:
    value: int
    def __init__(self, value: int = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class CustomDataFormatContext:
    address: int
    operand_index: int
    type_id: CustomDataTypeId
    def __init__(self) -> None: ...

class CustomDataTypeDefinition:
    name: str
    menu_name: str
    hotkey: str
    assembler_keyword: str
    value_size: int
    allow_duplicates: bool
    may_create_at: Callable[[int, int], bool] | None
    calculate_size: Callable[[int, int], int] | None
    def __init__(self) -> None: ...

class CustomDataTypeInfo:
    id: CustomDataTypeId
    name: str
    menu_name: str
    hotkey: str
    assembler_keyword: str
    value_size: int
    allow_duplicates: bool
    visible_in_menu: bool
    has_creation_filter: bool
    variable_size: bool
    def __init__(self) -> None: ...

class CustomDataFormatDefinition:
    name: str
    menu_name: str
    hotkey: str
    value_size: int
    text_width: int
    render: Callable[[bytes, CustomDataFormatContext], str] | None
    scan: Callable[[str, CustomDataFormatContext], Buffer] | None
    analyze: Callable[[CustomDataFormatContext], None] | None
    def __init__(self) -> None: ...

class CustomDataFormatInfo:
    id: CustomDataFormatId
    name: str
    menu_name: str
    hotkey: str
    value_size: int
    text_width: int
    visible_in_menu: bool
    can_render: bool
    can_scan: bool
    can_analyze: bool
    def __init__(self) -> None: ...

class CustomDataItemInfo:
    type_id: CustomDataTypeId
    format_id: CustomDataFormatId
    byte_length: int
    def __init__(self) -> None: ...

def read_byte(address: int) -> int: ...
def read_word(address: int) -> int: ...
def read_dword(address: int) -> int: ...
def read_qword(address: int) -> int: ...
def read_bytes(address: int, count: int) -> bytes: ...
def read_string(address: int, max_length: int = ..., string_type: int = ...,
                conversion_flags: int = ...) -> str: ...
def string_list_options() -> StringListOptions: ...
def configure_string_list(options: StringListOptions) -> None: ...
def rebuild_string_list() -> None: ...
def clear_string_list() -> None: ...
def string_literals(rebuild: bool = ...) -> list[StringLiteral]: ...
def read_typed(address: int, type: TypeInfo) -> TypedValue: ...

def write_byte(address: int, value: int) -> None: ...
def write_word(address: int, value: int) -> None: ...
def write_dword(address: int, value: int) -> None: ...
def write_qword(address: int, value: int) -> None: ...
def write_bytes(address: int, data: Buffer) -> None: ...
def write_typed(address: int, type: TypeInfo, value: TypedValue) -> None: ...
def patch_byte(address: int, value: int) -> None: ...
def patch_word(address: int, value: int) -> None: ...
def patch_dword(address: int, value: int) -> None: ...
def patch_qword(address: int, value: int) -> None: ...
def patch_bytes(address: int, data: Buffer) -> None: ...
def revert_patch(address: int) -> None: ...
def revert_patches(address: int, count: int) -> int: ...
def original_byte(address: int) -> int: ...
def original_word(address: int) -> int: ...
def original_dword(address: int) -> int: ...
def original_qword(address: int) -> int: ...

def define_byte(address: int, count: int = ...) -> None: ...
def define_word(address: int, count: int = ...) -> None: ...
def define_dword(address: int, count: int = ...) -> None: ...
def define_qword(address: int, count: int = ...) -> None: ...
def define_oword(address: int, count: int = ...) -> None: ...
def define_yword(address: int, count: int = ...) -> None: ...
def define_zword(address: int, count: int = ...) -> None: ...
def tbyte_element_size() -> int: ...
def define_tbyte(address: int, count: int = ...) -> None: ...
def packed_real_element_size() -> int: ...
def define_packed_real(address: int, count: int = ...) -> None: ...
def define_float(address: int, count: int = ...) -> None: ...
def define_double(address: int, count: int = ...) -> None: ...
def define_string(address: int, length: int, string_type: int = ...) -> None: ...
def define_struct(address: int, length: int, structure_id: int) -> None: ...

def register_custom_data_type(definition: CustomDataTypeDefinition) -> CustomDataTypeId: ...
def unregister_custom_data_type(type_id: CustomDataTypeId) -> None: ...
def custom_data_type(type_id: CustomDataTypeId) -> CustomDataTypeInfo: ...
def find_custom_data_type(name: str) -> CustomDataTypeId: ...
def custom_data_types(minimum_size: int = ...,
                      maximum_size: int = ...) -> list[CustomDataTypeInfo]: ...
def register_custom_data_format(definition: CustomDataFormatDefinition) -> CustomDataFormatId: ...
def unregister_custom_data_format(format_id: CustomDataFormatId) -> None: ...
def custom_data_format(format_id: CustomDataFormatId) -> CustomDataFormatInfo: ...
def find_custom_data_format(name: str) -> CustomDataFormatId: ...
def custom_data_formats(type_id: CustomDataTypeId) -> list[CustomDataFormatInfo]: ...
def standard_custom_data_formats() -> list[CustomDataFormatInfo]: ...
def attach_custom_data_format(type_id: CustomDataTypeId,
                              format_id: CustomDataFormatId) -> None: ...
def detach_custom_data_format(type_id: CustomDataTypeId,
                              format_id: CustomDataFormatId) -> None: ...
def is_custom_data_format_attached(type_id: CustomDataTypeId,
                                   format_id: CustomDataFormatId) -> bool: ...
def attach_custom_data_format_to_standard_types(format_id: CustomDataFormatId) -> None: ...
def detach_custom_data_format_from_standard_types(format_id: CustomDataFormatId) -> None: ...
def is_custom_data_format_attached_to_standard_types(format_id: CustomDataFormatId) -> bool: ...
def custom_data_item_size(type_id: CustomDataTypeId, address: int,
                          maximum_size: int) -> int: ...
def define_custom(address: int, byte_length: int, type_id: CustomDataTypeId,
                  format_id: CustomDataFormatId) -> None: ...
def define_custom_inferred(address: int, type_id: CustomDataTypeId,
                           format_id: CustomDataFormatId,
                           maximum_size: int) -> None: ...
def custom_data_at(address: int) -> CustomDataItemInfo: ...
def render_custom_data(format_id: CustomDataFormatId, value: Buffer,
                       context: CustomDataFormatContext = ...) -> str: ...
def scan_custom_data(format_id: CustomDataFormatId, text: str,
                     context: CustomDataFormatContext = ...) -> bytes: ...
def analyze_custom_data(format_id: CustomDataFormatId,
                        context: CustomDataFormatContext = ...) -> None: ...
def undefine(address: int, count: int = ...) -> None: ...
def find_binary_pattern(start: int, end: int, pattern: str,
                        forward: bool = ..., skip_start: bool = ...,
                        case_sensitive: bool = ..., radix: int = ...,
                        string_literals_encoding: int = ...) -> int: ...
