from enum import Enum
from os import PathLike
from types import TracebackType
from typing import overload
from .address import Range

_Path = str | bytes | PathLike[str] | PathLike[bytes]
_Buffer = bytes | bytearray | memoryview

class OpenMode(Enum):
    ANALYZE = ...
    SKIP_ANALYSIS = ...

class LoadIntent(Enum):
    AUTO_DETECT = ...
    BINARY = ...
    NON_BINARY = ...

class ProcessorId(Enum):
    INTEL_X86 = ...
    Z80 = ...
    INTEL_I860 = ...
    INTEL_8051 = ...
    TMS320_C5X = ...
    MOS_6502 = ...
    PDP11 = ...
    MOTOROLA_68K = ...
    JAVA_VM = ...
    MOTOROLA_6800 = ...
    ST7 = ...
    MOTOROLA_68HC12 = ...
    MIPS = ...
    ARM = ...
    TMS320_C6X = ...
    POWER_PC = ...
    INTEL_80196 = ...
    Z8 = ...
    SUPER_H = ...
    DOT_NET = ...
    AVR = ...
    H8 = ...
    PIC = ...
    SPARC = ...
    ALPHA = ...
    HPPA = ...
    H8500 = ...
    TRI_CORE = ...
    DSP56K = ...
    C166 = ...
    ST20 = ...
    IA64 = ...
    INTEL_I960 = ...
    F2MC16 = ...
    TMS320_C54X = ...
    TMS320_C55X = ...
    TRIMEDIA = ...
    M32R = ...
    NEC_78K0 = ...
    NEC_78K0S = ...
    MITSUBISHI_M740 = ...
    MITSUBISHI_M7700 = ...
    ST9 = ...
    FUJITSU_FR = ...
    MOTOROLA_68HC16 = ...
    MITSUBISHI_M7900 = ...
    TMS320_C3 = ...
    KR1878 = ...
    ADSP_218X = ...
    OAK_DSP = ...
    TLCS900 = ...
    ROCKWELL_C39 = ...
    CR16 = ...
    MN10200 = ...
    TMS320_C1X = ...
    NEC_V850X = ...
    SCRIPT_ADAPTER = ...
    EFI_BYTECODE = ...
    MSP430 = ...
    SPU = ...
    DALVIK = ...
    WDC_65C816 = ...
    M16C = ...
    ARC = ...
    UNSP = ...
    TMS320_C28X = ...
    DSP96000 = ...
    SPC700 = ...
    ADSP_2106X = ...
    PIC16 = ...
    S390 = ...
    XTENSA = ...
    RISC_V = ...
    RL78 = ...
    RX = ...
    WASM = ...
    NDS32 = ...
    MCORE = ...

class PluginLoadPolicy:
    disable_user_plugins: bool
    allowlist_patterns: list[str]
    def __init__(self, disable_user_plugins: bool = ...,
                 allowlist_patterns: list[str] = ...) -> None: ...

class RuntimeOptions:
    quiet: bool
    plugin_policy: PluginLoadPolicy
    def __init__(self, quiet: bool = ...,
                 plugin_policy: PluginLoadPolicy = ...) -> None: ...

class CompilerInfo:
    id: int
    uncertain: bool
    name: str
    abbreviation: str
    def __init__(self) -> None: ...

class ImportSymbol:
    address: int
    name: str
    ordinal: int
    def __init__(self) -> None: ...

class ImportModule:
    index: int
    name: str
    symbols: list[ImportSymbol]
    def __init__(self) -> None: ...

class ProcessorProfile:
    raw_id: int
    known_id: ProcessorId | None
    name: str
    address_bitness: int
    big_endian: bool
    abi_name: str | None
    def __init__(self) -> None: ...

class Snapshot:
    id: int
    flags: int
    description: str
    filename: str
    children: list[Snapshot]
    def __init__(self) -> None: ...

def processor_id_from_raw(raw_id: int) -> ProcessorId | None: ...
def init(argv: list[str] | tuple[str, ...] | None = ...,
         options: RuntimeOptions | None = ...) -> None: ...
@overload
def open(path: _Path, mode: bool,
         intent: LoadIntent = ...) -> None: ...
@overload
def open(path: _Path, mode: OpenMode = ...,
         intent: LoadIntent = ...) -> None: ...
def open_binary(path: _Path, mode: OpenMode = ...) -> None: ...
def open_non_binary(path: _Path, mode: OpenMode = ...) -> None: ...
def save() -> None: ...
def close(save: bool = ...) -> None: ...
def file_to_database(file_path: _Path, file_offset: int, address: int,
                     size: int, patchable: bool = ...,
                     remote: bool = ...) -> None: ...
def memory_to_database(data: _Buffer, address: int,
                       file_offset: int = ...) -> None: ...
def input_file_path() -> str: ...
def idb_path() -> str: ...
def file_type_name() -> str: ...
def loader_format_name() -> str: ...
def input_md5() -> str: ...
def compiler_info() -> CompilerInfo: ...
def import_modules() -> list[ImportModule]: ...
def image_base() -> int: ...
def min_address() -> int: ...
def max_address() -> int: ...
def address_bounds() -> Range: ...
def address_span() -> int: ...
def processor_id() -> int: ...
def processor() -> ProcessorId: ...
def processor_name() -> str: ...
def address_bitness() -> int: ...
def set_address_bitness(bits: int) -> None: ...
def is_big_endian() -> bool: ...
def abi_name() -> str: ...
def processor_profile() -> ProcessorProfile: ...
def snapshots() -> list[Snapshot]: ...
def set_snapshot_description(description: str) -> None: ...
def is_snapshot_database() -> bool: ...

class DatabaseSession:
    def __init__(self, path: _Path, *, mode: OpenMode | bool = ...,
                 intent: LoadIntent = ..., save_on_exit: bool = ...,
                 save_on_error: bool = ...) -> None: ...
    @property
    def is_open(self) -> bool: ...
    def __enter__(self) -> DatabaseSession: ...
    def close(self, *, save: bool | None = ...) -> None: ...
    def __exit__(self, exception_type: type[BaseException] | None,
                 exception: BaseException | None,
                 traceback: TracebackType | None) -> bool: ...

def opened(path: _Path, *, mode: OpenMode | bool = ...,
           intent: LoadIntent = ..., save_on_exit: bool = ...,
           save_on_error: bool = ...) -> DatabaseSession: ...
