from collections.abc import Callable
from enum import Enum
from types import TracebackType
from typing import TypeAlias
from .type import TypeInfo

Buffer: TypeAlias = bytes | bytearray | memoryview
Token: TypeAlias = int

class ProcessState(Enum):
    NO_PROCESS = ...
    RUNNING = ...
    SUSPENDED = ...

class AppcallValueKind(Enum):
    SIGNED_INTEGER = ...
    UNSIGNED_INTEGER = ...
    FLOATING_POINT = ...
    STRING = ...
    ADDRESS = ...
    BOOLEAN = ...

class BreakpointChange(Enum):
    ADDED = ...
    REMOVED = ...
    CHANGED = ...

class BackendInfo:
    name: str
    display_name: str
    remote: bool
    supports_appcall: bool
    supports_attach: bool
    loaded: bool
    def __init__(self) -> None: ...

class ThreadInfo:
    id: int
    name: str
    is_current: bool
    def __init__(self) -> None: ...

class RegisterInfo:
    name: str
    read_only: bool
    instruction_pointer: bool
    stack_pointer: bool
    frame_pointer: bool
    may_contain_address: bool
    custom_format: bool
    def __init__(self) -> None: ...

class AppcallValue:
    kind: AppcallValueKind
    signed_value: int
    unsigned_value: int
    floating_value: float
    string_value: str
    address_value: int
    boolean_value: bool
    def __init__(self) -> None: ...

class AppcallOptions:
    thread_id: int | None
    manual: bool
    include_debug_event: bool
    timeout_milliseconds: int | None
    def __init__(self) -> None: ...

class AppcallRequest:
    function_address: int
    function_type: TypeInfo
    arguments: list[AppcallValue]
    options: AppcallOptions
    def __init__(self) -> None: ...

class AppcallResult:
    return_value: AppcallValue
    diagnostics: str
    def __init__(self) -> None: ...

class AppcallExecutor:
    def __init__(self) -> None: ...
    def execute(self, request: AppcallRequest) -> AppcallResult: ...

class ModuleInfo:
    name: str
    base: int
    size: int
    def __init__(self) -> None: ...

class ExceptionInfo:
    address: int
    code: int
    can_continue: bool
    message: str
    def __init__(self) -> None: ...

class ScopedSubscription:
    def __init__(self, token: Token) -> None: ...
    @property
    def token(self) -> Token: ...
    def close(self) -> None: ...
    def __enter__(self) -> ScopedSubscription: ...
    def __exit__(self, exception_type: type[BaseException] | None,
                 exception: BaseException | None,
                 traceback: TracebackType | None) -> bool: ...

def available_backends() -> list[BackendInfo]: ...
def current_backend() -> BackendInfo: ...
def load_backend(backend_name: str, use_remote: bool = ...) -> None: ...
def start(path: str = ..., args: str = ..., working_dir: str = ...) -> None: ...
def request_start(path: str = ..., args: str = ...,
                  working_dir: str = ...) -> None: ...
def attach(pid: int) -> None: ...
def request_attach(pid: int, event_id: int = ...) -> None: ...
def detach() -> None: ...
def terminate() -> None: ...
def suspend() -> None: ...
def resume() -> None: ...
def step_into() -> None: ...
def step_over() -> None: ...
def step_out() -> None: ...
def run_to(address: int) -> None: ...
def state() -> ProcessState: ...
def instruction_pointer() -> int: ...
def stack_pointer() -> int: ...
def register_value(register_name: str) -> int: ...
def set_register(register_name: str, value: int) -> None: ...
def add_breakpoint(address: int) -> None: ...
def remove_breakpoint(address: int) -> None: ...
def has_breakpoint(address: int) -> bool: ...
def read_memory(address: int, size: int) -> bytes: ...
def write_memory(address: int, data: Buffer) -> None: ...
def is_request_running() -> bool: ...
def run_requests() -> None: ...
def request_suspend() -> None: ...
def request_resume() -> None: ...
def request_step_into() -> None: ...
def request_step_over() -> None: ...
def request_step_out() -> None: ...
def request_run_to(address: int) -> None: ...
def thread_count() -> int: ...
def thread_id_at(index: int) -> int: ...
def thread_name_at(index: int) -> str: ...
def current_thread_id() -> int: ...
def threads() -> list[ThreadInfo]: ...
def select_thread(thread_id: int) -> None: ...
def request_select_thread(thread_id: int) -> None: ...
def suspend_thread(thread_id: int) -> None: ...
def request_suspend_thread(thread_id: int) -> None: ...
def resume_thread(thread_id: int) -> None: ...
def request_resume_thread(thread_id: int) -> None: ...
def register_info(register_name: str) -> RegisterInfo: ...
def is_integer_register(register_name: str) -> bool: ...
def is_floating_register(register_name: str) -> bool: ...
def is_custom_register(register_name: str) -> bool: ...
def appcall(request: AppcallRequest) -> AppcallResult: ...
def cleanup_appcall(thread_id: int | None = ...) -> None: ...
def register_executor(name: str, executor: AppcallExecutor) -> None: ...
def unregister_executor(name: str) -> None: ...
def appcall_with_executor(name: str, request: AppcallRequest) -> AppcallResult: ...
def on_process_started(callback: Callable[[ModuleInfo], None]) -> Token: ...
def on_process_exited(callback: Callable[[int], None]) -> Token: ...
def on_process_suspended(callback: Callable[[int], None]) -> Token: ...
def on_breakpoint_hit(callback: Callable[[int, int], None]) -> Token: ...
def on_trace(callback: Callable[[int, int], bool]) -> Token: ...
def on_exception(callback: Callable[[ExceptionInfo], None]) -> Token: ...
def on_thread_started(callback: Callable[[int, str], None]) -> Token: ...
def on_thread_exited(callback: Callable[[int, int], None]) -> Token: ...
def on_library_loaded(callback: Callable[[ModuleInfo], None]) -> Token: ...
def on_library_unloaded(callback: Callable[[str], None]) -> Token: ...
def on_breakpoint_changed(callback: Callable[[BreakpointChange, int], None]) -> Token: ...
def unsubscribe(token: Token) -> None: ...
