from collections.abc import Callable
from enum import Enum, IntFlag
from types import TracebackType
from typing import ClassVar, TypeAlias
from .instruction import Instruction
from .type import TypeInfo, UsedMemberOffsets

Token: TypeAlias = int
FilterToken: TypeAlias = int

class Maturity(Enum):
    ZERO = ...
    BUILT = ...
    TRANS1 = ...
    NICE = ...
    TRANS2 = ...
    CPA = ...
    TRANS3 = ...
    CASTED = ...
    FINAL = ...

class MicrocodeApplyResult(Enum):
    NOT_HANDLED = ...
    HANDLED = ...
    ERROR = ...

class MicrocodeOpcode(Enum):
    NO_OPERATION = ...
    MOVE = ...
    ADD = ...
    SUBTRACT = ...
    MULTIPLY = ...
    ZERO_EXTEND = ...
    LOAD_MEMORY = ...
    STORE_MEMORY = ...
    BITWISE_OR = ...
    BITWISE_AND = ...
    BITWISE_XOR = ...
    SHIFT_LEFT = ...
    SHIFT_RIGHT_LOGICAL = ...
    SHIFT_RIGHT_ARITHMETIC = ...
    FLOAT_ADD = ...
    FLOAT_SUB = ...
    FLOAT_MUL = ...
    FLOAT_DIV = ...
    INTEGER_TO_FLOAT = ...
    FLOAT_TO_FLOAT = ...
    SIGNED_EXTEND = ...
    CALL = ...
    INDIRECT_CALL = ...
    GOTO = ...
    INDIRECT_JUMP = ...
    RETURN = ...
    OTHER = ...

class MicrocodeOperandKind(Enum):
    EMPTY = ...
    REGISTER = ...
    LOCAL_VARIABLE = ...
    REGISTER_PAIR = ...
    GLOBAL_ADDRESS = ...
    STACK_VARIABLE = ...
    HELPER_REFERENCE = ...
    BLOCK_REFERENCE = ...
    NESTED_INSTRUCTION = ...
    UNSIGNED_IMMEDIATE = ...
    SIGNED_IMMEDIATE = ...
    ADDRESS_REFERENCE = ...
    CALL_ARGUMENTS = ...
    STRING_CONSTANT = ...
    FLOATING_POINT_CONSTANT = ...
    OTHER = ...

class MicrocodeMaturity(Enum):
    GENERATED = ...
    PREOPTIMIZED = ...
    LOCALLY_OPTIMIZED = ...
    CALLS_ANALYZED = ...
    GLOBALLY_OPTIMIZED1 = ...
    GLOBALLY_OPTIMIZED2 = ...
    GLOBALLY_OPTIMIZED3 = ...
    LOCAL_VARIABLES = ...

class MicrocodeInsertPolicy(Enum):
    TAIL = ...
    BEGINNING = ...
    BEFORE_TAIL = ...

class MicrocodeValueKind(Enum):
    REGISTER = ...
    LOCAL_VARIABLE = ...
    REGISTER_PAIR = ...
    GLOBAL_ADDRESS = ...
    STACK_VARIABLE = ...
    HELPER_REFERENCE = ...
    BLOCK_REFERENCE = ...
    NESTED_INSTRUCTION = ...
    UNSIGNED_IMMEDIATE = ...
    SIGNED_IMMEDIATE = ...
    FLOAT32_IMMEDIATE = ...
    FLOAT64_IMMEDIATE = ...
    BYTE_ARRAY = ...
    VECTOR = ...
    TYPE_DECLARATION_VIEW = ...

class MicrocodeValueLocationKind(Enum):
    UNSPECIFIED = ...
    REGISTER = ...
    REGISTER_WITH_OFFSET = ...
    REGISTER_PAIR = ...
    REGISTER_RELATIVE = ...
    STACK_OFFSET = ...
    STATIC_ADDRESS = ...
    SCATTERED = ...

class MicrocodeArgumentFlag(IntFlag):
    HIDDEN_ARGUMENT = ...
    RETURN_VALUE_POINTER = ...
    STRUCT_ARGUMENT = ...
    ARRAY_ARGUMENT = ...
    UNUSED_ARGUMENT = ...

class MicrocodeCallingConvention(Enum):
    UNSPECIFIED = ...
    CDECL = ...
    STDCALL = ...
    FASTCALL = ...
    THISCALL = ...

class MicrocodeFunctionRole(Enum):
    UNKNOWN = ...
    EMPTY = ...
    MEMSET = ...
    MEMSET32 = ...
    MEMSET64 = ...
    MEMCPY = ...
    STRCPY = ...
    STRLEN = ...
    STRCAT = ...
    TAIL = ...
    BUG = ...
    ALLOCA = ...
    BYTE_SWAP = ...
    PRESENT = ...
    CONTAINING_RECORD = ...
    FAST_FAIL = ...
    READ_FLAGS = ...
    IS_MUL_OK = ...
    SATURATED_MUL = ...
    BIT_TEST = ...
    BIT_TEST_AND_SET = ...
    BIT_TEST_AND_RESET = ...
    BIT_TEST_AND_COMPLEMENT = ...
    VA_ARG = ...
    VA_COPY = ...
    VA_START = ...
    VA_END = ...
    ROTATE_LEFT = ...
    ROTATE_RIGHT = ...
    CARRY_FLAG_SUB3 = ...
    OVERFLOW_FLAG_SUB3 = ...
    ABSOLUTE_VALUE = ...
    THREE_WAY_COMPARE0 = ...
    THREE_WAY_COMPARE1 = ...
    WIDE_MEM_COPY = ...
    WIDE_MEM_SET = ...
    WIDE_STR_COPY = ...
    WIDE_STR_LEN = ...
    WIDE_STR_CAT = ...
    SSE_COMPARE4 = ...
    SSE_COMPARE8 = ...

class VariableStorage(Enum):
    UNKNOWN = ...
    REGISTER = ...
    STACK = ...

class LocalVariableLocationKind(Enum):
    NONE = ...
    REGISTER = ...
    STACK = ...

class VisitAction(Enum):
    CONTINUE = ...
    STOP = ...
    SKIP_CHILDREN = ...

class CommentPositionKind(Enum):
    DEFAULT = ...
    ARGUMENT = ...
    PARENTHESIS_OPEN = ...
    ASSEMBLY = ...
    ELSE_LINE = ...
    DO_LINE = ...
    SEMICOLON = ...
    OPEN_BRACE = ...
    CLOSE_BRACE = ...
    PARENTHESIS_CLOSE = ...
    LABEL_COLON = ...
    BLOCK_BEFORE = ...
    BLOCK_AFTER = ...
    TRY_LINE = ...
    SWITCH_CASE = ...

class ItemType(Enum):
    EXPR_EMPTY = ...
    EXPR_COMMA = ...
    EXPR_ASSIGN = ...
    EXPR_ASSIGN_BIT_OR = ...
    EXPR_ASSIGN_XOR = ...
    EXPR_ASSIGN_BIT_AND = ...
    EXPR_ASSIGN_ADD = ...
    EXPR_ASSIGN_SUB = ...
    EXPR_ASSIGN_MUL = ...
    EXPR_ASSIGN_SHIFT_RIGHT_SIGNED = ...
    EXPR_ASSIGN_SHIFT_RIGHT_UNSIGNED = ...
    EXPR_ASSIGN_SHIFT_LEFT = ...
    EXPR_ASSIGN_DIV_SIGNED = ...
    EXPR_ASSIGN_DIV_UNSIGNED = ...
    EXPR_ASSIGN_MOD_SIGNED = ...
    EXPR_ASSIGN_MOD_UNSIGNED = ...
    EXPR_TERNARY = ...
    EXPR_LOGICAL_OR = ...
    EXPR_LOGICAL_AND = ...
    EXPR_BIT_OR = ...
    EXPR_XOR = ...
    EXPR_BIT_AND = ...
    EXPR_EQUAL = ...
    EXPR_NOT_EQUAL = ...
    EXPR_SIGNED_GE = ...
    EXPR_UNSIGNED_GE = ...
    EXPR_SIGNED_LE = ...
    EXPR_UNSIGNED_LE = ...
    EXPR_SIGNED_GT = ...
    EXPR_UNSIGNED_GT = ...
    EXPR_SIGNED_LT = ...
    EXPR_UNSIGNED_LT = ...
    EXPR_SHIFT_RIGHT_SIGNED = ...
    EXPR_SHIFT_RIGHT_UNSIGNED = ...
    EXPR_SHIFT_LEFT = ...
    EXPR_ADD = ...
    EXPR_SUB = ...
    EXPR_MUL = ...
    EXPR_DIV_SIGNED = ...
    EXPR_DIV_UNSIGNED = ...
    EXPR_MOD_SIGNED = ...
    EXPR_MOD_UNSIGNED = ...
    EXPR_FLOAT_ADD = ...
    EXPR_FLOAT_SUB = ...
    EXPR_FLOAT_MUL = ...
    EXPR_FLOAT_DIV = ...
    EXPR_FLOAT_NEG = ...
    EXPR_NEG = ...
    EXPR_CAST = ...
    EXPR_LOGICAL_NOT = ...
    EXPR_BIT_NOT = ...
    EXPR_DEREF = ...
    EXPR_REF = ...
    EXPR_POST_INC = ...
    EXPR_POST_DEC = ...
    EXPR_PRE_INC = ...
    EXPR_PRE_DEC = ...
    EXPR_CALL = ...
    EXPR_INDEX = ...
    EXPR_MEMBER_REF = ...
    EXPR_MEMBER_PTR = ...
    EXPR_NUMBER = ...
    EXPR_FLOAT_NUMBER = ...
    EXPR_STRING = ...
    EXPR_OBJECT = ...
    EXPR_VARIABLE = ...
    EXPR_INSN = ...
    EXPR_SIZEOF = ...
    EXPR_HELPER = ...
    EXPR_TYPE = ...
    STMT_EMPTY = ...
    STMT_BLOCK = ...
    STMT_EXPR = ...
    STMT_IF = ...
    STMT_FOR = ...
    STMT_WHILE = ...
    STMT_DO = ...
    STMT_SWITCH = ...
    STMT_BREAK = ...
    STMT_CONTINUE = ...
    STMT_RETURN = ...
    STMT_GOTO = ...
    STMT_ASM = ...
    STMT_TRY = ...
    STMT_THROW = ...

class MaturityEvent:
    function_address: int
    new_maturity: Maturity
    def __init__(self) -> None: ...

class PseudocodeEvent:
    function_address: int
    def raw_lines(self) -> list[str]: ...
    def set_raw_line(self, line_index: int, tagged_text: str) -> None: ...
    @property
    def header_line_count(self) -> int: ...

class CursorPositionEvent:
    function_address: int
    cursor_address: int

class HintRequestEvent:
    function_address: int
    item_address: int

class PopulatingPopupEvent:
    function_address: int

class HintResult:
    text: str
    lines: int
    def __init__(self) -> None: ...

class ScopedSession:
    @property
    def valid(self) -> bool: ...
    def close(self) -> None: ...
    def __bool__(self) -> bool: ...
    def __enter__(self) -> ScopedSession: ...
    def __exit__(self, exception_type: type[BaseException] | None,
                 exception: BaseException | None,
                 traceback: TracebackType | None) -> bool: ...

class ScopedSubscription:
    def __init__(self, token: Token = 0) -> None: ...
    @property
    def token(self) -> Token: ...
    @property
    def valid(self) -> bool: ...
    def close(self) -> None: ...
    def reset(self) -> None: ...
    def __enter__(self) -> ScopedSubscription: ...
    def __exit__(self, exception_type: type[BaseException] | None,
                 exception: BaseException | None,
                 traceback: TracebackType | None) -> bool: ...

class MicrocodeOperand:
    kind: MicrocodeOperandKind
    register_id: int
    processor_register_id: int
    local_variable_index: int
    local_variable_offset: int
    second_register_id: int
    global_address: int
    stack_offset: int
    helper_name: str
    block_index: int
    nested_instruction: MicrocodeInstruction | None
    unsigned_immediate: int
    signed_immediate: int
    byte_width: int
    mark_user_defined_type: bool
    referenced_operand: MicrocodeOperand | None
    call_arguments: list[MicrocodeOperand]
    call_target: int
    text: str
    def __init__(self) -> None: ...

class MicrocodeInstruction:
    opcode: MicrocodeOpcode
    left: MicrocodeOperand
    right: MicrocodeOperand
    destination: MicrocodeOperand
    floating_point_instruction: bool
    modifies_destination: bool
    address: int
    text: str
    def __init__(self) -> None: ...

class MicrocodeGenerationOptions:
    maturity: MicrocodeMaturity
    analyze_calls: bool
    def __init__(self) -> None: ...

class MicrocodeLocationPart:
    kind: MicrocodeValueLocationKind
    register_id: int
    second_register_id: int
    register_offset: int
    register_relative_offset: int
    stack_offset: int
    static_address: int
    byte_offset: int
    byte_size: int
    def __init__(self) -> None: ...

class MicrocodeValueLocation:
    kind: MicrocodeValueLocationKind
    register_id: int
    second_register_id: int
    register_offset: int
    register_relative_offset: int
    stack_offset: int
    static_address: int
    scattered_parts: list[MicrocodeLocationPart]
    def __init__(self) -> None: ...

class MicrocodeFunctionArgument:
    name: str
    location: MicrocodeValueLocation
    byte_width: int
    def __init__(self) -> None: ...

class MicrocodeBlock:
    index: int
    start_address: int
    end_address: int
    predecessors: list[int]
    successors: list[int]
    instructions: list[MicrocodeInstruction]
    def __init__(self) -> None: ...

class MicrocodeFunction:
    entry_address: int
    maturity: MicrocodeMaturity
    arguments: list[MicrocodeFunctionArgument]
    return_location: MicrocodeValueLocation | None
    blocks: list[MicrocodeBlock]
    def __init__(self) -> None: ...

class MicrocodeValue:
    kind: MicrocodeValueKind
    register_id: int
    local_variable_index: int
    local_variable_offset: int
    second_register_id: int
    global_address: int
    stack_offset: int
    helper_name: str
    block_index: int
    nested_instruction: MicrocodeInstruction | None
    unsigned_immediate: int
    signed_immediate: int
    floating_immediate: float
    byte_width: int
    unsigned_integer: bool
    vector_element_byte_width: int
    vector_element_count: int
    vector_elements_unsigned: bool
    vector_elements_floating: bool
    type_declaration: str
    argument_name: str
    argument_flags: int
    location: MicrocodeValueLocation
    def __init__(self) -> None: ...

class MicrocodeRegisterRange:
    register_id: int
    byte_width: int
    def __init__(self) -> None: ...

class MicrocodeMemoryRange:
    address: int
    byte_size: int
    def __init__(self) -> None: ...

class MicrocodeCallOptions:
    insert_policy: MicrocodeInsertPolicy | None
    callee_address: int | None
    solid_argument_count: int | None
    call_stack_pointer_delta: int | None
    stack_arguments_top: int | None
    function_role: MicrocodeFunctionRole | None
    return_location: MicrocodeValueLocation | None
    return_type_declaration: str
    calling_convention: MicrocodeCallingConvention
    mark_final: bool
    mark_propagated: bool
    mark_dead_return_registers: bool
    mark_no_return: bool
    mark_pure: bool
    mark_no_side_effects: bool
    mark_spoiled_lists_optimized: bool
    mark_synthetic_has_call: bool
    mark_has_format_string: bool
    auto_stack_start_offset: int | None
    auto_stack_alignment: int | None
    auto_stack_argument_locations: bool
    mark_explicit_locations: bool
    return_registers: list[MicrocodeRegisterRange]
    spoiled_registers: list[MicrocodeRegisterRange]
    passthrough_registers: list[MicrocodeRegisterRange]
    dead_registers: list[MicrocodeRegisterRange]
    visible_memory_ranges: list[MicrocodeMemoryRange]
    visible_memory_all: bool
    def __init__(self) -> None: ...

class MicrocodeContext:
    @property
    def address(self) -> int: ...
    @property
    def instruction_type(self) -> int: ...
    @property
    def has_opmask(self) -> bool: ...
    @property
    def is_zero_masking(self) -> bool: ...
    @property
    def opmask_register_number(self) -> int: ...
    def local_variable_count(self) -> int: ...
    def block_instruction_count(self) -> int: ...
    def has_instruction_at_index(self, instruction_index: int) -> bool: ...
    def instruction(self) -> Instruction: ...
    def instruction_at_index(self, instruction_index: int) -> MicrocodeInstruction: ...
    def has_last_emitted_instruction(self) -> bool: ...
    def last_emitted_instruction(self) -> MicrocodeInstruction: ...
    def remove_last_emitted_instruction(self) -> None: ...
    def remove_instruction_at_index(self, instruction_index: int) -> None: ...
    def emit_noop(self) -> None: ...
    def emit_noop_with_policy(self, policy: MicrocodeInsertPolicy) -> None: ...
    def emit_instruction(self, instruction: MicrocodeInstruction) -> None: ...
    def emit_instruction_with_policy(self, instruction: MicrocodeInstruction,
                                     policy: MicrocodeInsertPolicy) -> None: ...
    def emit_instructions(self, instructions: list[MicrocodeInstruction]) -> None: ...
    def emit_instructions_with_policy(self, instructions: list[MicrocodeInstruction],
                                      policy: MicrocodeInsertPolicy) -> None: ...
    def load_operand_register(self, operand_index: int) -> int: ...
    def load_effective_address_register(self, operand_index: int) -> int: ...
    def allocate_temporary_register(self, byte_width: int) -> int: ...
    def store_operand_register(self, operand_index: int, source_register: int,
                               byte_width: int,
                               mark_user_defined_type: bool = ...) -> None: ...
    def emit_move_register(self, source_register: int, destination_register: int,
                           byte_width: int,
                           mark_user_defined_type: bool = ...) -> None: ...
    def emit_move_register_with_policy(self, source_register: int,
                                       destination_register: int, byte_width: int,
                                       policy: MicrocodeInsertPolicy,
                                       mark_user_defined_type: bool = ...) -> None: ...
    def emit_load_memory_register(self, selector_register: int, offset_register: int,
                                  destination_register: int, byte_width: int,
                                  offset_byte_width: int,
                                  mark_user_defined_type: bool = ...) -> None: ...
    def emit_load_memory_register_with_policy(self, selector_register: int,
                                              offset_register: int,
                                              destination_register: int,
                                              byte_width: int,
                                              offset_byte_width: int,
                                              policy: MicrocodeInsertPolicy,
                                              mark_user_defined_type: bool = ...) -> None: ...
    def emit_store_memory_register(self, source_register: int, selector_register: int,
                                   offset_register: int, byte_width: int,
                                   offset_byte_width: int,
                                   mark_user_defined_type: bool = ...) -> None: ...
    def emit_store_memory_register_with_policy(self, source_register: int,
                                               selector_register: int,
                                               offset_register: int,
                                               byte_width: int,
                                               offset_byte_width: int,
                                               policy: MicrocodeInsertPolicy,
                                               mark_user_defined_type: bool = ...) -> None: ...
    def emit_helper_call(self, helper_name: str) -> None: ...
    def emit_helper_call_with_arguments(self, helper_name: str,
                                        arguments: list[MicrocodeValue]) -> None: ...
    def emit_helper_call_with_arguments_and_options(self, helper_name: str,
                                                    arguments: list[MicrocodeValue],
                                                    options: MicrocodeCallOptions) -> None: ...
    def emit_helper_call_with_arguments_to_register(self, helper_name: str,
                                                    arguments: list[MicrocodeValue],
                                                    destination_register: int,
                                                    destination_byte_width: int,
                                                    destination_unsigned: bool = ...) -> None: ...
    def emit_helper_call_with_arguments_to_register_and_options(self, helper_name: str,
                                                                arguments: list[MicrocodeValue],
                                                                destination_register: int,
                                                                destination_byte_width: int,
                                                                destination_unsigned: bool,
                                                                options: MicrocodeCallOptions) -> None: ...
    def emit_helper_call_with_arguments_to_micro_operand(self, helper_name: str,
                                                         arguments: list[MicrocodeValue],
                                                         destination: MicrocodeOperand,
                                                         destination_unsigned: bool = ...) -> None: ...
    def emit_helper_call_with_arguments_to_micro_operand_and_options(self, helper_name: str,
                                                                     arguments: list[MicrocodeValue],
                                                                     destination: MicrocodeOperand,
                                                                     destination_unsigned: bool,
                                                                     options: MicrocodeCallOptions) -> None: ...
    def emit_helper_call_with_arguments_to_operand(self, helper_name: str,
                                                   arguments: list[MicrocodeValue],
                                                   destination_operand_index: int,
                                                   destination_byte_width: int,
                                                   destination_unsigned: bool = ...) -> None: ...
    def emit_helper_call_with_arguments_to_operand_and_options(self, helper_name: str,
                                                               arguments: list[MicrocodeValue],
                                                               destination_operand_index: int,
                                                               destination_byte_width: int,
                                                               destination_unsigned: bool,
                                                               options: MicrocodeCallOptions) -> None: ...

class MicrocodeFilter:
    def __init__(self) -> None: ...
    def match(self, context: MicrocodeContext) -> bool: ...
    def apply(self, context: MicrocodeContext) -> MicrocodeApplyResult: ...

class ScopedMicrocodeFilter:
    def __init__(self, token: FilterToken = 0) -> None: ...
    @property
    def token(self) -> FilterToken: ...
    @property
    def valid(self) -> bool: ...
    def close(self) -> None: ...
    def reset(self) -> None: ...
    def __enter__(self) -> ScopedMicrocodeFilter: ...
    def __exit__(self, exception_type: type[BaseException] | None,
                 exception: BaseException | None,
                 traceback: TracebackType | None) -> bool: ...

class DecompileFailure:
    request_address: int
    failure_address: int
    description: str
    def __init__(self) -> None: ...

class LocalVariableLocator:
    kind: LocalVariableLocationKind
    register_id: int
    stack_offset: int
    definition_address: int
    def __init__(self) -> None: ...

class LocalVariable:
    index: int
    name: str
    type_name: str
    is_argument: bool
    width: int
    has_user_name: bool
    has_nice_name: bool
    storage: VariableStorage
    comment: str
    def __init__(self) -> None: ...

class LocalVariableUserSetting:
    locator: LocalVariableLocator
    name: str
    type_declaration: str
    comment: str
    def __init__(self) -> None: ...

class ReferencedTypeCollection:
    ordinals: list[int]
    used_offsets: list[UsedMemberOffsets]
    def __init__(self) -> None: ...

class LvarSnapshot:
    def __init__(self) -> None: ...
    @property
    def empty(self) -> bool: ...
    @property
    def saved_variable_count(self) -> int: ...
    def __bool__(self) -> bool: ...

class CtreeItemView:
    type: ItemType
    address: int
    is_expression: bool
    def __init__(self) -> None: ...

class ExpressionView:
    @property
    def type(self) -> ItemType: ...
    @property
    def address(self) -> int: ...
    def number_value(self) -> int: ...
    def object_address(self) -> int: ...
    def variable_index(self) -> int: ...
    def helper_name(self) -> str: ...
    def type_declaration(self) -> str: ...
    def type_byte_width(self) -> int: ...
    def pointed_type_byte_width(self) -> int: ...
    def string_value(self) -> str: ...
    def call_argument_count(self) -> int: ...
    def call_callee(self) -> ExpressionView: ...
    def call_argument(self, index: int) -> ExpressionView: ...
    def member_offset(self) -> int: ...
    def member_name(self) -> str: ...
    @property
    def is_assignment_lhs(self) -> bool: ...
    def left(self) -> ExpressionView: ...
    def right(self) -> ExpressionView: ...
    @property
    def operand_count(self) -> int: ...
    def third(self) -> ExpressionView: ...
    def to_string(self) -> str: ...
    def parent(self) -> CtreeItemView | None: ...
    def parents(self) -> list[CtreeItemView]: ...

class StatementView:
    @property
    def type(self) -> ItemType: ...
    @property
    def address(self) -> int: ...
    def goto_target_label(self) -> int: ...
    def parent(self) -> CtreeItemView | None: ...
    def parents(self) -> list[CtreeItemView]: ...

class CtreeVisitor:
    def __init__(self) -> None: ...
    def visit_expression(self, expression: ExpressionView) -> VisitAction: ...
    def visit_statement(self, statement: StatementView) -> VisitAction: ...
    def leave_expression(self, expression: ExpressionView) -> VisitAction: ...
    def leave_statement(self, statement: StatementView) -> VisitAction: ...

class VisitOptions:
    post_order: bool
    track_parents: bool
    expressions_only: bool
    def __init__(self) -> None: ...

class CommentPosition:
    DEFAULT: ClassVar[CommentPosition]
    PARENTHESIS_OPEN: ClassVar[CommentPosition]
    ASSEMBLY: ClassVar[CommentPosition]
    ELSE_LINE: ClassVar[CommentPosition]
    DO_LINE: ClassVar[CommentPosition]
    SEMICOLON: ClassVar[CommentPosition]
    OPEN_BRACE: ClassVar[CommentPosition]
    CLOSE_BRACE: ClassVar[CommentPosition]
    PARENTHESIS_CLOSE: ClassVar[CommentPosition]
    LABEL_COLON: ClassVar[CommentPosition]
    BLOCK_BEFORE: ClassVar[CommentPosition]
    BLOCK_AFTER: ClassVar[CommentPosition]
    TRY_LINE: ClassVar[CommentPosition]
    def __init__(self) -> None: ...
    @staticmethod
    def argument(zero_based_index: int) -> CommentPosition: ...
    @staticmethod
    def switch_case(value: int) -> CommentPosition: ...
    @property
    def kind(self) -> CommentPositionKind: ...
    @property
    def argument_index(self) -> int | None: ...
    @property
    def switch_case_value(self) -> int | None: ...
    def __eq__(self, other: object) -> bool: ...

class PseudocodeComment:
    address: int
    position: CommentPosition
    text: str
    def __init__(self) -> None: ...

class AddressMapping:
    address: int
    line_number: int
    def __init__(self) -> None: ...

class ItemAtPosition:
    type: ItemType
    address: int
    item_index: int
    is_expression: bool
    def __init__(self) -> None: ...

class DecompiledFunction:
    @property
    def valid(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> DecompiledFunction: ...
    def __exit__(self, exc_type: object, exc_value: object,
                 traceback: object) -> bool: ...
    def pseudocode(self) -> str: ...
    def microcode(self) -> str: ...
    def lines(self) -> list[str]: ...
    def raw_lines(self) -> list[str]: ...
    def set_raw_line(self, line_index: int, tagged_text: str) -> None: ...
    def header_line_count(self) -> int: ...
    def microcode_lines(self) -> list[str]: ...
    def declaration(self) -> str: ...
    def variable_count(self) -> int: ...
    def variables(self) -> list[LocalVariable]: ...
    def variable(self, variable_index: int) -> LocalVariable: ...
    def rename_variable(self, old_name: str, new_name: str) -> None: ...
    def retype_variable(self, variable: str | int, new_type: TypeInfo) -> None: ...
    def capture_user_lvar_settings(self) -> LvarSnapshot: ...
    def restore_user_lvar_settings(self, snapshot: LvarSnapshot) -> None: ...
    def set_variable_comment(self, variable: str | int, comment: str) -> None: ...
    def visit(self, visitor: CtreeVisitor, options: VisitOptions = ...) -> int: ...
    def visit_expressions(self, visitor: CtreeVisitor,
                          post_order: bool = ...) -> int: ...
    def set_comment(self, address: int, text: str,
                    position: CommentPosition = ...) -> None: ...
    def get_comment(self, address: int,
                    position: CommentPosition = ...) -> str: ...
    def comments(self) -> list[PseudocodeComment]: ...
    def save_comments(self) -> None: ...
    def has_orphan_comments(self) -> bool: ...
    def remove_orphan_comments(self) -> int: ...
    def refresh(self) -> None: ...
    @property
    def entry_address(self) -> int: ...
    def line_to_address(self, line_number: int) -> int: ...
    def address_map(self) -> list[AddressMapping]: ...

class DecompilerView:
    @property
    def function_address(self) -> int: ...
    def function_name(self) -> str: ...
    def decompiled_function(self) -> DecompiledFunction: ...
    def rename_variable(self, old_name: str, new_name: str) -> None: ...
    def retype_variable(self, variable: str | int, new_type: TypeInfo) -> None: ...
    def capture_user_lvar_settings(self) -> LvarSnapshot: ...
    def restore_user_lvar_settings(self, snapshot: LvarSnapshot) -> None: ...
    def set_variable_comment(self, variable: str | int, comment: str) -> None: ...
    def set_comment(self, address: int, text: str,
                    position: CommentPosition = ...) -> None: ...
    def get_comment(self, address: int,
                    position: CommentPosition = ...) -> str: ...
    def comments(self) -> list[PseudocodeComment]: ...
    def save_comments(self) -> None: ...
    def refresh(self) -> None: ...

def initialize() -> ScopedSession: ...
def available() -> bool: ...
def on_maturity_changed(callback: Callable[[MaturityEvent], None]) -> Token: ...
def on_func_printed(callback: Callable[[PseudocodeEvent], None]) -> Token: ...
def on_refresh_pseudocode(callback: Callable[[PseudocodeEvent], None]) -> Token: ...
def on_switch_pseudocode(callback: Callable[[PseudocodeEvent], None]) -> Token: ...
def on_curpos_changed(callback: Callable[[CursorPositionEvent], None]) -> Token: ...
def on_create_hint(callback: Callable[[HintRequestEvent], HintResult]) -> Token: ...
def on_populating_popup(callback: Callable[[PopulatingPopupEvent], None]) -> Token: ...
def unsubscribe(token: Token) -> None: ...
def mark_dirty(function_address: int, close_views: bool = ...) -> None: ...
def mark_dirty_with_callers(function_address: int, close_views: bool = ...) -> None: ...
def register_microcode_filter(filter: MicrocodeFilter) -> FilterToken: ...
def unregister_microcode_filter(token: FilterToken) -> None: ...
def generate_microcode(function_address: int,
                       options: MicrocodeGenerationOptions = ...) -> MicrocodeFunction: ...
def saved_user_lvar_settings(function_address: int) -> list[LocalVariableUserSetting]: ...
def apply_user_lvar_setting(function_address: int,
                            setting: LocalVariableUserSetting) -> None: ...
def apply_user_lvar_settings(function_address: int,
                             settings: list[LocalVariableUserSetting]) -> None: ...
def collect_referenced_types(function_address: int) -> ReferencedTypeCollection: ...
def is_expression(type: ItemType) -> bool: ...
def is_statement(type: ItemType) -> bool: ...
def view_from_host(event: CursorPositionEvent | HintRequestEvent |
                   PopulatingPopupEvent) -> DecompilerView: ...
def view_for_function(address: int) -> DecompilerView: ...
def current_view() -> DecompilerView: ...
def decompile(address: int) -> DecompiledFunction: ...
def raw_pseudocode_lines(event: PseudocodeEvent) -> list[str]: ...
def set_pseudocode_line(event: PseudocodeEvent, line_index: int,
                        tagged_text: str) -> None: ...
def pseudocode_header_line_count(event: PseudocodeEvent) -> int: ...
def item_at_position(event: PseudocodeEvent, tagged_line: str,
                     char_index: int) -> ItemAtPosition: ...
def item_type_name(type: ItemType) -> str: ...
def for_each_expression(function: DecompiledFunction,
                        callback: Callable[[ExpressionView], VisitAction]) -> int: ...
def for_each_item(function: DecompiledFunction,
                  on_expression: Callable[[ExpressionView], VisitAction],
                  on_statement: Callable[[StatementView], VisitAction]) -> int: ...
