"""Hex-Rays sessions, ctree, microcode, and pseudocode."""

from ._native.decompiler import (
    AddressMapping,
    CommentPosition,
    CommentPositionKind,
    CtreeItemView,
    CtreeVisitor,
    CursorPositionEvent,
    DecompileFailure,
    DecompiledFunction,
    DecompilerView,
    ExpressionView,
    HintRequestEvent,
    HintResult,
    ItemAtPosition,
    ItemType,
    LocalVariable,
    LocalVariableLocationKind,
    LocalVariableLocator,
    LocalVariableUserSetting,
    LvarSnapshot,
    Maturity,
    MaturityEvent,
    MicrocodeApplyResult,
    MicrocodeArgumentFlag,
    MicrocodeBlock,
    MicrocodeCallOptions,
    MicrocodeCallingConvention,
    MicrocodeContext,
    MicrocodeFilter,
    MicrocodeFunction,
    MicrocodeFunctionArgument,
    MicrocodeFunctionRole,
    MicrocodeGenerationOptions,
    MicrocodeInsertPolicy,
    MicrocodeInstruction,
    MicrocodeLocationPart,
    MicrocodeMaturity,
    MicrocodeMemoryRange,
    MicrocodeOpcode,
    MicrocodeOperand,
    MicrocodeOperandKind,
    MicrocodeRegisterRange,
    MicrocodeValue,
    MicrocodeValueKind,
    MicrocodeValueLocation,
    MicrocodeValueLocationKind,
    PopulatingPopupEvent,
    PseudocodeComment,
    PseudocodeEvent,
    ReferencedTypeCollection,
    ScopedMicrocodeFilter,
    ScopedSession,
    ScopedSubscription,
    StatementView,
    VariableStorage,
    VisitAction,
    VisitOptions,
    apply_user_lvar_setting,
    apply_user_lvar_settings,
    available,
    collect_referenced_types,
    current_view,
    decompile,
    for_each_expression,
    for_each_item,
    generate_microcode,
    initialize,
    is_expression,
    is_statement,
    item_at_position,
    item_type_name,
    mark_dirty,
    mark_dirty_with_callers,
    on_create_hint,
    on_curpos_changed,
    on_func_printed,
    on_maturity_changed,
    on_populating_popup,
    on_refresh_pseudocode,
    on_switch_pseudocode,
    pseudocode_header_line_count,
    raw_pseudocode_lines,
    register_microcode_filter,
    saved_user_lvar_settings,
    set_pseudocode_line,
    unregister_microcode_filter,
    unsubscribe,
    view_for_function,
    view_from_host,
)

__all__ = [
    "AddressMapping", "CommentPosition", "CommentPositionKind", "CtreeItemView",
    "CtreeVisitor", "CursorPositionEvent", "DecompileFailure",
    "DecompiledFunction", "DecompilerView", "ExpressionView", "HintRequestEvent",
    "HintResult", "ItemAtPosition", "ItemType", "LocalVariable",
    "LocalVariableLocationKind", "LocalVariableLocator",
    "LocalVariableUserSetting", "LvarSnapshot", "Maturity", "MaturityEvent",
    "MicrocodeApplyResult", "MicrocodeArgumentFlag", "MicrocodeBlock",
    "MicrocodeCallOptions", "MicrocodeCallingConvention", "MicrocodeContext",
    "MicrocodeFilter", "MicrocodeFunction", "MicrocodeFunctionArgument",
    "MicrocodeFunctionRole", "MicrocodeGenerationOptions", "MicrocodeInsertPolicy",
    "MicrocodeInstruction", "MicrocodeLocationPart", "MicrocodeMaturity",
    "MicrocodeMemoryRange", "MicrocodeOpcode", "MicrocodeOperand",
    "MicrocodeOperandKind", "MicrocodeRegisterRange", "MicrocodeValue",
    "MicrocodeValueKind", "MicrocodeValueLocation", "MicrocodeValueLocationKind",
    "PopulatingPopupEvent", "PseudocodeComment", "PseudocodeEvent",
    "ReferencedTypeCollection", "ScopedMicrocodeFilter", "ScopedSession",
    "ScopedSubscription", "StatementView", "VariableStorage", "VisitAction",
    "VisitOptions", "apply_user_lvar_setting", "apply_user_lvar_settings",
    "available", "collect_referenced_types", "current_view", "decompile",
    "for_each_expression", "for_each_item", "generate_microcode", "initialize",
    "is_expression", "is_statement", "item_at_position", "item_type_name",
    "mark_dirty", "mark_dirty_with_callers", "on_create_hint",
    "on_curpos_changed", "on_func_printed", "on_maturity_changed",
    "on_populating_popup", "on_refresh_pseudocode", "on_switch_pseudocode",
    "pseudocode_header_line_count", "raw_pseudocode_lines",
    "register_microcode_filter", "saved_user_lvar_settings",
    "set_pseudocode_line", "unregister_microcode_filter", "unsubscribe",
    "view_for_function", "view_from_host",
]
