from enum import Enum
from .error import ErrorInfo

class LogLevel(Enum):
    ERROR = ...
    WARNING = ...
    INFO = ...
    DEBUG = ...
    TRACE = ...

class PerformanceCounters:
    log_messages: int
    invariant_failures: int
    def __init__(self) -> None: ...

def set_log_level(level: LogLevel) -> None: ...
def log_level() -> LogLevel: ...
def log(level: LogLevel, domain: str, message: str) -> None: ...
def enrich(error: ErrorInfo, context_suffix: str) -> ErrorInfo: ...
def assert_invariant(condition: bool, message: str) -> None: ...
def reset_performance_counters() -> None: ...
def performance_counters() -> PerformanceCounters: ...
