from collections.abc import Sequence
from enum import Enum

class Kind(Enum):
    LOCAL_TYPES = 0
    FUNCTIONS = 1
    NAMES = 2
    IMPORTS = 3
    IDA_PLACE_BOOKMARKS = 4
    BREAKPOINTS = 5
    LOCAL_TYPE_BOOKMARKS = 6
    SNIPPETS = 7

class EntryKind(Enum):
    DIRECTORY = 0
    ITEM = 1

class OperationError(Enum):
    ALREADY_EXISTS = 1
    NOT_FOUND = 2
    NOT_DIRECTORY = 3
    NOT_EMPTY = 4
    BAD_PATH = 5
    CANNOT_RENAME = 6
    OWN_CHILD = 7
    DIRECTORY_LIMIT = 8
    NOT_ORDERABLE = 9
    SDK_FAILURE = 10

class Entry:
    path: str
    name: str
    display_name: str
    attributes: str
    kind: EntryKind
    @property
    def is_directory(self) -> bool: ...

class BulkFailure:
    input_index: int
    path: str
    error: OperationError
    message: str

class BulkReport:
    affected_paths: list[str]
    failures: list[BulkFailure]
    @property
    def ok(self) -> bool: ...
    def __bool__(self) -> bool: ...

class Tree:
    @staticmethod
    def open(kind: Kind) -> Tree: ...
    @property
    def kind(self) -> Kind: ...
    @property
    def is_orderable(self) -> bool: ...
    @property
    def current_directory(self) -> str: ...
    def change_directory(self, path: str) -> None: ...
    def absolute_path(self, relative_path: str) -> str: ...
    def contains(self, path: str) -> bool: ...
    def entry(self, path: str) -> Entry: ...
    def children(self, path: str = ...) -> list[Entry]: ...
    def snapshot(self, path: str = ...) -> list[Entry]: ...
    def find_items(self, pattern: str) -> list[Entry]: ...
    def create_directory(self, path: str) -> None: ...
    def remove_directory(self, path: str) -> None: ...
    def link(self, path: str) -> None: ...
    def unlink(self, path: str) -> None: ...
    def rename(self, from_path: str, to_path: str) -> None: ...
    def fold_common_prefix(self, path: str = ...) -> None: ...
    def has_natural_order(self, directory_path: str) -> bool: ...
    def set_natural_order(self, directory_path: str, enable: bool) -> None: ...
    def rank(self, path: str) -> int: ...
    def change_rank(self, path: str, delta: int) -> None: ...
    def move(
        self,
        paths: Sequence[str],
        destination_directory: str,
        destination_rank: int | None = ...,
    ) -> BulkReport: ...
    def remove(self, paths: Sequence[str]) -> BulkReport: ...
