from os import PathLike
from typing import TypeAlias
_Path: TypeAlias = str | bytes | PathLike[str] | PathLike[bytes]
class ModuleInfo:
    @property
    def path(self) -> str: ...
    @property
    def load_address(self) -> int: ...
def is_available() -> bool: ...
def list_modules(cache_path: _Path | None = None) -> list[ModuleInfo]: ...
def load_module(module_path: str, wait_for_analysis: bool = False) -> None: ...
def load_section(address: int, wait_for_analysis: bool = False) -> None: ...
def load_dyld_header(wait_for_analysis: bool = False) -> None: ...
def load_branch_islands(wait_for_analysis: bool = False) -> int: ...
def load_branch_mappings(wait_for_analysis: bool = False) -> int: ...
def load_global_offset_tables(wait_for_analysis: bool = False) -> int: ...
def load_gaps(wait_for_analysis: bool = False) -> int: ...
def load_cache_data(wait_for_analysis: bool = False) -> int: ...
