class EntryPoint:
    ordinal: int
    address: int
    name: str
    forwarder: str
    def __init__(self) -> None: ...

def count() -> int: ...
def by_index(index: int) -> EntryPoint: ...
def by_ordinal(ordinal: int) -> EntryPoint: ...
def add(ordinal: int, address: int, name: str,
        make_code: bool = ...) -> None: ...
def rename(ordinal: int, name: str) -> None: ...
def forwarder(ordinal: int) -> str: ...
def set_forwarder(ordinal: int, target: str) -> None: ...
def clear_forwarder(ordinal: int) -> None: ...
