from enum import Enum

class ErrorCategory(Enum):
    VALIDATION = ...
    NOT_FOUND = ...
    CONFLICT = ...
    UNSUPPORTED = ...
    SDK_FAILURE = ...
    INTERNAL = ...

class ErrorInfo:
    category: ErrorCategory
    code: int
    message: str
    context: str
    def __init__(self, category: ErrorCategory = ..., code: int = ...,
                 message: str = ..., context: str = ...) -> None: ...
    @staticmethod
    def validation(message: str, context: str = ...) -> ErrorInfo: ...
    @staticmethod
    def not_found(message: str, context: str = ...) -> ErrorInfo: ...
    @staticmethod
    def conflict(message: str, context: str = ...) -> ErrorInfo: ...
    @staticmethod
    def unsupported(message: str, context: str = ...) -> ErrorInfo: ...
    @staticmethod
    def sdk_failure(message: str, context: str = ...) -> ErrorInfo: ...
    @staticmethod
    def internal(message: str, context: str = ...) -> ErrorInfo: ...

class IdaxError(RuntimeError):
    category: ErrorCategory
    code: int
    message: str
    context: str

class ValidationError(IdaxError): ...
class NotFoundError(IdaxError): ...
class ConflictError(IdaxError): ...
class UnsupportedError(IdaxError): ...
class SdkError(IdaxError): ...
class InternalError(IdaxError): ...
