from collections.abc import Callable
from enum import Enum
from types import TracebackType
from typing import TypeAlias

Token: TypeAlias = int

class EventKind(Enum):
    SEGMENT_ADDED = ...
    SEGMENT_DELETED = ...
    FUNCTION_ADDED = ...
    FUNCTION_DELETED = ...
    RENAMED = ...
    BYTE_PATCHED = ...
    COMMENT_CHANGED = ...
    SEGMENT_MOVED = ...
    FUNCTION_UPDATED = ...
    ITEM_TYPE_CHANGED = ...
    OPERAND_TYPE_CHANGED = ...
    CODE_CREATED = ...
    DATA_CREATED = ...
    ITEMS_DESTROYED = ...
    EXTRA_COMMENT_CHANGED = ...
    LOCAL_TYPES_CHANGED = ...

class ExtraCommentPlacement(Enum):
    UNKNOWN = ...
    ANTERIOR = ...
    POSTERIOR = ...

class LocalTypeChangeKind(Enum):
    NONE = ...
    ADDED = ...
    DELETED = ...
    EDITED = ...
    ALIASED = ...
    COMPILER_CHANGED = ...
    LIBRARY_LOADED = ...
    LIBRARY_UNLOADED = ...
    ORDINALS_COMPACTED = ...

class SegmentMovedEvent:
    from_address: int
    to_address: int
    size: int
    address_mapping_changed: bool
    def __init__(self) -> None: ...

class ItemCreatedEvent:
    address: int
    size: int
    def __init__(self) -> None: ...

class ItemsDestroyedEvent:
    start: int
    end: int
    will_disable_range: bool
    def __init__(self) -> None: ...

class ExtraCommentChangedEvent:
    address: int
    placement: ExtraCommentPlacement
    line_index: int
    text: str
    def __init__(self) -> None: ...

class LocalTypesChangedEvent:
    change: LocalTypeChangeKind
    ordinal: int
    name: str
    def __init__(self) -> None: ...

class Event:
    kind: EventKind
    address: int
    secondary_address: int
    new_name: str
    old_name: str
    old_value: int
    repeatable: bool
    size: int
    operand_index: int
    line_index: int
    text: str
    will_disable_range: bool
    address_mapping_changed: bool
    extra_comment_placement: ExtraCommentPlacement
    local_type_change: LocalTypeChangeKind
    type_ordinal: int
    type_name: str
    def __init__(self) -> None: ...

class ScopedSubscription:
    def __init__(self, token: Token) -> None: ...
    @property
    def token(self) -> Token: ...
    def close(self) -> None: ...
    def __enter__(self) -> ScopedSubscription: ...
    def __exit__(self, exception_type: type[BaseException] | None,
                 exception: BaseException | None,
                 traceback: TracebackType | None) -> bool: ...

def unsubscribe(token: Token) -> None: ...
def on_segment_added(callback: Callable[[int], None]) -> Token: ...
def on_segment_deleted(callback: Callable[[int, int], None]) -> Token: ...
def on_function_added(callback: Callable[[int], None]) -> Token: ...
def on_function_deleted(callback: Callable[[int], None]) -> Token: ...
def on_renamed(callback: Callable[[int, str, str], None]) -> Token: ...
def on_byte_patched(callback: Callable[[int, int], None]) -> Token: ...
def on_comment_changed(callback: Callable[[int, bool], None]) -> Token: ...
def on_segment_moved(callback: Callable[[SegmentMovedEvent], None]) -> Token: ...
def on_function_updated(callback: Callable[[int], None]) -> Token: ...
def on_item_type_changed(callback: Callable[[int], None]) -> Token: ...
def on_operand_type_changed(callback: Callable[[int, int], None]) -> Token: ...
def on_code_created(callback: Callable[[ItemCreatedEvent], None]) -> Token: ...
def on_data_created(callback: Callable[[ItemCreatedEvent], None]) -> Token: ...
def on_items_destroyed(callback: Callable[[ItemsDestroyedEvent], None]) -> Token: ...
def on_extra_comment_changed(callback: Callable[[ExtraCommentChangedEvent], None]) -> Token: ...
def on_local_types_changed(callback: Callable[[LocalTypesChangedEvent], None]) -> Token: ...
def on_event(callback: Callable[[Event], None]) -> Token: ...
def on_event_filtered(filter: Callable[[Event], bool],
                      callback: Callable[[Event], None]) -> Token: ...
