import builtins
from collections.abc import Sequence
from enum import Enum
from .address import Range

class CatchSelectorKind(Enum):
    TYPED = ...
    CATCH_ALL = ...
    CLEANUP = ...

class SehDisposition(Enum):
    CONTINUE_EXECUTION = ...
    CONTINUE_SEARCH = ...
    EXECUTE_HANDLER = ...

class Location(Enum):
    CPP_TRY = ...
    CPP_HANDLER = ...
    SEH_TRY = ...
    SEH_HANDLER = ...
    SEH_FILTER = ...
    ANY = ...
    UNWIND_FALLTHROUGH = ...

class HandlerMetadata:
    regions: list[Range]
    stack_displacement: int | None
    frame_register: int | None
    def __init__(self) -> None: ...

class CatchSelector:
    kind: CatchSelectorKind
    type_identifier: int
    def __init__(self) -> None: ...

class CatchHandler:
    metadata: HandlerMetadata
    object_displacement: int | None
    selector: CatchSelector
    def __init__(self) -> None: ...

class SehHandler:
    metadata: HandlerMetadata
    filter_regions: list[Range]
    disposition: SehDisposition | None
    def __init__(self) -> None: ...

class CppHandlers:
    catches: list[CatchHandler]
    def __init__(self) -> None: ...

class BlockDefinition:
    protected_regions: list[Range]
    handlers: CppHandlers | SehHandler
    def __init__(self) -> None: ...

class Block:
    @property
    def definition(self) -> BlockDefinition: ...
    @property
    def nesting_level(self) -> int: ...

def list(range: Range) -> builtins.list[Block]: ...
def remove(range: Range) -> None: ...
def add(definition: BlockDefinition) -> None: ...
def system_region_start(address: int) -> int | None: ...
def contains(address: int, locations: Location | Sequence[Location] = ...) -> bool: ...
