from collections.abc import Iterator
from enum import Enum, IntFlag

class Type(Enum):
    OFF8 = ...
    OFF16 = ...
    SEG16 = ...
    PTR16 = ...
    OFF32 = ...
    PTR32 = ...
    HI8 = ...
    HI16 = ...
    LOW8 = ...
    LOW16 = ...
    OFF64 = ...
    OFF8_SIGNED = ...
    OFF16_SIGNED = ...
    OFF32_SIGNED = ...
    CUSTOM = ...

class HandlerProperty(IntFlag):
    VERIFY = ...
    CODE = ...
    FORCE_CODE = ...
    ABSOLUTE_OP = ...
    SIGNED_OP = ...

class Descriptor:
    source: int
    type: Type
    flags: int
    base: int
    target: int
    selector: int
    offset: int
    displacement: int
    def __init__(self) -> None: ...

class CustomHandler:
    name: str
    properties: int
    size: int
    width: int
    shift: int
    reference_type: int
    def __init__(self) -> None: ...

class FixupRange:
    def __iter__(self) -> Iterator[Descriptor]: ...

def at(source: int) -> Descriptor: ...
def set(source: int, descriptor: Descriptor) -> None: ...
def remove(source: int) -> None: ...
def exists(source: int) -> bool: ...
def contains(start: int, size: int) -> bool: ...
def in_range(start: int, end: int) -> list[Descriptor]: ...
def first() -> int: ...
def next(address: int) -> int: ...
def prev(address: int) -> int: ...
def all() -> FixupRange: ...
def register_custom(handler: CustomHandler) -> int: ...
def unregister_custom(custom_type: int) -> None: ...
def find_custom(name: str) -> int: ...
