from collections.abc import Iterator
from .type import TypeInfo

class Chunk:
    start: int
    end: int
    is_tail: bool
    owner: int
    @property
    def size(self) -> int: ...
    def __init__(self) -> None: ...

class FrameVariable:
    name: str
    byte_offset: int
    byte_size: int
    comment: str
    is_special: bool
    def __init__(self) -> None: ...

class StackFrame:
    @property
    def local_variables_size(self) -> int: ...
    @property
    def saved_registers_size(self) -> int: ...
    @property
    def arguments_size(self) -> int: ...
    @property
    def total_size(self) -> int: ...
    @property
    def variables(self) -> list[FrameVariable]: ...

class Function:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def bitness(self) -> int: ...
    @property
    def returns(self) -> bool: ...
    @property
    def is_library(self) -> bool: ...
    @property
    def is_thunk(self) -> bool: ...
    @property
    def is_visible(self) -> bool: ...
    @property
    def frame_local_size(self) -> int: ...
    @property
    def frame_regs_size(self) -> int: ...
    @property
    def frame_args_size(self) -> int: ...
    def refresh(self) -> None: ...

class RegisterVariable:
    range_start: int
    range_end: int
    canonical_name: str
    user_name: str
    comment: str
    def __init__(self) -> None: ...

class FunctionRange:
    def __iter__(self) -> Iterator[Function]: ...

def create(start: int, end: int = ...) -> Function: ...
def remove(address: int) -> None: ...
def at(address: int) -> Function: ...
def by_index(index: int) -> Function: ...
def count() -> int: ...
def name_at(address: int) -> str: ...
def set_start(address: int, new_start: int) -> None: ...
def set_end(address: int, new_end: int) -> None: ...
def update(address: int) -> None: ...
def reanalyze(address: int) -> None: ...
def is_outlined(address: int) -> bool: ...
def set_outlined(address: int, outlined: bool) -> None: ...
def comment(address: int, repeatable: bool = ...) -> str: ...
def set_comment(address: int, text: str,
                repeatable: bool = ...) -> None: ...
def callers(address: int) -> list[int]: ...
def callees(address: int) -> list[int]: ...
def chunks(address: int) -> list[Chunk]: ...
def tail_chunks(address: int) -> list[Chunk]: ...
def chunk_count(address: int) -> int: ...
def add_tail(function_address: int, tail_start: int, tail_end: int) -> None: ...
def remove_tail(function_address: int, tail_address: int) -> None: ...
def frame(address: int) -> StackFrame: ...
def sp_delta_at(address: int) -> int: ...
def frame_variable_by_name(address: int, name: str) -> FrameVariable: ...
def frame_variable_by_offset(address: int,
                             byte_offset: int) -> FrameVariable: ...
def define_stack_variable(function_address: int, name: str, frame_offset: int,
                          type: TypeInfo) -> None: ...
def set_prototype(function_address: int, type: TypeInfo) -> None: ...
def apply_decl(function_address: int, c_declaration: str) -> None: ...
def declaration(function_address: int, name_override: str = ...) -> str: ...
def add_register_variable(function_address: int, range_start: int,
                          range_end: int, register_name: str,
                          user_name: str, comment: str = ...) -> None: ...
def find_register_variable(function_address: int, address: int,
                           register_name: str) -> RegisterVariable: ...
def remove_register_variable(function_address: int, range_start: int,
                             range_end: int, register_name: str) -> None: ...
def rename_register_variable(function_address: int, address: int,
                             register_name: str,
                             new_user_name: str) -> None: ...
def has_register_variables(function_address: int, address: int) -> bool: ...
def register_variables(address: int) -> list[RegisterVariable]: ...
def item_addresses(address: int) -> list[int]: ...
def code_addresses(address: int) -> list[int]: ...
def all() -> FunctionRange: ...
