"""Function snapshots, frames, chunks, and relationships."""

from ._native.function import (
    Chunk,
    FrameVariable,
    Function,
    FunctionRange,
    RegisterVariable,
    StackFrame,
    add_register_variable,
    add_tail,
    all,
    apply_decl,
    at,
    by_index,
    callees,
    callers,
    chunk_count,
    chunks,
    code_addresses,
    comment,
    count,
    create,
    declaration,
    define_stack_variable,
    find_register_variable,
    frame,
    frame_variable_by_name,
    frame_variable_by_offset,
    has_register_variables,
    is_outlined,
    item_addresses,
    name_at,
    reanalyze,
    register_variables,
    remove,
    remove_register_variable,
    remove_tail,
    rename_register_variable,
    set_comment,
    set_end,
    set_outlined,
    set_prototype,
    set_start,
    sp_delta_at,
    tail_chunks,
    update,
)

__all__ = [
    "Chunk", "FrameVariable", "Function", "FunctionRange", "RegisterVariable",
    "StackFrame", "add_register_variable", "add_tail", "all", "apply_decl",
    "at", "by_index", "callees", "callers", "chunk_count", "chunks",
    "code_addresses", "comment", "count", "create", "declaration",
    "define_stack_variable", "find_register_variable", "frame",
    "frame_variable_by_name", "frame_variable_by_offset",
    "has_register_variables", "is_outlined", "item_addresses", "name_at",
    "reanalyze", "register_variables", "remove", "remove_register_variable",
    "remove_tail", "rename_register_variable", "set_comment", "set_end",
    "set_outlined", "set_prototype", "set_start", "sp_delta_at",
    "tail_chunks", "update",
]
