from enum import Enum
from .address import Range

class Layout(Enum):
    NONE = ...
    DIGRAPH = ...
    TREE = ...
    CIRCLE = ...
    POLAR_TREE = ...
    ORTHOGONAL = ...
    RADIAL_TREE = ...

class BlockType(Enum):
    NORMAL = ...
    INDIRECT_JUMP = ...
    RETURN = ...
    CONDITIONAL_RETURN = ...
    NO_RETURN = ...
    EXTERNAL_NO_RETURN = ...
    EXTERNAL = ...
    ERROR = ...

class Edge:
    source: int
    target: int
    def __init__(self) -> None: ...

class NodeInfo:
    background_color: int
    frame_color: int
    address: int
    text: str
    def __init__(self) -> None: ...

class EdgeInfo:
    color: int
    width: int
    source_port: int
    target_port: int
    def __init__(self) -> None: ...

class BasicBlock:
    start: int
    end: int
    type: BlockType
    successors: list[int]
    predecessors: list[int]
    def __init__(self) -> None: ...

class SwitchTable:
    table_address: int
    entry_count: int
    entry_size: int
    def __init__(self) -> None: ...

class Graph:
    def __init__(self) -> None: ...
    def add_node(self) -> int: ...
    def remove_node(self, node: int) -> None: ...
    @property
    def total_node_count(self) -> int: ...
    @property
    def visible_node_count(self) -> int: ...
    def node_exists(self, node: int) -> bool: ...
    def add_edge(self, source: int, target: int,
                 info: EdgeInfo | None = ...) -> None: ...
    def remove_edge(self, source: int, target: int) -> None: ...
    def replace_edge(self, source: int, target: int,
                     new_source: int, new_target: int) -> None: ...
    def successors(self, node: int) -> list[int]: ...
    def predecessors(self, node: int) -> list[int]: ...
    def visible_nodes(self) -> list[int]: ...
    def edges(self) -> list[Edge]: ...
    def path_exists(self, source: int, target: int) -> bool: ...
    def create_group(self, nodes: list[int]) -> int: ...
    def delete_group(self, group: int) -> None: ...
    def set_group_expanded(self, group: int, expanded: bool) -> None: ...
    def is_group(self, node: int) -> bool: ...
    def is_collapsed(self, group: int) -> bool: ...
    def group_members(self, group: int) -> list[int]: ...
    def set_layout(self, layout: Layout) -> None: ...
    @property
    def current_layout(self) -> Layout: ...
    def redo_layout(self) -> None: ...
    def clear(self) -> None: ...

class GraphCallback:
    def __init__(self) -> None: ...
    def on_refresh(self, graph: Graph) -> bool: ...
    def on_node_text(self, node: int) -> str: ...
    def on_node_color(self, node: int) -> int: ...
    def on_clicked(self, node: int) -> bool: ...
    def on_double_clicked(self, node: int) -> bool: ...
    def on_hint(self, node: int) -> str: ...
    def on_creating_group(self, nodes: list[int]) -> bool: ...
    def on_destroyed(self) -> None: ...

def show_graph(title: str, graph: Graph,
               callback: GraphCallback | None = ...) -> None: ...
def refresh_graph(title: str) -> None: ...
def has_graph_viewer(title: str) -> bool: ...
def is_graph_viewer_visible(title: str) -> bool: ...
def activate_graph_viewer(title: str) -> None: ...
def close_graph_viewer(title: str) -> None: ...
def switch_table(jump_address: int) -> SwitchTable: ...
def flowchart(function_address: int) -> list[BasicBlock]: ...
def flowchart_for_ranges(ranges: list[Range]) -> list[BasicBlock]: ...
