from enum import Enum

class OperandType(Enum):
    NONE = ...
    REGISTER = ...
    MEMORY_DIRECT = ...
    MEMORY_PHRASE = ...
    MEMORY_DISPLACEMENT = ...
    IMMEDIATE = ...
    FAR_ADDRESS = ...
    NEAR_ADDRESS = ...
    PROCESSOR_SPECIFIC_0 = ...
    PROCESSOR_SPECIFIC_1 = ...
    PROCESSOR_SPECIFIC_2 = ...
    PROCESSOR_SPECIFIC_3 = ...
    PROCESSOR_SPECIFIC_4 = ...
    PROCESSOR_SPECIFIC_5 = ...

class OperandFormat(Enum):
    DEFAULT = ...
    HEX = ...
    DECIMAL = ...
    OCTAL = ...
    BINARY = ...
    CHARACTER = ...
    FLOAT = ...
    OFFSET = ...
    STACK_VARIABLE = ...

class RegisterCategory(Enum):
    UNKNOWN = ...
    GENERAL_PURPOSE = ...
    SEGMENT = ...
    FLOATING_POINT = ...
    VECTOR = ...
    MASK = ...
    CONTROL = ...
    DEBUG = ...
    OTHER = ...

class StructOffsetPath:
    structure_name: str
    member_names: list[str]
    delta: int
    def __init__(self) -> None: ...

class OperandEnum:
    name: str
    serial: int
    def __init__(self) -> None: ...

class Operand:
    @property
    def index(self) -> int: ...
    @property
    def type(self) -> OperandType: ...
    @property
    def is_register(self) -> bool: ...
    @property
    def is_immediate(self) -> bool: ...
    @property
    def is_memory(self) -> bool: ...
    @property
    def register_id(self) -> int: ...
    @property
    def value(self) -> int: ...
    @property
    def target_address(self) -> int: ...
    @property
    def displacement(self) -> int: ...
    @property
    def byte_width(self) -> int: ...
    @property
    def encoded_value_byte_offset(self) -> int | None: ...
    @property
    def secondary_encoded_value_byte_offset(self) -> int | None: ...
    @property
    def register_name(self) -> str: ...
    @property
    def is_read(self) -> bool: ...
    @property
    def is_written(self) -> bool: ...
    @property
    def register_category(self) -> RegisterCategory: ...
    @property
    def is_vector_register(self) -> bool: ...
    @property
    def is_mask_register(self) -> bool: ...

class Instruction:
    @property
    def address(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def opcode(self) -> int: ...
    @property
    def mnemonic(self) -> str: ...
    @property
    def operand_count(self) -> int: ...
    def operand(self, index: int) -> Operand: ...
    @property
    def operands(self) -> list[Operand]: ...

def decode(address: int) -> Instruction: ...
def create(address: int) -> Instruction: ...
def text(address: int) -> str: ...
def set_operand_hex(address: int, operand_index: int) -> None: ...
def set_operand_decimal(address: int, operand_index: int) -> None: ...
def set_operand_octal(address: int, operand_index: int) -> None: ...
def set_operand_binary(address: int, operand_index: int) -> None: ...
def set_operand_character(address: int, operand_index: int) -> None: ...
def set_operand_float(address: int, operand_index: int) -> None: ...
def set_operand_format(address: int, operand_index: int, format: OperandFormat,
                       base: int = ...) -> None: ...
def set_operand_offset(address: int, operand_index: int,
                       base: int = ...) -> None: ...
def set_operand_enum(address: int, operand_index: int, enum_name: str,
                     serial: int = ...) -> None: ...
def operand_enum(address: int, operand_index: int) -> OperandEnum: ...
def set_operand_struct_offset(address: int, operand_index: int,
                              structure_name: str, delta: int = ...) -> None: ...
def ensure_operand_struct_member_offset(address: int, operand_index: int,
                                        structure_name: str,
                                        member_byte_offset: int,
                                        delta: int = ...) -> bool: ...
def set_operand_based_struct_offset(address: int, operand_index: int,
                                    operand_value: int, base: int) -> None: ...
def operand_struct_offset_path(address: int,
                               operand_index: int) -> StructOffsetPath: ...
def operand_struct_offset_path_names(address: int,
                                     operand_index: int) -> list[str]: ...
def set_operand_stack_variable(address: int, operand_index: int) -> None: ...
def clear_operand_representation(address: int, operand_index: int) -> None: ...
def set_forced_operand(address: int, operand_index: int, text: str) -> None: ...
def get_forced_operand(address: int, operand_index: int) -> str: ...
def operand_text(address: int, operand_index: int) -> str: ...
def operand_byte_width(address: int, operand_index: int) -> int: ...
def operand_register_name(address: int, operand_index: int) -> str: ...
def operand_register_category(address: int,
                              operand_index: int) -> RegisterCategory: ...
def toggle_operand_sign(address: int, operand_index: int) -> None: ...
def toggle_operand_negate(address: int, operand_index: int) -> None: ...
def code_refs_from(address: int) -> list[int]: ...
def data_refs_from(address: int) -> list[int]: ...
def call_targets(address: int) -> list[int]: ...
def jump_targets(address: int) -> list[int]: ...
def has_fall_through(address: int) -> bool: ...
def is_call(address: int) -> bool: ...
def is_return(address: int) -> bool: ...
def is_jump(address: int) -> bool: ...
def is_conditional_jump(address: int) -> bool: ...
def next(address: int) -> Instruction: ...
def prev(address: int) -> Instruction: ...
