"""Instruction decode, operands, display, and xrefs."""

from ._native.instruction import (
    Instruction,
    Operand,
    OperandEnum,
    OperandFormat,
    OperandType,
    RegisterCategory,
    StructOffsetPath,
    call_targets,
    clear_operand_representation,
    code_refs_from,
    create,
    data_refs_from,
    decode,
    ensure_operand_struct_member_offset,
    get_forced_operand,
    has_fall_through,
    is_call,
    is_conditional_jump,
    is_jump,
    is_return,
    jump_targets,
    next,
    operand_byte_width,
    operand_enum,
    operand_register_category,
    operand_register_name,
    operand_struct_offset_path,
    operand_struct_offset_path_names,
    operand_text,
    prev,
    set_forced_operand,
    set_operand_based_struct_offset,
    set_operand_binary,
    set_operand_character,
    set_operand_decimal,
    set_operand_enum,
    set_operand_float,
    set_operand_format,
    set_operand_hex,
    set_operand_octal,
    set_operand_offset,
    set_operand_stack_variable,
    set_operand_struct_offset,
    text,
    toggle_operand_negate,
    toggle_operand_sign,
)

__all__ = [
    "Instruction", "Operand", "OperandEnum", "OperandFormat", "OperandType",
    "RegisterCategory", "StructOffsetPath", "call_targets",
    "clear_operand_representation", "code_refs_from", "create",
    "data_refs_from", "decode", "ensure_operand_struct_member_offset",
    "get_forced_operand", "has_fall_through", "is_call",
    "is_conditional_jump", "is_jump", "is_return", "jump_targets", "next",
    "operand_byte_width", "operand_enum", "operand_register_category",
    "operand_register_name", "operand_struct_offset_path",
    "operand_struct_offset_path_names", "operand_text", "prev",
    "set_forced_operand", "set_operand_based_struct_offset",
    "set_operand_binary", "set_operand_character", "set_operand_decimal",
    "set_operand_enum", "set_operand_float", "set_operand_format",
    "set_operand_hex", "set_operand_octal", "set_operand_offset",
    "set_operand_stack_variable", "set_operand_struct_offset", "text",
    "toggle_operand_negate", "toggle_operand_sign",
]
