from enum import IntEnum
from typing import Final
from .address import Range

class SourceFile:
    filename: str
    range: Range
    def __init__(self) -> None: ...

class Color(IntEnum):
    DEFAULT = ...
    REGULAR_COMMENT = ...
    REPEATABLE_COMMENT = ...
    AUTO_COMMENT = ...
    INSTRUCTION = ...
    DATA_NAME = ...
    REGULAR_DATA_NAME = ...
    DEMANGLED_NAME = ...
    SYMBOL = ...
    CHAR_LITERAL = ...
    STRING = ...
    NUMBER = ...
    VOID = ...
    CODE_REFERENCE = ...
    DATA_REFERENCE = ...
    CODE_REF_TAIL = ...
    DATA_REF_TAIL = ...
    ERROR = ...
    PREFIX = ...
    BINARY_PREFIX = ...
    EXTRA = ...
    ALT_OPERAND = ...
    HIDDEN_NAME = ...
    LIBRARY_NAME = ...
    LOCAL_NAME = ...
    DUMMY_CODE_NAME = ...
    ASM_DIRECTIVE = ...
    MACRO = ...
    DATA_STRING = ...
    DATA_CHAR = ...
    DATA_NUMBER = ...
    KEYWORD = ...
    REGISTER = ...
    IMPORTED_NAME = ...
    SEGMENT_NAME = ...
    UNKNOWN_NAME = ...
    CODE_NAME = ...
    USER_NAME = ...
    COLLAPSED = ...

COLOR_ON: Final[int]
COLOR_OFF: Final[int]
COLOR_ESC: Final[int]
COLOR_INV: Final[int]
COLOR_ADDR: Final[int]
COLOR_ADDR_SIZE: Final[int]

def add_source_file(range: Range, filename: str) -> None: ...
def source_file_at(address: int) -> SourceFile: ...
def remove_source_file(address: int) -> None: ...
def colstr(text: str, color: Color) -> str: ...
def tag_remove(tagged_text: str) -> str: ...
def tag_advance(tagged_text: str, position: int) -> int: ...
def tag_strlen(tagged_text: str) -> int: ...
def make_addr_tag(item_index: int) -> str: ...
def decode_addr_tag(tagged_text: str, position: int) -> int: ...
