from typing import TypeAlias

Buffer: TypeAlias = bytes | bytearray | memoryview

class InputFile:
    def size(self) -> int: ...
    def tell(self) -> int: ...
    def seek(self, offset: int) -> int: ...
    def read_bytes(self, count: int) -> bytes: ...
    def read_bytes_at(self, offset: int, count: int) -> bytes: ...
    def read_string(self, offset: int, max_length: int = ...) -> str: ...
    def filename(self) -> str: ...

class OutputFile:
    def write(self, data: Buffer) -> int: ...
    def flush(self) -> None: ...
    def tell(self) -> int: ...

class AcceptResult:
    format_name: str
    processor_name: str
    priority: int
    archive_loader: bool
    continue_probe: bool
    prefer_first: bool
    def __init__(self) -> None: ...

class LoaderOptions:
    supports_reload: bool
    requires_processor: bool
    def __init__(self) -> None: ...

class LoadFlags:
    create_segments: bool
    load_resources: bool
    rename_entries: bool
    manual_load: bool
    fill_gaps: bool
    create_import_segment: bool
    first_file: bool
    binary_code_segment: bool
    reload: bool
    auto_flat_group: bool
    mini_database: bool
    loader_options_dialog: bool
    load_all_segments: bool
    def __init__(self) -> None: ...

class LoadRequest:
    format_name: str
    input_name: str
    archive_name: str
    archive_member_name: str
    flags: LoadFlags
    is_remote: bool
    def __init__(self) -> None: ...

class SaveRequest:
    format_name: str
    capability_query: bool
    is_remote: bool
    def __init__(self) -> None: ...

class MoveSegmentRequest:
    format_name: str
    whole_program_rebase: bool
    reload: bool
    def __init__(self) -> None: ...

class ArchiveMemberRequest:
    archive_name: str
    default_member: str
    flags: LoadFlags
    def __init__(self) -> None: ...

class ArchiveMemberResult:
    extracted_file: str
    member_name: str
    flags: LoadFlags
    def __init__(self) -> None: ...

class Loader:
    def __init__(self) -> None: ...
    def options(self) -> LoaderOptions: ...
    def accept(self, input: InputFile) -> AcceptResult | None: ...
    def load(self, input: InputFile, format_name: str) -> None: ...
    def load_with_request(self, input: InputFile, request: LoadRequest) -> None: ...
    def process_archive(self, input: InputFile,
                        request: ArchiveMemberRequest) -> ArchiveMemberResult | None: ...
    def save(self, output: OutputFile | None, format_name: str) -> bool: ...
    def save_with_request(self, output: OutputFile | None,
                          request: SaveRequest) -> bool: ...
    def move_segment(self, from_address: int, to_address: int, size: int,
                     format_name: str = ...) -> None: ...
    def move_segment_with_request(self, from_address: int, to_address: int,
                                  size: int, request: MoveSegmentRequest) -> None: ...

def decode_load_flags(raw_flags: int) -> LoadFlags: ...
def encode_load_flags(flags: LoadFlags) -> int: ...
def file_to_database(input: InputFile, file_offset: int, address: int,
                     size: int, patchable: bool = ...) -> None: ...
def memory_to_database(data: Buffer, address: int, size: int | None = ...) -> None: ...
def set_processor(processor_name: str) -> None: ...
def create_filename_comment() -> None: ...
def abort_load(message: str) -> None: ...
