from collections.abc import Sequence
from enum import Enum, IntEnum

class Feature(Enum):
    PRIMARY_METADATA = ...
    DECOMPILER = ...
    TELEMETRY = ...
    SECONDARY_METADATA = ...

class PushMode(Enum):
    PREFER_BETTER_OR_DIFFERENT = ...
    OVERRIDE = ...
    KEEP_EXISTING = ...
    MERGE = ...

class OperationCode(IntEnum):
    BAD_PATTERN = ...
    NOT_FOUND = ...
    ERROR = ...
    OK = ...
    ADDED = ...

class BatchResult:
    requested: int
    completed: int
    succeeded: int
    failed: int
    codes: list[OperationCode]
    def __init__(self) -> None: ...

def has_connection(feature: Feature = ...) -> bool: ...
def close_connection(feature: Feature = ...) -> None: ...
def close_all_connections() -> None: ...
def pull(addresses: int | Sequence[int], auto_apply: bool = ...,
         skip_frequency_update: bool = ...,
         feature: Feature = ...) -> BatchResult: ...
def push(addresses: int | Sequence[int], mode: PushMode = ...,
         feature: Feature = ...) -> BatchResult: ...
