from enum import Enum
from typing import overload

class DemangleForm(Enum):
    SHORT = ...
    LONG = ...
    FULL = ...

class Entry:
    address: int
    name: str
    user_defined: bool
    auto_generated: bool
    def __init__(self) -> None: ...

class ListOptions:
    start: int
    end: int
    include_user_defined: bool
    include_auto_generated: bool
    def __init__(self) -> None: ...

def set(address: int, name: str) -> None: ...
def force_set(address: int, name: str) -> None: ...
def remove(address: int) -> None: ...
def get(address: int) -> str: ...
@overload
def demangled(value: int, form: DemangleForm = ...) -> str: ...
@overload
def demangled(value: str, form: DemangleForm = ...) -> str: ...
def resolve(name: str, context: int = ...) -> int: ...
def all(options: ListOptions = ...) -> list[Entry]: ...
def all_user_defined(start: int = ..., end: int = ...) -> list[Entry]: ...
def is_public(address: int) -> bool: ...
def is_weak(address: int) -> bool: ...
def is_user_defined(address: int) -> bool: ...
def is_auto_generated(address: int) -> bool: ...
def is_valid_identifier(text: str) -> bool: ...
def sanitize_identifier(text: str) -> str: ...
def set_public(address: int, value: bool = ...) -> None: ...
def set_weak(address: int, value: bool = ...) -> None: ...
