class Entry:
    def __init__(self) -> None: ...
    address: int
    channel: str
    metadata: str

class History:
    @property
    def name(self) -> str: ...
    @property
    def created(self) -> bool: ...
    @property
    def entries(self) -> list[Entry]: ...
    @property
    def size(self) -> int: ...
    @property
    def index(self) -> int: ...
    @property
    def current(self) -> Entry: ...
    def current_for(self, channel: str) -> Entry | None: ...
    @property
    def all_current(self) -> list[Entry]: ...
    def set_current(self, entry: Entry, record_in_history: bool = ...) -> None: ...
    def push(self, entry: Entry) -> Entry: ...
    def seek(self, index: int) -> Entry: ...
    def back(self, count: int = ...) -> Entry | None: ...
    def forward(self, count: int = ...) -> Entry | None: ...
    def replace(self, index: int, entry: Entry) -> None: ...
    def clear(self, new_tip: Entry) -> None: ...
    def transfer_channel_to(
        self,
        destination: History,
        channel: str,
        retain_history: bool = ...,
    ) -> None: ...

def open(name: str, initial: Entry) -> History: ...
