"""Opaque operand offset and reference semantics."""

from ._native.offset import (
    ExpressionComplexity,
    OperandLocation,
    ReferenceCalculation,
    ReferenceInfo,
    ReferenceKind,
    ReferenceOptions,
    ReferenceType,
    ReferenceTypeDescriptor,
    RenderedExpression,
    RenderOptions,
    add_operand_data_references,
    apply_reference,
    calculate_base_value,
    calculate_offset_base,
    calculate_reference,
    default_reference_type,
    possible_offset32_target,
    probable_base,
    reference_info,
    reference_types,
    remove_reference,
    render_expression,
    render_stored_expression,
)

__all__ = [
    "ExpressionComplexity",
    "OperandLocation",
    "ReferenceCalculation",
    "ReferenceInfo",
    "ReferenceKind",
    "ReferenceOptions",
    "ReferenceType",
    "ReferenceTypeDescriptor",
    "RenderedExpression",
    "RenderOptions",
    "add_operand_data_references",
    "apply_reference",
    "calculate_base_value",
    "calculate_offset_base",
    "calculate_reference",
    "default_reference_type",
    "possible_offset32_target",
    "probable_base",
    "reference_info",
    "reference_types",
    "remove_reference",
    "render_expression",
    "render_stored_expression",
]
