from enum import Enum
from .xref import DataType

class ReferenceKind(Enum):
    OFFSET8 = ...
    OFFSET16 = ...
    OFFSET32 = ...
    OFFSET64 = ...
    LOW8 = ...
    LOW16 = ...
    LOW32 = ...
    HIGH8 = ...
    HIGH16 = ...
    HIGH32 = ...
    CUSTOM = ...

class ReferenceType:
    kind: ReferenceKind
    custom_name: str
    def __init__(self, kind: ReferenceKind = ...,
                 custom_name: str = ...) -> None: ...

class ReferenceTypeDescriptor:
    @property
    def type(self) -> ReferenceType: ...
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def target_optional(self) -> bool: ...

class OperandLocation:
    index: int
    outer: bool
    def __init__(self, index: int = ..., outer: bool = ...) -> None: ...

class ReferenceOptions:
    relative_virtual_address: bool
    allow_past_end: bool
    suppress_base_reference: bool
    subtract_operand: bool
    sign_extend_operand: bool
    accept_zero: bool
    reject_all_ones: bool
    self_relative: bool
    ignore_fixup: bool
    def __init__(self) -> None: ...

class ReferenceInfo:
    type: ReferenceType
    target: int | None
    base: int | None
    target_delta: int
    options: ReferenceOptions
    def __init__(self) -> None: ...

class ExpressionComplexity(Enum):
    SIMPLE = ...
    COMPLEX = ...

class RenderOptions:
    append_zero_field: bool
    avoid_dummy_names: bool
    def __init__(self, append_zero_field: bool = ...,
                 avoid_dummy_names: bool = ...) -> None: ...

class RenderedExpression:
    @property
    def text(self) -> str: ...
    @property
    def complexity(self) -> ExpressionComplexity: ...

class ReferenceCalculation:
    @property
    def target(self) -> int | None: ...
    @property
    def base(self) -> int | None: ...

def reference_types() -> list[ReferenceTypeDescriptor]: ...
def default_reference_type(address: int) -> ReferenceType: ...
def reference_info(address: int,
                   location: OperandLocation) -> ReferenceInfo | None: ...
def apply_reference(address: int, location: OperandLocation,
                    info: ReferenceInfo) -> None: ...
def remove_reference(address: int, location: OperandLocation) -> bool: ...
def render_stored_expression(address: int, location: OperandLocation,
                             from_address: int, operand_value: int,
                             options: RenderOptions = ...) -> RenderedExpression: ...
def render_expression(address: int, location: OperandLocation,
                      info: ReferenceInfo, from_address: int,
                      operand_value: int,
                      options: RenderOptions = ...) -> RenderedExpression: ...
def possible_offset32_target(address: int) -> int | None: ...
def calculate_offset_base(address: int,
                          location: OperandLocation) -> int | None: ...
def probable_base(address: int, operand_value: int) -> int | None: ...
def calculate_reference(from_address: int, info: ReferenceInfo,
                        operand_value: int) -> ReferenceCalculation: ...
def add_operand_data_references(instruction_address: int,
                                location: OperandLocation,
                                type: DataType = ...) -> int: ...
def calculate_base_value(target: int, base: int) -> int | None: ...
