from typing import Callable
from .type import TypeInfo

class Info:
    name: str
    hotkey: str
    comment: str
    help: str
    icon: int
    def __init__(self) -> None: ...

class ExportFlags:
    modifies_database: bool
    requests_redraw: bool
    segment_scoped: bool
    unload_after_run: bool
    hidden: bool
    debugger_only: bool
    processor_specific: bool
    load_at_startup: bool
    extra_raw_flags: int
    def __init__(self) -> None: ...

class TypeRef:
    name: str
    type: TypeInfo
    def __init__(self) -> None: ...

class HostHandle:
    @property
    def valid(self) -> bool: ...
    @property
    def kind(self) -> str: ...

class ActionContext:
    action_id: str
    widget_title: str
    widget_type: int
    current_address: int
    current_value: int
    has_selection: bool
    is_external_address: bool
    register_name: str
    type_ref: TypeRef | None
    @property
    def widget_host(self) -> HostHandle: ...
    @property
    def focused_widget_host(self) -> HostHandle: ...
    @property
    def decompiler_view_host(self) -> HostHandle: ...

class Action:
    id: str
    label: str
    hotkey: str
    tooltip: str
    icon: int
    handler: Callable[[], None] | None
    handler_with_context: Callable[[ActionContext], None] | None
    enabled: Callable[[], bool] | None
    enabled_with_context: Callable[[ActionContext], bool] | None
    def __init__(self) -> None: ...

class Plugin:
    def __init__(self) -> None: ...
    def info(self) -> Info: ...
    def init(self) -> bool: ...
    def term(self) -> None: ...
    def run(self, argument: int = ...) -> None: ...

class ScopedHotkey:
    @property
    def active(self) -> bool: ...
    @property
    def hotkey(self) -> str: ...
    def activate(self) -> None: ...
    def release(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> ScopedHotkey: ...
    def __exit__(self, exc_type: object, exc_value: object,
                 traceback: object) -> bool: ...

def widget_host(context: ActionContext) -> HostHandle: ...
def with_widget_host(context: ActionContext,
                     callback: Callable[[HostHandle], None]) -> None: ...
def decompiler_view_host(context: ActionContext) -> HostHandle: ...
def with_decompiler_view_host(context: ActionContext,
                              callback: Callable[[HostHandle], None]) -> None: ...
def register_action(action: Action) -> None: ...
def unregister_action(action_id: str) -> None: ...
def activate_action(action_id: str) -> None: ...
def register_hotkey(hotkey: str, callback: Callable[[], None]) -> ScopedHotkey: ...
def attach_to_menu(target: str, action_id: str) -> None: ...
def attach_to_toolbar(target: str, action_id: str) -> None: ...
def attach_to_popup(target: str, action_id: str) -> None: ...
def detach_from_menu(target: str, action_id: str) -> None: ...
def detach_from_toolbar(target: str, action_id: str) -> None: ...
def detach_from_popup(target: str, action_id: str) -> None: ...
