from enum import Enum, IntFlag

class InstructionFeature(IntFlag):
    NONE = ...
    STOP = ...
    CALL = ...
    CHANGE1 = ...
    CHANGE2 = ...
    CHANGE3 = ...
    CHANGE4 = ...
    CHANGE5 = ...
    CHANGE6 = ...
    USE1 = ...
    USE2 = ...
    USE3 = ...
    USE4 = ...
    USE5 = ...
    USE6 = ...
    JUMP = ...
    SHIFT = ...
    HIGH_LEVEL = ...
    CHANGE7 = ...
    CHANGE8 = ...
    USE7 = ...
    USE8 = ...

class ProcessorFlag(IntFlag):
    NONE = ...
    SEGMENTS = ...
    USE32 = ...
    DEFAULT_SEG32 = ...
    REGISTER_NAMES = ...
    ADJUST_SEGMENTS = ...
    OCTAL_NUMBERS = ...
    DECIMAL_NUMBERS = ...
    BINARY_NUMBERS = ...
    WORD_INSTRUCTIONS = ...
    NO_CHANGE = ...
    ASSEMBLE = ...
    ALIGN_DATA = ...
    TYPE_INFO = ...
    USE64 = ...
    SEGMENT_REGISTERS_OTHER = ...
    STACK_GROWS_UP = ...
    BINARY_MEMORY = ...
    SEGMENT_TRANSLATION = ...
    CHECK_CROSS_REFERENCES = ...
    NO_SEG_MOVE = ...
    USE_ARG_TYPES = ...
    SCALE_STACK_VARIABLES = ...
    DELAYED_BRANCHES = ...
    ALIGN_INSTRUCTIONS = ...
    PURGING = ...
    CONDITIONAL_INSNS = ...
    USE_TBYTE = ...
    DEFAULT_SEG64 = ...
    OUTER_OPERANDS = ...
    HEX_NUMBERS = ...

class ProcessorFlag2(IntFlag):
    NONE = ...
    MAPPINGS = ...
    IDP_OPTIONS = ...
    CODE16_BIT = ...
    MACRO = ...
    USE_CALC_REL = ...
    RELATIVE_BITS = ...
    FORCE16_BIT_TYPES = ...
    IGNORE_IDA_GUESS = ...

class SwitchTableKind(Enum):
    DENSE = ...
    SPARSE = ...
    INDIRECT = ...
    CUSTOM = ...

class EmulateResult(Enum):
    NOT_IMPLEMENTED = ...
    SUCCESS = ...
    DELETE_INSTRUCTION = ...

class OutputOperandResult(Enum):
    NOT_IMPLEMENTED = ...
    SUCCESS = ...
    HIDDEN = ...

class OutputInstructionResult(Enum):
    NOT_IMPLEMENTED = ...
    SUCCESS = ...

class AnalyzeOperandKind(Enum):
    NONE = ...
    REGISTER = ...
    IMMEDIATE = ...
    NEAR_ADDRESS = ...
    FAR_ADDRESS = ...
    DIRECT_MEMORY = ...
    INDIRECT_MEMORY = ...
    DISPLACEMENT = ...
    PROCESSOR_SPECIFIC0 = ...
    PROCESSOR_SPECIFIC1 = ...
    PROCESSOR_SPECIFIC2 = ...
    PROCESSOR_SPECIFIC3 = ...
    PROCESSOR_SPECIFIC4 = ...
    PROCESSOR_SPECIFIC5 = ...

class OutputTokenKind(Enum):
    PLAIN_TEXT = ...
    MNEMONIC = ...
    REGISTER = ...
    IMMEDIATE = ...
    ADDRESS = ...
    SYMBOL = ...
    COMMENT = ...
    KEYWORD = ...
    STRING_LITERAL = ...
    NUMBER = ...
    OPERATOR_SYMBOL = ...
    PUNCTUATION = ...
    WHITESPACE = ...

class RegisterInfo:
    name: str
    read_only: bool
    def __init__(self) -> None: ...

class InstructionDescriptor:
    mnemonic: str
    feature_flags: int
    operand_count: int
    description: str
    privileged: bool
    def __init__(self) -> None: ...

class AssemblerInfo:
    name: str
    comment_prefix: str
    origin: str
    end_directive: str
    string_delim: str
    char_delim: str
    byte_directive: str
    word_directive: str
    dword_directive: str
    qword_directive: str
    oword_directive: str
    float_directive: str
    double_directive: str
    tbyte_directive: str
    align_directive: str
    include_directive: str
    public_directive: str
    weak_directive: str
    external_directive: str
    current_ip_symbol: str
    uppercase_mnemonics: bool
    uppercase_registers: bool
    requires_colon_after_labels: bool
    supports_quoted_names: bool
    def __init__(self) -> None: ...

class ProcessorInfo:
    id: int
    short_names: list[str]
    long_names: list[str]
    flags: int
    flags2: int
    code_bits_per_byte: int
    data_bits_per_byte: int
    registers: list[RegisterInfo]
    code_segment_register: int
    data_segment_register: int
    first_segment_register: int
    last_segment_register: int
    segment_register_size: int
    instructions: list[InstructionDescriptor]
    return_icode: int
    assemblers: list[AssemblerInfo]
    default_bitness: int
    def __init__(self) -> None: ...

class SwitchDescription:
    kind: SwitchTableKind
    jump_table: int
    values_table: int
    default_target: int
    idiom_start: int
    element_base: int
    low_case_value: int
    indirect_low_case_value: int
    case_count: int
    jump_table_entry_count: int
    jump_element_size: int
    value_element_size: int
    shift: int
    expression_register: int
    expression_data_type: int
    has_default: bool
    default_in_table: bool
    values_signed: bool
    subtract_values: bool
    self_relative: bool
    inverted: bool
    user_defined: bool
    def __init__(self) -> None: ...

class SwitchCase:
    values: list[int]
    target: int
    def __init__(self) -> None: ...

class AnalyzeOperand:
    index: int
    kind: AnalyzeOperandKind
    has_register: bool
    register_index: int
    has_immediate: bool
    immediate_value: int
    has_target_address: bool
    target_address: int
    has_displacement: bool
    displacement: int
    data_type_code: int
    processor_flags: int
    def __init__(self) -> None: ...

class AnalyzeDetails:
    instruction_code: int
    size: int
    operands: list[AnalyzeOperand]
    def __init__(self) -> None: ...

class OutputToken:
    kind: OutputTokenKind
    text: str
    def __init__(self) -> None: ...

class OutputContext:
    def __init__(self) -> None: ...
    def token(self, kind: OutputTokenKind, text: str) -> OutputContext: ...
    def append(self, text: str) -> OutputContext: ...
    def mnemonic(self, text: str) -> OutputContext: ...
    def register_name(self, text: str) -> OutputContext: ...
    def symbol(self, text: str) -> OutputContext: ...
    def keyword(self, text: str) -> OutputContext: ...
    def comment(self, text: str) -> OutputContext: ...
    def number(self, text: str) -> OutputContext: ...
    def operator_symbol(self, text: str) -> OutputContext: ...
    def punctuation(self, text: str) -> OutputContext: ...
    def whitespace(self, text: str = ...) -> OutputContext: ...
    def string_literal(self, text: str, quote: str = ...) -> OutputContext: ...
    def immediate(self, value: int, radix: int = ...) -> OutputContext: ...
    def address(self, address: int) -> OutputContext: ...
    def character(self, character: str) -> OutputContext: ...
    def space(self) -> OutputContext: ...
    def comma(self) -> OutputContext: ...
    def clear(self) -> None: ...
    @property
    def empty(self) -> bool: ...
    @property
    def text(self) -> str: ...
    @property
    def tokens(self) -> list[OutputToken]: ...
    def take(self) -> str: ...
    def take_tokens(self) -> list[OutputToken]: ...

class Processor:
    def __init__(self) -> None: ...
    def info(self) -> ProcessorInfo: ...
    def analyze(self, address: int) -> int: ...
    def analyze_with_details(self, address: int) -> AnalyzeDetails: ...
    def emulate(self, address: int) -> EmulateResult: ...
    def output_instruction(self, address: int) -> None: ...
    def output_operand(self, address: int, operand_index: int) -> OutputOperandResult: ...
    def output_mnemonic_with_context(self, address: int,
                                     output: OutputContext) -> OutputInstructionResult: ...
    def output_instruction_with_context(self, address: int,
                                        output: OutputContext) -> OutputInstructionResult: ...
    def output_operand_with_context(self, address: int, operand_index: int,
                                    output: OutputContext) -> OutputOperandResult: ...
    def on_new_file(self, filename: str) -> None: ...
    def on_old_file(self, filename: str) -> None: ...
    def is_call(self, address: int) -> int: ...
    def is_return(self, address: int) -> int: ...
    def may_be_function(self, address: int) -> int: ...
    def is_sane_instruction(self, address: int, no_code_references: bool) -> int: ...
    def is_indirect_jump(self, address: int) -> int: ...
    def is_basic_block_end(self, address: int,
                           call_instruction_stops_block: bool) -> int: ...
    def create_function_frame(self, address: int) -> bool: ...
    def adjust_function_bounds(self, function_start: int, maximum_end: int,
                               suggested_result: int) -> int: ...
    def analyze_function_prolog(self, address: int) -> int: ...
    def calculate_stack_pointer_delta(self, address: int) -> int | None: ...
    def get_return_address_size(self, address: int) -> int: ...
    def detect_switch(self, address: int) -> tuple[int, SwitchDescription | None]: ...
    def calculate_switch_cases(self, address: int,
                               description: SwitchDescription) -> list[SwitchCase] | None: ...
    def create_switch_references(self, address: int,
                                 description: SwitchDescription) -> bool: ...
