from enum import Enum

from . import Address, AddressDelta

class TrackingState(Enum):
    UNDEFINED = 0
    DEAD_END = 1
    ABORTED = 2
    BAD_INSTRUCTION = 3
    UNKNOWN_INSTRUCTION = 4
    FUNCTION_INPUT = 5
    LOOP_VARIANT = 6
    INCOMPATIBLE_VALUES = 7
    TOO_MANY_REFERENCES = 8
    TOO_MANY_VALUES = 9
    CONSTANT = 10
    STACK_POINTER_DELTA = 11

class ReferenceMutation(Enum):
    ADDED = 0
    REMOVED = 1

class ValueOrigin:
    @property
    def address(self) -> Address: ...
    @property
    def instruction_code(self) -> int: ...
    @property
    def short_instruction(self) -> bool: ...
    @property
    def program_counter_based(self) -> bool: ...
    @property
    def global_offset_table_like(self) -> bool: ...

class ValueCandidate:
    @property
    def constant(self) -> int | None: ...
    @property
    def stack_pointer_delta(self) -> AddressDelta | None: ...
    @property
    def origin(self) -> ValueOrigin: ...

class TrackedValue:
    @property
    def state(self) -> TrackingState: ...
    @property
    def candidates(self) -> list[ValueCandidate]: ...
    @property
    def cause(self) -> ValueOrigin | None: ...
    @property
    def aborting_depth(self) -> int | None: ...
    @property
    def description(self) -> str: ...
    @property
    def known(self) -> bool: ...

class NearestValue:
    @property
    def selected_index(self) -> int: ...
    @property
    def register_name(self) -> str: ...
    @property
    def value(self) -> TrackedValue: ...

def track(address: Address, register_name: str, max_depth: int = 0) -> TrackedValue: ...
def constant_at(address: Address, register_name: str, max_depth: int = 0) -> int | None: ...
def stack_delta_at(
    address: Address, register_name: str | None = None
) -> AddressDelta | None: ...
def nearest_at(
    address: Address, first_register: str, second_register: str
) -> NearestValue | None: ...
def clear_control_flow_cache() -> None: ...
def clear_data_reference_cache() -> None: ...
def control_flow_reference_changed(
    from_address: Address, to_address: Address, mutation: ReferenceMutation
) -> None: ...
def data_reference_changed(
    to_address: Address, mutation: ReferenceMutation
) -> None: ...
