from collections.abc import Sequence
from enum import Enum
from typing import TypeAlias

Buffer: TypeAlias = bytes | bytearray | memoryview

class ValueKind(Enum):
    STRING = 1
    BINARY = 3
    INTEGER = 4

class StringListUpdate:
    def __init__(self) -> None: ...
    add: str | None
    remove: str | None
    max_records: int
    ignore_case: bool

class Store:
    @staticmethod
    def open(key: str) -> Store: ...
    @property
    def key(self) -> str: ...
    def child(self, name: str) -> Store: ...
    @property
    def exists(self) -> bool: ...
    def child_keys(self) -> list[str]: ...
    def value_names(self) -> list[str]: ...
    def contains(self, name: str) -> bool: ...
    def value_kind(self, name: str) -> ValueKind | None: ...
    def read_string(self, name: str) -> str | None: ...
    def write_string(self, name: str, value: str) -> None: ...
    def read_binary(self, name: str) -> bytes | None: ...
    def write_binary(self, name: str, value: Buffer) -> None: ...
    def read_integer(self, name: str) -> int | None: ...
    def write_integer(self, name: str, value: int) -> None: ...
    def read_boolean(self, name: str) -> bool | None: ...
    def write_boolean(self, name: str, value: bool) -> None: ...
    def erase_value(self, name: str) -> bool: ...
    def erase_key(self) -> bool: ...
    def erase_tree(self) -> bool: ...
    def read_string_list(self) -> list[str]: ...
    def write_string_list(self, values: Sequence[str]) -> None: ...
    def update_string_list(self, update: StringListUpdate) -> None: ...
