import builtins
from enum import Enum
from typing import overload

from . import Address

class ValueKind(Enum):
    INTEGER = 0
    FLOATING_POINT = 1
    OBJECT = 2
    FUNCTION = 3
    STRING = 4
    OPAQUE_POINTER = 5
    REFERENCE = 6

class DereferenceMode(Enum):
    ONCE = 0
    RECURSIVE = 1

class Value:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, value: int) -> None: ...
    @overload
    def __init__(self, value: str) -> None: ...
    @staticmethod
    def floating(value: float) -> Value: ...
    @staticmethod
    def object() -> Value: ...
    @property
    def kind(self) -> ValueKind: ...
    def as_integer(self) -> int: ...
    def as_floating(self) -> float: ...
    def as_string(self) -> str: ...
    def coerce_integer(self) -> int: ...
    def coerce_floating(self) -> float: ...
    def coerce_string(self) -> str: ...
    def render(self, name: str | None = ..., indent: int = ...) -> str: ...
    def deep_copy(self) -> Value: ...
    @property
    def class_name(self) -> str: ...
    def attribute(self, name: str, use_handler: bool = ...) -> Value: ...
    def set_attribute(
        self, name: str, value: Value, use_handler: bool = ...
    ) -> None: ...
    def attribute_names(self) -> list[str]: ...
    def remove_attribute(self, name: str) -> bool: ...
    def slice(self, begin: int, end: int) -> Value: ...
    def replace_slice(self, begin: int, end: int, replacement: Value) -> None: ...
    def dereference(self, mode: DereferenceMode = ...) -> Value: ...
    def __copy__(self) -> Value: ...
    def __deepcopy__(
        self, memo: dict[builtins.object, builtins.object]
    ) -> Value: ...

class ResolvedName:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, name: str, value: int) -> None: ...
    name: str
    value: int

class CompileOptions:
    def __init__(self) -> None: ...
    only_safe_functions: bool
    resolved_names: list[ResolvedName]

class FileCompileOptions:
    def __init__(self) -> None: ...
    delete_macros_after_compilation: bool
    allow_program_labels: bool
    only_safe_functions: bool

class CompilationResult:
    @property
    def succeeded(self) -> bool: ...
    @property
    def error(self) -> str: ...
    def __bool__(self) -> bool: ...

class ExecutionResult:
    @property
    def succeeded(self) -> bool: ...
    @property
    def value(self) -> Value: ...
    @property
    def error(self) -> str: ...
    def __bool__(self) -> bool: ...

class IntegerExecutionResult:
    @property
    def succeeded(self) -> bool: ...
    @property
    def value(self) -> int: ...
    @property
    def error(self) -> str: ...
    def __bool__(self) -> bool: ...

def evaluate(expression: str, where: Address = ...) -> ExecutionResult: ...
def evaluate_idc(expression: str, where: Address = ...) -> ExecutionResult: ...
def evaluate_integer(
    expression: str, where: Address = ...
) -> IntegerExecutionResult: ...
def compile_file(
    path: str, options: FileCompileOptions = ...
) -> CompilationResult: ...
def compile_text(
    source: str, options: CompileOptions = ...
) -> CompilationResult: ...
def compile_snippet(
    function_name: str, body: str, options: CompileOptions = ...
) -> CompilationResult: ...
def call(
    function_name: str,
    arguments: list[Value] = ...,
    resolved_names: list[ResolvedName] = ...,
) -> ExecutionResult: ...
def execute_script(
    path: str,
    function_name: str,
    arguments: list[Value] = ...,
    options: FileCompileOptions = ...,
) -> ExecutionResult: ...
def evaluate_snippet(
    source: str, resolved_names: list[ResolvedName] = ...
) -> ExecutionResult: ...
def set_include_paths(paths: list[str]) -> None: ...
def append_include_paths(paths: list[str]) -> None: ...
def resolve_file(file: str) -> str | None: ...
def execute_system_script(file: str, complain_if_missing: bool = ...) -> None: ...
def function_names(prefix: str = ..., maximum: int = ...) -> list[str]: ...
def global_value(name: str) -> Value | None: ...
def set_global(name: str, value: Value) -> bool: ...
def reference_global(name: str) -> Value: ...
