from collections.abc import Iterator
from enum import Enum
from typing import overload

class Type(Enum):
    NORMAL = ...
    EXTERNAL = ...
    CODE = ...
    DATA = ...
    BSS = ...
    ABSOLUTE_SYMBOLS = ...
    COMMON = ...
    NULL = ...
    UNDEFINED = ...
    IMPORT = ...
    INTERNAL_MEMORY = ...
    GROUP = ...

class Permissions:
    read: bool
    write: bool
    execute: bool
    def __init__(self, read: bool = ..., write: bool = ...,
                 execute: bool = ...) -> None: ...

class SegmentRegisterSource(Enum):
    INHERITED = ...
    USER = ...
    ANALYSIS = ...
    ANALYSIS_AT_SEGMENT_START = ...

class SegmentRegisterDescriptor:
    @property
    def name(self) -> str: ...
    @property
    def bit_width(self) -> int: ...
    @property
    def is_code(self) -> bool: ...
    @property
    def is_data(self) -> bool: ...

class SegmentRegisterRange:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def value(self) -> int | None: ...
    @property
    def source(self) -> SegmentRegisterSource: ...

class Segment:
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def bitness(self) -> int: ...
    @property
    def type(self) -> Type: ...
    @property
    def permissions(self) -> Permissions: ...
    @property
    def name(self) -> str: ...
    @property
    def class_name(self) -> str: ...
    @property
    def is_visible(self) -> bool: ...
    def refresh(self) -> None: ...

class SegmentRange:
    def __iter__(self) -> Iterator[Segment]: ...

def create(start: int, end: int, name: str, class_name: str = ...,
           type: Type = ...) -> Segment: ...
def remove(address: int) -> None: ...
def at(address: int) -> Segment: ...
def by_name(name: str) -> Segment: ...
def by_index(index: int) -> Segment: ...
def count() -> int: ...
def set_name(address: int, name: str) -> None: ...
def set_class(address: int, class_name: str) -> None: ...
def set_type(address: int, type: Type) -> None: ...
def set_permissions(address: int, permissions: Permissions) -> None: ...
def set_bitness(address: int, bits: int) -> None: ...
def segment_registers() -> list[SegmentRegisterDescriptor]: ...
def segment_register_value(address: int, register_name: str) -> int | None: ...
def default_segment_register_value(address: int,
                                   register_name: str) -> int | None: ...
def segment_register_range(address: int,
                           register_name: str) -> SegmentRegisterRange: ...
def previous_segment_register_range(address: int,
                                    register_name: str) -> SegmentRegisterRange | None: ...
def segment_register_ranges(register_name: str) -> list[SegmentRegisterRange]: ...
def segment_register_range_index(address: int,
                                 register_name: str) -> int | None: ...
def split_segment_register_range(address: int, register_name: str,
                                 value: int | None,
                                 source: SegmentRegisterSource = ...) -> None: ...
def remove_segment_register_range(range_start: int,
                                  register_name: str) -> None: ...
@overload
def set_default_segment_register(address: int, register_name: str,
                                 value: int | None) -> None: ...
@overload
def set_default_segment_register(address: int, register_index: int,
                                 value: int) -> None: ...
@overload
def set_default_segment_register_for_all(register_name: str,
                                         value: int | None) -> None: ...
@overload
def set_default_segment_register_for_all(register_index: int,
                                         value: int) -> None: ...
def set_default_data_segment(value: int | None) -> None: ...
def set_segment_register_at_next_code(search_start: int, maximum: int,
                                      register_name: str,
                                      value: int | None) -> None: ...
def copy_segment_register_ranges(destination_register: str,
                                 source_register: str,
                                 map_selectors_to_addresses: bool = ...) -> None: ...
def comment(address: int, repeatable: bool = ...) -> str: ...
def set_comment(address: int, text: str,
                repeatable: bool = ...) -> None: ...
def resize(address: int, new_start: int, new_end: int) -> None: ...
def move(address: int, new_start: int) -> None: ...
def all() -> SegmentRange: ...
def first() -> Segment: ...
def last() -> Segment: ...
def next(address: int) -> Segment: ...
def prev(address: int) -> Segment: ...
