"""Segment snapshots, mutation, lookup, and traversal."""

from ._native.segment import (
    Permissions,
    Segment,
    SegmentRange,
    SegmentRegisterDescriptor,
    SegmentRegisterRange,
    SegmentRegisterSource,
    Type,
    all,
    at,
    by_index,
    by_name,
    comment,
    copy_segment_register_ranges,
    count,
    create,
    default_segment_register_value,
    first,
    last,
    move,
    next,
    prev,
    remove,
    remove_segment_register_range,
    resize,
    set_bitness,
    set_class,
    set_comment,
    set_default_segment_register,
    set_default_segment_register_for_all,
    set_default_data_segment,
    set_name,
    set_permissions,
    set_segment_register_at_next_code,
    set_type,
    segment_register_range,
    segment_register_range_index,
    segment_register_ranges,
    segment_register_value,
    segment_registers,
    split_segment_register_range,
    previous_segment_register_range,
)

__all__ = [
    "Permissions", "Segment", "SegmentRange", "SegmentRegisterDescriptor",
    "SegmentRegisterRange", "SegmentRegisterSource", "Type", "all", "at",
    "by_index", "by_name", "comment", "copy_segment_register_ranges",
    "count", "create", "default_segment_register_value", "first", "last",
    "move", "next", "prev", "previous_segment_register_range", "remove",
    "remove_segment_register_range", "resize", "segment_register_range",
    "segment_register_range_index", "segment_register_ranges",
    "segment_register_value", "segment_registers", "set_bitness", "set_class",
    "set_comment", "set_default_data_segment", "set_default_segment_register",
    "set_default_segment_register_for_all", "set_name", "set_permissions",
    "set_segment_register_at_next_code", "set_type",
    "split_segment_register_range",
]
