from os import PathLike

_Buffer = bytes | bytearray | memoryview

class Node:
    def __init__(self) -> None: ...
    @staticmethod
    def open(name: str, create: bool = ...) -> Node: ...
    @staticmethod
    def open_by_id(node_id: int) -> Node: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    def alt(self, index: int, tag: int = ...) -> int: ...
    def set_alt(self, index: int, value: int, tag: int = ...) -> None: ...
    def remove_alt(self, index: int, tag: int = ...) -> None: ...
    def sup(self, index: int, tag: int = ...) -> bytes: ...
    def set_sup(self, index: int, data: _Buffer, tag: int = ...) -> None: ...
    def hash(self, key: str, tag: int = ...) -> str: ...
    def set_hash(self, key: str, value: str, tag: int = ...) -> None: ...
    def blob_size(self, index: int, tag: int = ...) -> int: ...
    def blob(self, index: int, tag: int = ...) -> bytes: ...
    def set_blob(self, index: int, data: _Buffer, tag: int = ...) -> None: ...
    def remove_blob(self, index: int, tag: int = ...) -> None: ...
    def blob_string(self, index: int, tag: int = ...) -> str: ...
