from enum import Enum

class CallingConvention(Enum):
    UNKNOWN = ...
    CDECL = ...
    STDCALL = ...
    PASCAL = ...
    FASTCALL = ...
    THISCALL = ...
    SWIFT = ...
    GOLANG = ...
    USER_DEFINED = ...

class TypeKind(Enum):
    UNKNOWN = ...
    VOID = ...
    BOOL = ...
    CHARACTER = ...
    SIGNED_INTEGER = ...
    UNSIGNED_INTEGER = ...
    FLOATING_POINT = ...
    POINTER = ...
    ARRAY = ...
    FUNCTION = ...
    STRUCT = ...
    UNION = ...
    ENUM = ...
    TYPEDEF = ...

class EnumRadix(Enum):
    UNKNOWN = ...
    BINARY = ...
    OCTAL = ...
    DECIMAL = ...
    HEXADECIMAL = ...

class EnumMember:
    name: str
    value: int
    comment: str
    def __init__(self) -> None: ...

class ParseDeclarationsOptions:
    suppress_warnings: bool
    relaxed_namespaces: bool
    raw_argument_names: bool
    no_mangle: bool
    pack_alignment: int
    def __init__(self) -> None: ...

class ParseDeclarationsReport:
    error_count: int
    @property
    def ok(self) -> bool: ...
    def __init__(self) -> None: ...
    def __bool__(self) -> bool: ...

class UsedMemberOffsets:
    type_name: str
    byte_offsets: list[int]
    def __init__(self) -> None: ...

class TypeRenderOptions:
    size_comments: bool
    trim_unreferenced: bool
    used_offsets: list[UsedMemberOffsets]
    def __init__(self) -> None: ...

class TypeGraphOptions:
    class Mode(Enum):
        SIMPLE = ...
        TABLE = ...
    mode: Mode
    max_depth: int
    include_enums: bool
    include_typedefs: bool
    def __init__(self) -> None: ...

class TypeDeclaration:
    ordinal: int
    name: str
    declaration: str
    def __init__(self) -> None: ...

class TypeInfo:
    def __init__(self) -> None: ...
    @staticmethod
    def void_type() -> TypeInfo: ...
    @staticmethod
    def int8() -> TypeInfo: ...
    @staticmethod
    def int16() -> TypeInfo: ...
    @staticmethod
    def int32() -> TypeInfo: ...
    @staticmethod
    def int64() -> TypeInfo: ...
    @staticmethod
    def uint8() -> TypeInfo: ...
    @staticmethod
    def uint16() -> TypeInfo: ...
    @staticmethod
    def uint32() -> TypeInfo: ...
    @staticmethod
    def uint64() -> TypeInfo: ...
    @staticmethod
    def float32() -> TypeInfo: ...
    @staticmethod
    def float64() -> TypeInfo: ...
    @staticmethod
    def pointer_to(target: TypeInfo) -> TypeInfo: ...
    @staticmethod
    def array_of(element: TypeInfo, count: int) -> TypeInfo: ...
    @staticmethod
    def function_type(return_type: TypeInfo,
                      argument_types: list[TypeInfo] = ...,
                      calling_convention: CallingConvention = ...,
                      has_varargs: bool = ...) -> TypeInfo: ...
    @staticmethod
    def enum_type(members: list[EnumMember], byte_width: int = ...,
                  bitmask: bool = ...) -> TypeInfo: ...
    @staticmethod
    def from_declaration(c_declaration: str) -> TypeInfo: ...
    @staticmethod
    def create_struct() -> TypeInfo: ...
    @staticmethod
    def create_union() -> TypeInfo: ...
    @staticmethod
    def by_name(name: str) -> TypeInfo: ...
    @property
    def is_void(self) -> bool: ...
    @property
    def is_integer(self) -> bool: ...
    @property
    def is_floating_point(self) -> bool: ...
    @property
    def is_pointer(self) -> bool: ...
    @property
    def is_array(self) -> bool: ...
    @property
    def is_function(self) -> bool: ...
    @property
    def is_struct(self) -> bool: ...
    @property
    def is_union(self) -> bool: ...
    @property
    def is_enum(self) -> bool: ...
    @property
    def is_typedef(self) -> bool: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_char(self) -> bool: ...
    @property
    def is_unsigned_char(self) -> bool: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_forward_declaration(self) -> bool: ...
    @property
    def forward_declaration_kind(self) -> TypeKind: ...
    @property
    def kind(self) -> TypeKind: ...
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> int: ...
    def to_string(self) -> str: ...
    def declaration(self, declarator_name: str = ...) -> str: ...
    def pointee_type(self) -> TypeInfo: ...
    def pointer_details(self) -> PointerDetails: ...
    def with_shifted_parent(self, parent: TypeInfo,
                            byte_delta: int) -> TypeInfo: ...
    def array_element_type(self) -> TypeInfo: ...
    def array_length(self) -> int: ...
    def resolve_typedef(self) -> TypeInfo: ...
    def function_return_type(self) -> TypeInfo: ...
    def function_argument_types(self) -> list[TypeInfo]: ...
    def function_details(self) -> FunctionDetails: ...
    def with_function_argument_type(self, index: int,
                                    replacement: TypeInfo) -> TypeInfo: ...
    def with_function_argument_name(self, index: int, name: str) -> TypeInfo: ...
    def with_function_return_type(self, replacement: TypeInfo) -> TypeInfo: ...
    def calling_convention(self) -> CallingConvention: ...
    def is_variadic_function(self) -> bool: ...
    def enum_members(self) -> list[EnumMember]: ...
    def enum_details(self) -> EnumDetails: ...
    def member_count(self) -> int: ...
    def members(self) -> list[Member]: ...
    def udt_details(self) -> UdtDetails: ...
    def set_udt_semantics(self, is_cpp_object: bool,
                          is_vftable: bool) -> None: ...
    def member_by_name(self, name: str) -> Member: ...
    def member_by_offset(self, byte_offset: int) -> Member: ...
    def member_references(self, byte_offset: int) -> list[int]: ...
    def ensure_member_reference(self, byte_offset: int,
                                source_address: int) -> bool: ...
    def add_member(self, name: str, member_type: TypeInfo,
                   byte_offset: int = ...) -> None: ...
    def apply(self, address: int) -> None: ...
    def save_as(self, name: str) -> None: ...
    def replace_forward_declaration(self, name: str) -> TypeInfo: ...

class Member:
    name: str
    type: TypeInfo
    byte_offset: int
    bit_size: int
    bit_offset: int
    storage_byte_width: int
    is_baseclass: bool
    is_vftable: bool
    is_gap: bool
    is_bitfield: bool
    comment: str
    def __init__(self) -> None: ...

class PointerDetails:
    pointee_type: TypeInfo
    shifted_parent: TypeInfo | None
    shift_delta: int
    is_shifted: bool
    def __init__(self) -> None: ...

class FunctionArgument:
    name: str
    type: TypeInfo
    def __init__(self) -> None: ...

class FunctionDetails:
    return_type: TypeInfo
    arguments: list[FunctionArgument]
    calling_convention: CallingConvention
    variadic: bool
    def __init__(self) -> None: ...

class UdtDetails:
    total_size: int
    is_union: bool
    is_cpp_object: bool
    is_vftable: bool
    members: list[Member]
    def __init__(self) -> None: ...

class EnumDetails:
    byte_width: int
    signed_values: bool
    radix: EnumRadix
    members: list[EnumMember]
    def __init__(self) -> None: ...

def retrieve(address: int) -> TypeInfo: ...
def retrieve_operand(address: int, operand_index: int) -> TypeInfo: ...
def remove_type(address: int) -> None: ...
def load_type_library(name: str) -> bool: ...
def unload_type_library(name: str) -> None: ...
def local_type_count() -> int: ...
def local_type_name(ordinal: int) -> str: ...
def import_type(source_library: str, type_name: str) -> int: ...
def ensure_named_type(type_name: str,
                      source_library: str = ...) -> TypeInfo: ...
def apply_named_type(address: int, type_name: str) -> None: ...
def parse_declarations(declarations: str,
                       options: ParseDeclarationsOptions = ...) -> ParseDeclarationsReport: ...
def render_named_declarations(names: list[str], max_depth: int = ...,
                              options: TypeRenderOptions = ...) -> str: ...
def render_ordinal_declarations(ordinals: list[int],
                                options: TypeRenderOptions = ...) -> str: ...
def render_type_graph(root_name: str,
                      options: TypeGraphOptions = ...) -> str: ...
def declarations_for_ordinals(ordinals: list[int]) -> list[TypeDeclaration]: ...
