from enum import Enum
from typing import Callable, overload
from .address import Range
from .plugin import HostHandle

class WidgetType(Enum):
    UNKNOWN = ...
    EXPORTS = ...
    IMPORTS = ...
    NAMES = ...
    FUNCTIONS = ...
    STRINGS = ...
    SEGMENTS = ...
    SEGREGS = ...
    SELECTORS = ...
    SIGNATURES = ...
    TYPE_LIBRARIES = ...
    LOCAL_TYPES = ...
    PROBLEMS = ...
    BREAKPOINTS = ...
    THREADS = ...
    MODULES = ...
    TRACE_LOG = ...
    CALL_STACK = ...
    CROSS_REFS = ...
    SEARCH_RESULTS = ...
    STACK_FRAME = ...
    NAV_BAND = ...
    DISASSEMBLY = ...
    HEX_VIEW = ...
    NOTEPAD = ...
    OUTPUT = ...
    COMMAND_LINE = ...
    CHOOSER = ...
    PSEUDOCODE = ...
    MICROCODE = ...

class DockPosition(Enum):
    LEFT = ...
    RIGHT = ...
    TOP = ...
    BOTTOM = ...
    FLOATING = ...
    TAB = ...

class ColumnFormat(Enum):
    PLAIN = ...
    PATH = ...
    HEX = ...
    DECIMAL = ...
    ADDRESS = ...
    FUNCTION_NAME = ...

class EventKind(Enum):
    DATABASE_INITED = ...
    DATABASE_CLOSED = ...
    READY_TO_RUN = ...
    CURRENT_WIDGET_CHANGED = ...
    SCREEN_ADDRESS_CHANGED = ...
    WIDGET_VISIBLE = ...
    WIDGET_INVISIBLE = ...
    WIDGET_CLOSING = ...
    VIEW_ACTIVATED = ...
    VIEW_DEACTIVATED = ...
    VIEW_CREATED = ...
    VIEW_CLOSED = ...
    CURSOR_CHANGED = ...

class FormBinding: ...

class FormSvalBinding(FormBinding):
    value: int
    def __init__(self, value: int = ...) -> None: ...

class FormIntBinding(FormSvalBinding):
    def __init__(self, value: int = ...) -> None: ...

class FormU16Binding(FormBinding):
    value: int
    def __init__(self, value: int = ...) -> None: ...

class FormAddressBinding(FormBinding):
    value: int
    def __init__(self, value: int = ...) -> None: ...

class FormTextBinding(FormBinding):
    value: str
    def __init__(self, value: str = ...) -> None: ...

class FormPathBinding(FormBinding):
    value: str
    for_saving: bool
    def __init__(self, value: str = ..., for_saving: bool = ...) -> None: ...

class FormBuilder:
    def __init__(self, title: str) -> None: ...
    @property
    def markup(self) -> str: ...
    @property
    def bindings(self) -> list[FormBinding]: ...
    def add_int(self, label: str, value: int = ..., width: int = ...,
                visible_width: int = ...) -> FormIntBinding: ...
    def add_sval(self, label: str, value: int = ..., width: int = ...,
                 visible_width: int = ...) -> FormSvalBinding: ...
    def add_bitset(self, group_label: str, value: int = ...,
                   choices: list[str] = ...) -> FormU16Binding: ...
    def add_radio(self, group_label: str, value: int = ...,
                  choices: list[str] = ...) -> FormU16Binding: ...
    def add_address(self, label: str, value: int = ..., width: int = ...,
                    visible_width: int = ...) -> FormAddressBinding: ...
    def add_text(self, label: str, value: str = ..., width: int = ...,
                 visible_width: int = ...) -> FormTextBinding: ...
    def add_path(self, label: str, value: str = ..., for_saving: bool = ...,
                 visible_width: int = ...) -> FormPathBinding: ...
    def ask(self) -> bool: ...

class WaitBox:
    def __init__(self, message: str) -> None: ...
    @property
    def active(self) -> bool: ...
    @property
    def cancelled(self) -> bool: ...
    def update(self, message: str) -> None: ...
    def dismiss(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> WaitBox: ...
    def __exit__(self, exc_type: object, exc_value: object,
                 traceback: object) -> bool: ...

class Progress:
    phase: str
    processed: int
    total: int
    current_item: str
    def __init__(self) -> None: ...

class ShowWidgetOptions:
    position: DockPosition
    restore_previous: bool
    def __init__(self) -> None: ...

class Widget:
    def __init__(self) -> None: ...
    @property
    def valid(self) -> bool: ...
    @property
    def title(self) -> str: ...
    @property
    def id(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

class Column:
    name: str
    width: int
    format: ColumnFormat
    def __init__(self) -> None: ...

class RowStyle:
    bold: bool
    italic: bool
    strikethrough: bool
    gray: bool
    background_color: int
    def __init__(self) -> None: ...

class Row:
    columns: list[str]
    icon: int
    style: RowStyle
    def __init__(self) -> None: ...

class ChooserOptions:
    title: str
    columns: list[Column]
    modal: bool
    can_insert: bool
    can_delete: bool
    can_edit: bool
    can_refresh: bool
    def __init__(self) -> None: ...

class Chooser:
    def __init__(self, options: ChooserOptions) -> None: ...
    def count(self) -> int: ...
    def row(self, index: int) -> Row: ...
    def address_for(self, index: int) -> int: ...
    def on_insert(self, before_index: int) -> None: ...
    def on_delete(self, index: int) -> None: ...
    def on_edit(self, index: int) -> None: ...
    def on_enter(self, index: int) -> None: ...
    def on_refresh(self) -> None: ...
    def on_close(self) -> None: ...
    def show(self, default_selection: int = ...) -> int | None: ...
    def refresh(self) -> None: ...
    def close(self) -> None: ...
    @property
    def options(self) -> ChooserOptions: ...

class Event:
    kind: EventKind
    address: int
    previous_address: int
    previous_widget: Widget
    is_new_database: bool
    startup_script: str
    widget: Widget
    widget_title: str
    def __init__(self) -> None: ...

class ScopedSubscription:
    def __init__(self, token: int = 0) -> None: ...
    @property
    def token(self) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> ScopedSubscription: ...
    def __exit__(self, exc_type: object, exc_value: object,
                 traceback: object) -> bool: ...

class PopupEvent:
    widget: Widget
    popup: HostHandle
    type: WidgetType

class LineRenderEntry:
    line_number: int
    background_color: int
    start_column: int
    length: int
    character_range: bool
    def __init__(self) -> None: ...

class RenderingEvent:
    widget: Widget
    type: WidgetType
    entries: list[LineRenderEntry]

def message(text: str) -> None: ...
def warning(text: str) -> None: ...
def info(text: str) -> None: ...
def ask_yn(question: str, default_yes: bool = ...) -> bool: ...
def ask_string(prompt: str, default_value: str = ...) -> str: ...
def ask_file(for_saving: bool, default_path: str = ..., prompt: str = ...) -> str: ...
def ask_address(prompt: str, default_value: int = ...) -> int: ...
def ask_long(prompt: str, default_value: int = ...) -> int: ...
def ask_text(prompt: str, default_value: str = ..., max_size: int = ...,
             accept_tabs: bool = ..., normal_font: bool = ...) -> str: ...
def ask_form(markup: str, *bindings: FormBinding) -> bool: ...
def copy_to_clipboard(text: str) -> None: ...
def read_clipboard() -> str: ...
def clipboard_backend() -> str: ...
def form_sval(value: int = ...) -> FormSvalBinding: ...
def form_int(value: int = ...) -> FormIntBinding: ...
def form_bitset(value: int = ...) -> FormU16Binding: ...
def form_radio(value: int = ...) -> FormU16Binding: ...
def form_address(value: int = ...) -> FormAddressBinding: ...
def form_text(value: str = ...) -> FormTextBinding: ...
def form_path(value: str = ..., for_saving: bool = ...) -> FormPathBinding: ...
def form_builder(title: str) -> FormBuilder: ...
def jump_to(address: int) -> None: ...
def screen_address() -> int: ...
def selection() -> Range: ...
def widget_type(widget: Widget | HostHandle) -> WidgetType: ...
def create_widget(title: str) -> Widget: ...
def create_custom_viewer(title: str, lines: list[str]) -> Widget: ...
def set_custom_viewer_lines(viewer: Widget, lines: list[str]) -> None: ...
def custom_viewer_line_count(viewer: Widget) -> int: ...
def custom_viewer_jump_to_line(viewer: Widget, line_index: int, x: int = ...,
                               y: int = ...) -> None: ...
def custom_viewer_current_line(viewer: Widget, mouse: bool = ...) -> str: ...
def refresh_custom_viewer(viewer: Widget) -> None: ...
def close_custom_viewer(viewer: Widget) -> None: ...
def show_widget(widget: Widget, options: ShowWidgetOptions = ...) -> None: ...
def activate_widget(widget: Widget) -> None: ...
def current_widget() -> Widget: ...
def find_widget(title: str) -> Widget: ...
def close_widget(widget: Widget) -> None: ...
def is_widget_visible(widget: Widget) -> bool: ...
def widget_host(widget: Widget) -> HostHandle: ...
def with_widget_host(widget: Widget,
                     callback: Callable[[HostHandle], None]) -> None: ...
def register_timer(interval_ms: int, callback: Callable[[], int]) -> int: ...
def unregister_timer(token: int) -> None: ...
def on_database_closed(callback: Callable[[], None]) -> int: ...
def on_database_inited(callback: Callable[[bool, str], None]) -> int: ...
def on_ready_to_run(callback: Callable[[], None]) -> int: ...
def on_screen_ea_changed(callback: Callable[[int, int], None]) -> int: ...
def on_current_widget_changed(callback: Callable[[Widget, Widget], None]) -> int: ...
@overload
def on_widget_visible(callback: Callable[[str], None]) -> int: ...
@overload
def on_widget_visible(widget: Widget, callback: Callable[[Widget], None]) -> int: ...
@overload
def on_widget_invisible(callback: Callable[[str], None]) -> int: ...
@overload
def on_widget_invisible(widget: Widget, callback: Callable[[Widget], None]) -> int: ...
@overload
def on_widget_closing(callback: Callable[[str], None]) -> int: ...
@overload
def on_widget_closing(widget: Widget, callback: Callable[[Widget], None]) -> int: ...
def on_cursor_changed(callback: Callable[[int], None]) -> int: ...
def on_view_activated(callback: Callable[[Widget], None]) -> int: ...
def on_view_deactivated(callback: Callable[[Widget], None]) -> int: ...
def on_view_created(callback: Callable[[Widget], None]) -> int: ...
def on_view_closed(callback: Callable[[Widget], None]) -> int: ...
def on_event(callback: Callable[[Event], None]) -> int: ...
def on_event_filtered(filter: Callable[[Event], bool],
                      callback: Callable[[Event], None]) -> int: ...
def unsubscribe(token: int) -> None: ...
def on_popup_ready(callback: Callable[[PopupEvent], None]) -> int: ...
def attach_dynamic_action(popup: HostHandle, widget: Widget, action_id: str,
                          label: str, handler: Callable[[], None],
                          menu_path: str = ..., icon: int = ...) -> None: ...
def attach_registered_action(popup: HostHandle, widget: Widget | HostHandle,
                             action_id: str, menu_path: str = ...) -> None: ...
def on_rendering_info(callback: Callable[[RenderingEvent], None]) -> int: ...
def user_directory() -> str: ...
def refresh_all_views() -> None: ...
