def create_point(action_name: str, label: str) -> bool: ...
def undo_action_label() -> str | None: ...
def redo_action_label() -> str | None: ...
def perform_undo() -> bool: ...
def perform_redo() -> bool: ...
