from collections.abc import Iterator
from enum import Enum

class CodeType(Enum):
    CALL_FAR = ...
    CALL_NEAR = ...
    JUMP_FAR = ...
    JUMP_NEAR = ...
    FLOW = ...

class DataType(Enum):
    OFFSET = ...
    WRITE = ...
    READ = ...
    TEXT = ...
    INFORMATIONAL = ...

class ReferenceType(Enum):
    UNKNOWN = ...
    FLOW = ...
    CALL_NEAR = ...
    CALL_FAR = ...
    JUMP_NEAR = ...
    JUMP_FAR = ...
    OFFSET = ...
    READ = ...
    WRITE = ...
    TEXT = ...
    INFORMATIONAL = ...

class Reference:
    from_address: int
    to_address: int
    is_code: bool
    type: ReferenceType
    user_defined: bool
    def __init__(self) -> None: ...

class ReferenceRange:
    def __iter__(self) -> Iterator[Reference]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

def add_code(from_address: int, to_address: int, type: CodeType) -> None: ...
def add_data(from_address: int, to_address: int, type: DataType) -> None: ...
def remove_code(from_address: int, to_address: int) -> None: ...
def remove_data(from_address: int, to_address: int) -> None: ...
def refs_from(address: int, type: ReferenceType | None = ...) -> list[Reference]: ...
def refs_to(address: int, type: ReferenceType | None = ...) -> list[Reference]: ...
def code_refs_from(address: int) -> list[Reference]: ...
def code_refs_to(address: int) -> list[Reference]: ...
def data_refs_from(address: int) -> list[Reference]: ...
def data_refs_to(address: int) -> list[Reference]: ...
def refs_from_range(address: int) -> ReferenceRange: ...
def refs_to_range(address: int) -> ReferenceRange: ...
def code_refs_from_range(address: int) -> ReferenceRange: ...
def code_refs_to_range(address: int) -> ReferenceRange: ...
def data_refs_from_range(address: int) -> ReferenceRange: ...
def data_refs_to_range(address: int) -> ReferenceRange: ...
def is_call(type: ReferenceType) -> bool: ...
def is_jump(type: ReferenceType) -> bool: ...
def is_flow(type: ReferenceType) -> bool: ...
def is_data(type: ReferenceType) -> bool: ...
def is_data_read(type: ReferenceType) -> bool: ...
def is_data_write(type: ReferenceType) -> bool: ...
